//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class LSBundleProxy, NSArray, NSOperationQueue, SDAirDropHandler, SDAirDropHandleriCloudDrive;

@interface SDAirDropHandlerGenericFiles
{
    NSOperationQueue *_workOperationsQueue;	// 8 = 0x8
    SDAirDropHandleriCloudDrive *_icloudDriveHandler;	// 16 = 0x10
    SDAirDropHandler *_selectedHandler;	// 24 = 0x18
    LSBundleProxy *_selectedProxy;	// 32 = 0x20
    _Bool _willUseOpenWithAlert;	// 40 = 0x28
    NSArray *_availableApplications;	// 48 = 0x30
    LSBundleProxy *_selectedApplication;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x00200000000ac4ce
@property(retain, nonatomic) LSBundleProxy *selectedApplication; // @synthesize selectedApplication=_selectedApplication;
@property(copy, nonatomic) NSArray *availableApplications; // @synthesize availableApplications=_availableApplications;
- (void)openResourceOperation:(id)arg1 didFailWithError:(id)arg2;	// IMP=0x00100000000ac41f
- (void)openResourceOperationDidComplete:(id)arg1;	// IMP=0x00100000000ac35b
- (void)openResourceOperation:(id)arg1 didFinishCopyingResource:(id)arg2;	// IMP=0x00100000000ac270
- (void)performActionWithBundleProxy:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000abbfe
- (void)addOpenWithActions;	// IMP=0x00100000000ab8b2
- (void)acceptActionTriggered;	// IMP=0x00100000000ab7bf
- (_Bool)shouldOpenAutomaticallyAfterUserAccepts;	// IMP=0x00100000000ab6c7
- (id)actionForBundleProxy:(id)arg1;	// IMP=0x00100000000ab512
- (id)cancelActionTitleToAccompanyActions:(id)arg1;	// IMP=0x00100000000ab4b1
- (void)updatePossibleActions;	// IMP=0x00100000000ab17d
- (id)suitableContentsDescription;	// IMP=0x00100000000aaf47
- (id)firstReceivedFilename;	// IMP=0x00100000000aae7c
- (long long)transferTypes;	// IMP=0x00100000000aae47
- (_Bool)canHandleTransfer;	// IMP=0x00100000000aae35
- (id)initWithTransfer:(id)arg1 bundleIdentifier:(id)arg2;	// IMP=0x00100000000aad5e
- (id)initWithTransfer:(id)arg1;	// IMP=0x00100000000aad4a

@end

