//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSMutableDictionary, NSString, SDAirDropTransferManager;

@interface SDAirDropClassroomTransferManager
{
    NSMutableDictionary *_transferIDToProgress;	// 8 = 0x8
    SDAirDropTransferManager *_transferManager;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000018fb1c
@property(retain, nonatomic) SDAirDropTransferManager *transferManager; // @synthesize transferManager=_transferManager;
- (void)connectionInvalidated:(id)arg1;	// IMP=0x001000000018f9a8
- (void)connectionEstablished:(id)arg1;	// IMP=0x001000000018f89f
- (_Bool)shouldAcceptNewConnection:(id)arg1;	// IMP=0x001000000018f897
- (id)remoteObjectInterface;	// IMP=0x001000000018f877
- (id)exportedInterface;	// IMP=0x001000000018f727
- (id)machServiceName;	// IMP=0x001000000018f71a
- (void)alertManager:(id)arg1 cancelingTransferWithRecordID:(id)arg2 withFailureReason:(unsigned long long)arg3;	// IMP=0x001000000018f53d
- (void)alertManager:(id)arg1 acceptingTransferWithRecordID:(id)arg2 withDestinationURL:(id)arg3 shouldExtractMediaFromPhotosBundlesForRecordID:(_Bool)arg4;	// IMP=0x001000000018f36e
- (void)updateTransferWithIdentifier:(id)arg1 withState:(long long)arg2 information:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x001000000018e996
- (void)replaceIconValue:(id)arg1 forKey:(id)arg2;	// IMP=0x001000000018e876
- (id)makeDestinationDirectoryWithIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x001000000018e5f1
- (void)_enumerateRemoteObjectProxiesUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000018e5df
- (void)invalidate;	// IMP=0x001000000018e5b0
- (void)activate;	// IMP=0x001000000018e581
- (id)init;	// IMP=0x001000000018e524

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

