//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSSet, NSString, UNUserNotificationCenter;
@protocol OS_dispatch_queue;

@interface SDNotificationManager : NSObject
{
    _Bool _activated;	// 8 = 0x8
    NSMutableDictionary *_autoFillRequests;	// 16 = 0x10
    UNUserNotificationCenter *_homePodNotifCenter;	// 24 = 0x18
    UNUserNotificationCenter *_homePodMiniNotificationCenter;	// 32 = 0x20
    _Bool _homePodNotifGranted;	// 40 = 0x28
    NSMutableDictionary *_homePodRequests;	// 48 = 0x30
    _Bool _invalidated;	// 56 = 0x38
    NSMutableDictionary *_tvKeyboardRequests;	// 64 = 0x40
    UNUserNotificationCenter *_tvNotifCenter;	// 72 = 0x48
    _Bool _tvNotifGranted;	// 80 = 0x50
    NSMutableDictionary *_watchKeyboardRequests;	// 88 = 0x58
    UNUserNotificationCenter *_watchNotifCenter;	// 96 = 0x60
    _Bool _watchNotifGranted;	// 104 = 0x68
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 112 = 0x70
}

+ (id)sharedManager;	// IMP=0x00200000000ff628
- (void).cxx_destruct;	// IMP=0x00200000001078ad
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
- (void)testWatchKeyboardAutoFill;	// IMP=0x00100000001077b4
- (void)testWatchKeyboard;	// IMP=0x00100000001076e8
- (void)testKeyboardUpdate;	// IMP=0x001000000010761b
- (void)testKeyboardRemove;	// IMP=0x001000000010754f
- (void)testKeyboardPostAutoFill;	// IMP=0x001000000010746f
- (void)testKeyboardPost;	// IMP=0x00100000001073a1
- (void)testHandoffPost;	// IMP=0x0010000000107210
- (void)testAutoFillRemove;	// IMP=0x0010000000107144
- (void)testAutofillPost;	// IMP=0x0010000000107078
- (void)testPostBasic;	// IMP=0x0010000000106f41
- (void)testPost:(id)arg1;	// IMP=0x0010000000106d6d
- (void)userNotificationCenter:(id)arg1 didReceiveNotificationResponse:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;	// IMP=0x00100000001067f5
- (void)_homePodHandleResponse:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000001062f3
- (void)_homePodHandoffUpdateIfNeeded:(id)arg1 info:(id)arg2;	// IMP=0x0010000000105dee
- (void)homePodHandoffUpdateIfNeeded:(id)arg1 info:(id)arg2;	// IMP=0x0010000000105d16
- (void)_homePodHandoffRemoveAll;	// IMP=0x0010000000105c66
- (void)homePodHandoffRemoveAll;	// IMP=0x0010000000105c05
- (void)_homePodHandoffRemove:(id)arg1 reason:(long long)arg2;	// IMP=0x0010000000105996
- (void)homePodHandoffRemove:(id)arg1 reason:(long long)arg2;	// IMP=0x00100000001058de
- (void)_homePodHandoffPostIfNeeded:(id)arg1 info:(id)arg2;	// IMP=0x0010000000105707
- (void)homePodHandoffPostIfNeeded:(id)arg1 info:(id)arg2;	// IMP=0x001000000010562f
- (id)homePodHandoffContentForDevice:(id)arg1 info:(id)arg2;	// IMP=0x0010000000105133
- (void)_watchHandleResponse:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000105098
- (void)_watchKeyboardUpdate:(id)arg1 rtiData:(id)arg2;	// IMP=0x0010000000104a1c
- (void)watchKeyboardUpdate:(id)arg1 rtiData:(id)arg2;	// IMP=0x0010000000104944
- (void)_watchKeyboardUpdate:(id)arg1 info:(id)arg2;	// IMP=0x00100000001044c9
- (void)watchKeyboardUpdate:(id)arg1 info:(id)arg2;	// IMP=0x00100000001043f1
- (void)_watchKeyboardRemoveAll;	// IMP=0x001000000010436d
- (void)watchKeyboardRemoveAll;	// IMP=0x001000000010430c
- (void)_watchKeyboardRemove:(id)arg1;	// IMP=0x0010000000104186
- (void)watchKeyboardRemove:(id)arg1;	// IMP=0x00100000001040de
- (void)_watchKeyboardPostIfNeeded:(id)arg1;	// IMP=0x0010000000103f58
- (void)watchKeyboardPostIfNeeded:(id)arg1;	// IMP=0x0010000000103eb0
- (id)watchKeyboardContentForDevice:(id)arg1;	// IMP=0x0010000000103b7f
- (void)_tvAutoFillRemoveAll;	// IMP=0x0010000000103aef
- (void)tvAutoFillRemoveAll;	// IMP=0x0010000000103a8e
- (void)_tvAutoFillRemove:(id)arg1;	// IMP=0x0010000000103908
- (void)tvAutoFillRemove:(id)arg1;	// IMP=0x0010000000103860
- (void)_tvAutoFillPostIfNeeded:(id)arg1;	// IMP=0x0010000000103515
- (void)tvAutoFillPostIfNeeded:(id)arg1;	// IMP=0x001000000010346d
@property(readonly, copy, nonatomic) NSSet *activeTVAutoFillPrompts;
- (void)_riServerUpdate:(id)arg1 rtiData:(id)arg2;	// IMP=0x0010000000102d77
- (void)riServerUpdate:(id)arg1 rtiData:(id)arg2;	// IMP=0x0010000000102c9f
- (void)_riServerUpdate:(id)arg1 info:(id)arg2;	// IMP=0x0010000000102824
- (void)riServerUpdate:(id)arg1 info:(id)arg2;	// IMP=0x001000000010274c
- (void)_riServerRemoveAll;	// IMP=0x00100000001026c8
- (void)riServerRemoveAll;	// IMP=0x0010000000102667
- (void)_riServerRemove:(id)arg1;	// IMP=0x00100000001024e1
- (void)riServerRemove:(id)arg1;	// IMP=0x0010000000102439
- (void)_riServerPostIfNeeded:(id)arg1 backgroundAction:(_Bool)arg2;	// IMP=0x0010000000102288
- (void)riServerPostIfNeeded:(id)arg1 backgroundAction:(_Bool)arg2;	// IMP=0x00100000001021d0
- (id)riServerContentForDevice:(id)arg1 backgroundAction:(_Bool)arg2;	// IMP=0x0010000000101ee3
- (void)_tvHandleResponse:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000010188a
- (id)attachmentFromURL:(id)arg1;	// IMP=0x0010000000101687
- (void)_addRequestWithID:(id)arg1 content:(id)arg2 type:(unsigned int)arg3 isHomePodMini:(_Bool)arg4;	// IMP=0x0010000000100d93
- (void)_addRequestWithID:(id)arg1 content:(id)arg2 type:(unsigned int)arg3;	// IMP=0x0010000000100d7e
- (void)_homePodEnsureStarted:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000100611
- (void)_watchEnsureStarted:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000100262
- (void)_riServerEnsureStarted:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000ffea6
- (void)_update;	// IMP=0x00100000000ffe48
- (void)prefsChanged;	// IMP=0x00100000000ffe36
- (void)_invalidate;	// IMP=0x00100000000ffde9
- (void)invalidate;	// IMP=0x00100000000ffd88
- (void)_activate;	// IMP=0x00100000000ffd07
- (void)activate;	// IMP=0x00100000000ffca4
@property(readonly, copy) NSString *description;
- (id)init;	// IMP=0x00100000000ff67d

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

