//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSString;

@interface SDUnlockDisable : PBCodable
{
    NSString *_pairingID;	// 8 = 0x8
    unsigned int _version;	// 16 = 0x10
    CDStruct_f20694ce _has;	// 20 = 0x14
}

- (void).cxx_destruct;	// IMP=0x00200000000910a6
@property(retain, nonatomic) NSString *pairingID; // @synthesize pairingID=_pairingID;
@property(nonatomic) unsigned int version; // @synthesize version=_version;
- (void)mergeFrom:(id)arg1;	// IMP=0x001000000009100e
- (unsigned long long)hash;	// IMP=0x0010000000090fc2
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000090efd
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000090e6d
- (void)copyTo:(id)arg1;	// IMP=0x0010000000090e0a
- (void)writeTo:(id)arg1;	// IMP=0x0010000000090da6
- (_Bool)readFrom:(id)arg1;	// IMP=0x0010000000090d99
- (id)dictionaryRepresentation;	// IMP=0x0010000000090ac1
- (id)description;	// IMP=0x0010000000090a12
@property(readonly, nonatomic) _Bool hasPairingID;
@property(nonatomic) _Bool hasVersion;

@end

