//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSObject;
@protocol OS_dispatch_queue;

@interface CSMediaPlayingMonitor
{
    long long _mediaIsPlaying;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_queue;	// 16 = 0x10
}

+ (id)sharedInstance;	// IMP=0x00400000000e24a9
- (void).cxx_destruct;	// IMP=0x00200000000e2d07
- (void)mediaPlayingStateWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000000e2c52
- (long long)mediaPlayingState;	// IMP=0x00100000000e2b9e
- (void)_notifyObserver:(id)arg1 mediaIsPlayingState:(long long)arg2;	// IMP=0x00100000000e2b2a
- (void)_notePossiblePlayPausedStateChange:(id)arg1;	// IMP=0x00100000000e299d
- (void)_stopMonitoring;	// IMP=0x00100000000e28ca
- (void)_startMonitoringWithQueue:(id)arg1;	// IMP=0x00100000000e27be
- (void)initializeMediaPlayingState;	// IMP=0x00100000000e2591
- (id)init;	// IMP=0x00100000000e2523

@end

