//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString;
@protocol CSConnectionServiceDelegate, CSSmartSiriVolumeProcessor, OS_dispatch_queue;

@interface CSSmartSiriVolumeManager : NSObject
{
    id <CSConnectionServiceDelegate> _delegate;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_queue;	// 16 = 0x10
    id <CSSmartSiriVolumeProcessor> _smartSiriVolume;	// 24 = 0x18
}

+ (id)sharedInstance;	// IMP=0x00200000000c5d8c
- (void).cxx_destruct;	// IMP=0x00200000000c68d7
@property(retain, nonatomic) id <CSSmartSiriVolumeProcessor> smartSiriVolume; // @synthesize smartSiriVolume=_smartSiriVolume;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(nonatomic) __weak id <CSConnectionServiceDelegate> delegate; // @synthesize delegate=_delegate;
- (MISSING_TYPE *)CSAutomaticVolumeEnabledMonitor:didReceiveEnabled: /* Error: Ran out of types for this method. */;	// IMP=0x00100000000c674d
- (void)voiceTriggerDidDetectKeyword:(id)arg1 deviceId:(id)arg2;	// IMP=0x00100000000c6666
- (void)CSVolumeMonitor:(id)arg1 didReceiveAlarmVolumeChanged:(float)arg2;	// IMP=0x00100000000c651d
- (void)CSVolumeMonitor:(id)arg1 didReceiveMusicVolumeChanged:(float)arg2;	// IMP=0x00100000000c63d4
- (void)CSTimerMonitor:(id)arg1 didReceiveTimerChanged:(long long)arg2;	// IMP=0x00100000000c6297
- (void)CSAlarmMonitor:(id)arg1 didReceiveAlarmChanged:(long long)arg2;	// IMP=0x00100000000c615a
- (void)setPermanentVolumeOffsetWithDirection:(_Bool)arg1;	// IMP=0x00100000000c6144
- (void)setSmartSiriVolumeDirection:(_Bool)arg1;	// IMP=0x00100000000c612e
- (void)setSmartSiriVolumePercentage:(float)arg1;	// IMP=0x00100000000c6118
- (id)getVolumeForTTSType:(unsigned long long)arg1 withOverrideMediaVolume:(id)arg2 WithRequestTime:(unsigned long long)arg3;	// IMP=0x00100000000c6102
- (void)setAsset:(id)arg1;	// IMP=0x00100000000c60ec
- (void)startSmartSiriVolume;	// IMP=0x00100000000c60d6
- (id)initWithSamplingRate:(float)arg1 withAsset:(id)arg2;	// IMP=0x00100000000c5e71

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

