//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class IDSServerBag, NSMutableDictionary;
@protocol IDSCoalesceMessageQueueManagerDelegate;

@interface IDSCoalesceMessageQueueManager : NSObject
{
    struct os_unfair_lock_s _lock;	// 8 = 0x8
    id <IDSCoalesceMessageQueueManagerDelegate> _delegate;	// 16 = 0x10
    NSMutableDictionary *_queueMap;	// 24 = 0x18
    NSMutableDictionary *_timerMap;	// 32 = 0x20
    NSMutableDictionary *_rateLimitMap;	// 40 = 0x28
    IDSServerBag *_bag;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x002000000029fb10
@property(nonatomic) struct os_unfair_lock_s lock; // @synthesize lock=_lock;
@property(retain, nonatomic) IDSServerBag *bag; // @synthesize bag=_bag;
@property(retain, nonatomic) NSMutableDictionary *rateLimitMap; // @synthesize rateLimitMap=_rateLimitMap;
@property(retain, nonatomic) NSMutableDictionary *timerMap; // @synthesize timerMap=_timerMap;
@property(retain, nonatomic) NSMutableDictionary *queueMap; // @synthesize queueMap=_queueMap;
@property __weak id <IDSCoalesceMessageQueueManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)handleRateLimitingResponseForTopic:(id)arg1 ttr:(id)arg2;	// IMP=0x001000000029f760
- (_Bool)_isTopicBeingRateLimited:(id)arg1;	// IMP=0x001000000029f6e0
- (id)loggableOverviewForTopic:(id)arg1;	// IMP=0x001000000029f510
- (id)formattedKeyForTopic:(id)arg1 sendMode:(id)arg2;	// IMP=0x001000000029f380
- (double)defaultDelayForSendMode:(id)arg1;	// IMP=0x001000000029f290
- (double)coalesceDelayForTopic:(id)arg1 sendMode:(id)arg2;	// IMP=0x001000000029f0c0
- (void)_timerFired:(id)arg1;	// IMP=0x001000000029ef70
- (void)_resetTimerForTopic:(id)arg1 withDelay:(double)arg2;	// IMP=0x001000000029ee20
- (void)_clearTimerForTopic:(id)arg1;	// IMP=0x001000000029ec60
- (void)_createTimerForTopic:(id)arg1 withDelay:(double)arg2;	// IMP=0x001000000029ead0
- (void)_updateTimerForTopic:(id)arg1 sendMode:(id)arg2;	// IMP=0x001000000029e730
- (_Bool)coalesceQueueExistsForTopic:(id)arg1;	// IMP=0x001000000029e5b0
- (void)flushCoalesceQueueForTopic:(id)arg1;	// IMP=0x001000000029e020
- (void)_clearQueueForTopic:(id)arg1;	// IMP=0x001000000029dec0
- (void)enqueueMessage:(id)arg1 forTopic:(id)arg2 sendMode:(id)arg3;	// IMP=0x001000000029db10
- (void)handleMessageToCoalesce:(id)arg1 forTopic:(id)arg2 sendMode:(id)arg3;	// IMP=0x001000000029da40
- (id)initWithBag:(id)arg1;	// IMP=0x001000000029d910

@end

