//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface IDSDeviceAccountMigration : NSObject
{
}

+ (void)migrateToNewBAACert;	// IMP=0x00400000004bd740
+ (void)migrateAwayFromMultiwayAppleIDAccountsWithAccountController:(id)arg1 serviceController:(id)arg2;	// IMP=0x00100000004bd1a0
+ (void)migrateATVToSupportDeviceAccountsIfNeededWithAccountController:(id)arg1 serviceController:(id)arg2;	// IMP=0x00100000004bd050

@end

