//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface IDSDaemonCapabilities : NSObject
{
    int _supportedServicesToken;	// 8 = 0x8
}

+ (id)sharedInstance;	// IMP=0x002000000038c830
@property(nonatomic) int supportedServicesToken; // @synthesize supportedServicesToken=_supportedServicesToken;
- (void)_deferredUpdateCapabilities;	// IMP=0x001000000038d130
- (void)carrierBundleInformationDidChange;	// IMP=0x001000000038d070
- (void)_setupTokens;	// IMP=0x001000000038d030
- (void)_listenForMGChanges;	// IMP=0x001000000038d020
- (void)_updateCapabilities;	// IMP=0x001000000038c9f0
- (void)dealloc;	// IMP=0x001000000038c9b0
- (id)init;	// IMP=0x001000000038c8f0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

