//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface IDSKeyTransparencyPolicy : NSObject
{
}

- (_Bool)isKeyTransparencyUIEnabled;	// IMP=0x0040000000757ae0
- (_Bool)shouldSyncTrustCircleAfterSelfQueryForServiceIdentifier:(id)arg1;	// IMP=0x00100000007576e0
- (_Bool)isKeyTransparencySFAnalyticsEnabled;	// IMP=0x00100000007575c0
- (_Bool)isKeyTransparencyRTCAnalyticsEnabled;	// IMP=0x0010000000757490
- (MISSING_TYPE *)isKeyTransparencyAnalyticsEnabled;	// IMP=0x0010000000757370
- (unsigned long long)keyTransparencyMaximumVerificationsPerXPCActivity;	// IMP=0x0010000000757250
- (unsigned long long)keyTransparencyXPCActivityIntervalInSeconds;	// IMP=0x0010000000757110
- (_Bool)isKeyTransparencyXPCActivityEnabled;	// IMP=0x0010000000756ff0
- (_Bool)isKeyTransparencyAccountKeyCircleEnabled;	// IMP=0x0010000000756e90
- (_Bool)isKeyTransparencyCloudKitCircleEnabled;	// IMP=0x0010000000756d30
- (_Bool)isKeyTransparencyTrustCircleEnabled;	// IMP=0x0010000000756cd0
- (_Bool)isKeyTransparencyEnabledForServiceType:(id)arg1;	// IMP=0x0010000000756ba0
- (_Bool)isKeyTransparencyEnabledForServiceIdentifier:(id)arg1;	// IMP=0x00100000007569d0
- (_Bool)_isKeyTransparencyDisabledViaServerBag;	// IMP=0x00100000007568d0
- (_Bool)_isKeyTransparencyEnabledViaServerBag;	// IMP=0x00100000007568a0
- (_Bool)_isKeyTransparencyEnabledViaDefaults;	// IMP=0x0010000000756840
- (_Bool)isKeyTransparencyTrustCircleAllowedWithoutEnrollment;	// IMP=0x0010000000756820
- (_Bool)isKeyTransparencyPeerVerificationAllowedWithoutEnrollment;	// IMP=0x00100000007567f0
- (_Bool)isKeyTransparencyEnabled;	// IMP=0x0010000000756790

@end

