//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <FTServices/FTIDSMessage.h>

@class NSArray, NSDictionary;

@interface IDSProfileGetHandlesMessage : FTIDSMessage
{
    NSArray *_responseHandles;	// 232 = 0xe8
    NSDictionary *_selfHandle;	// 240 = 0xf0
}

- (void).cxx_destruct;	// IMP=0x0020000000713fd0
@property(copy) NSDictionary *selfHandle; // @synthesize selfHandle=_selfHandle;
@property(copy) NSArray *responseHandles; // @synthesize responseHandles=_responseHandles;
- (void)handleResponseDictionary:(id)arg1;	// IMP=0x0010000000713dc0
- (double)anisetteHeadersTimeout;	// IMP=0x0010000000713da0
- (id)messageBody;	// IMP=0x0010000000713d40
- (id)requiredKeys;	// IMP=0x0010000000713ce0
- (id)bagKey;	// IMP=0x0010000000713cc0
- (int)maxTimeoutRetries;	// IMP=0x0010000000713ca0
- (_Bool)wantsExtraTimeoutRetry;	// IMP=0x0010000000713c80
- (id)additionalMessageHeaders;	// IMP=0x0010000000713a80
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000007139c0
- (id)init;	// IMP=0x0010000000713920

@end

