//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GEOSQLiteDB, MISSING_TYPE, NSString;

@interface GEOAnalyticsPipelinePersistence : NSObject
{
    GEOSQLiteDB *_db;	// 8 = 0x8
    _Bool _shadowEnabled;	// 16 = 0x10
    NSString *_dbFilePath;	// 24 = 0x18
    _Bool _firstAuthComplete;	// 32 = 0x20
}

+ (id)sharedInstance;	// IMP=0x0020000000027bdd
- (void).cxx_destruct;	// IMP=0x001000000002c272
- (void)processMapsAppDeletion;	// IMP=0x001000000002c135
- (void)clearAllData;	// IMP=0x001000000002c09f
- (void)clearPendingLogMsgElemsForBatchUploadWithBatchId:(unsigned long long)arg1;	// IMP=0x001000000002bef4
- (void)clearExpiredLogMsgsWithResultBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000002b90e
- (void)selectDailySettingsWithVisitorBlock:(CDUnknownBlockType)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x001000000002b494
- (void)selectMonthlyCountsWithVisitorBlock:(CDUnknownBlockType)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x001000000002b3df
- (void)selectDailyCountsWithVisitorBlock:(CDUnknownBlockType)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x001000000002b3b9
- (void)selectCountsWithQueryStmtKey:(id)arg1 deleteStmtKey:(id)arg2 visitorBlock:(CDUnknownBlockType)arg3 completionBlock:(CDUnknownBlockType)arg4;	// IMP=0x001000000002ab32
- (void)selectCurCollViewsWithVisitorBlock:(CDUnknownBlockType)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x001000000002a61a
- (MISSING_TYPE *)selectLogMsgsForBatchUploadWithBatchId:visitorBlock:completionBlock: /* Error: Ran out of types for this method. */;	// IMP=0x001000000002a0de
- (id)selectBatchIdsForBatchUpload;	// IMP=0x0010000000029ee7
- (void)storeLogMsgElems:(id)arg1;	// IMP=0x0010000000029a15
- (void)_writeRRLogElem:(id)arg1;	// IMP=0x0010000000029880
- (void)_writeDailySettingsElem:(id)arg1;	// IMP=0x0010000000029696
- (void)_writeCuratedCollectionElem:(id)arg1;	// IMP=0x001000000002922a
- (void)_writeMonthlyCountElem:(id)arg1;	// IMP=0x001000000002915e
- (void)_writeDailyCountElem:(id)arg1;	// IMP=0x0010000000029145
- (void)_writeDailyCountElem:(id)arg1 withStmtKey:(id)arg2;	// IMP=0x0010000000028ca9
- (void)_writeLogMsgQueueElem:(id)arg1;	// IMP=0x0010000000028901
- (long long)_analyticsCount;	// IMP=0x00100000000287e1
- (void)tearDown;	// IMP=0x0010000000028774
- (void)dealloc;	// IMP=0x0010000000028736
- (void)_setupEvalStmtsOnDb:(id)arg1;	// IMP=0x00100000000285d8
- (void)_configureDatabase;	// IMP=0x0010000000027e8d
@property(readonly, nonatomic) _Bool evalModeEnabled;
- (void)protectedDataDidBecomeAvailable:(id)arg1;	// IMP=0x0010000000027e72
@property(nonatomic) _Bool firstAuthComplete;
- (id)initWithDBFilePath:(id)arg1;	// IMP=0x0010000000027cda
- (id)init;	// IMP=0x0010000000027c32
- (void)showEvalDataWithVisitorBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000002d72b
- (void)flushEvalData;	// IMP=0x001000000002d687
- (void)setEvalMode:(_Bool)arg1;	// IMP=0x001000000002d5ea

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

