//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GEOXPCActivity;
@protocol OS_dispatch_queue;

@interface GEOMobileAssetResourceUpdater : NSObject
{
    NSObject<OS_dispatch_queue> *_updateWorkQueue;	// 8 = 0x8
    GEOXPCActivity *_activity;	// 16 = 0x10
    _Bool _running;	// 24 = 0x18
}

+ (void)run;	// IMP=0x004000000001a59b
+ (void)registerXPCActivity;	// IMP=0x001000000001a36d
+ (id)sharedUpdater;	// IMP=0x001000000001a1fb
- (void).cxx_destruct;	// IMP=0x002000000001b4be
- (void)_pruneOldResourcesIn:(id)arg1;	// IMP=0x001000000001b02e
- (void)_processResources:(id)arg1 group:(id)arg2;	// IMP=0x001000000001acd8
- (void)_fetchAssets;	// IMP=0x001000000001a945
- (void)_updateComplete;	// IMP=0x001000000001a8c2
- (void)_updateOnQueue;	// IMP=0x001000000001a639
- (void)_update;	// IMP=0x001000000001a5d8
- (void)_registerActivity;	// IMP=0x001000000001a388
- (id)initInternal;	// IMP=0x001000000001a260

@end

