//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface _TtC14Xcode_Previews23ApplicationInfoProvider : NSObject
{
}

- (void).cxx_destruct;	// IMP=0x004000000001e8e0
- (id)init;	// IMP=0x001000000001e860
- (id)applicationInfoForAuditToken:(id)arg1;	// IMP=0x001000000001e7a0
- (id)applicationInfoForBundleIdentifier:(id)arg1;	// IMP=0x001000000001e740
- (id)systemServiceApplicationInfoProvider:(id)arg1;	// IMP=0x001000000001e720

@end

