//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDate, NSDictionary, NSError, NSMutableArray, NSNumber, NSString, NSURL;
@protocol OS_dispatch_source;

@interface APSConfiguration : NSObject
{
    NSString *_name;	// 8 = 0x8
    NSDictionary *_plist;	// 16 = 0x10
    NSDate *_expiry;	// 24 = 0x18
    NSDate *_fetchDate;	// 32 = 0x20
    NSError *_loadingError;	// 40 = 0x28
    _Bool _isLoaded;	// 48 = 0x30
    _Bool _hasValidSignature;	// 49 = 0x31
    _Bool _isLoadBalanced;	// 50 = 0x32
    NSURL *_url;	// 56 = 0x38
    NSMutableArray *_pendingCompletionBlocks;	// 64 = 0x40
    long long _interface;	// 72 = 0x48
    NSObject<OS_dispatch_source> *_expireTimer;	// 80 = 0x50
    NSNumber *_expensiveConditionsBackOffInterval;	// 88 = 0x58
}

+ (void)invalidateConfigurationForEnvironment:(id)arg1 interface:(long long)arg2;	// IMP=0x004000000006e5c9
+ (void)loadConfigurationForEnvironment:(id)arg1 interface:(long long)arg2 block:(CDUnknownBlockType)arg3;	// IMP=0x001000000006e280
+ (id)configurationForEnvironment:(id)arg1 interface:(long long)arg2;	// IMP=0x001000000006e075
+ (id)_onQueue_configurationForEnvironment:(id)arg1 interface:(long long)arg2;	// IMP=0x001000000006de57
+ (void)initialize;	// IMP=0x001000000006de00
- (void).cxx_destruct;	// IMP=0x00200000000700bb
@property(readonly, nonatomic) NSNumber *expensiveConditionsBackOffInterval; // @synthesize expensiveConditionsBackOffInterval=_expensiveConditionsBackOffInterval;
@property(nonatomic) _Bool hasValidSignature; // @synthesize hasValidSignature=_hasValidSignature;
@property(copy, nonatomic) NSDate *expiry; // @synthesize expiry=_expiry;
@property(copy, nonatomic) NSDate *fetchDate; // @synthesize fetchDate=_fetchDate;
- (void)setExpiryInterval:(double)arg1 expirationBlock:(CDUnknownBlockType)arg2;	// IMP=0x001000000006fe7c
- (_Bool)_isExpired;	// IMP=0x001000000006fe1c
- (_Bool)_isLoaded;	// IMP=0x001000000006fe13
@property(readonly, nonatomic) NSNumber *simulatorConnectionEnabled;
@property(readonly, nonatomic) NSNumber *minPresenceSaltRotationInterval;
@property(readonly, nonatomic) NSString *urlTokenPrefix;
@property(readonly, nonatomic) NSNumber *pubSubDefaultTimeout;
@property(readonly, nonatomic) NSNumber *pubSubRetryAttemptsCount;
@property(readonly, nonatomic) NSNumber *delayedSuspendKeepAliveInterval;
@property(readonly, nonatomic) NSNumber *suspendToggleDailyLimit;
@property(readonly, nonatomic) NSNumber *suspendToggleHourlyLimit;
- (id)bagExpiryInterval;	// IMP=0x001000000006fd0e
@property(readonly, nonatomic) NSNumber *disableDualModePiggybackTimer;
@property(readonly, nonatomic) NSNumber *lowQualityThresholdConnectedTime;
@property(readonly, nonatomic) NSNumber *highQualityThresholdConnectedTime;
@property(readonly, nonatomic) NSNumber *delayedReconnectTLSInterval;
@property(readonly, nonatomic) NSNumber *delayedReconnectTLSIntervalTrigger;
@property(readonly, nonatomic) NSNumber *delayedReconnectMinIntervalTrigger;
@property(readonly, nonatomic) NSNumber *delayedReconnectMaxIntervalTrigger;
@property(readonly, nonatomic) NSNumber *delayedReconnectMaxInterval;
@property(readonly, nonatomic) NSNumber *delayedReconnectInterval;
@property(readonly, nonatomic) NSNumber *delayedReconnectIntervalWatchWiFi;
@property(readonly, nonatomic) NSNumber *wifiKeepAliveEarlyFireConstantInterval;
- (id)ExpensiveConditionsBackOffInterval;	// IMP=0x001000000006fbb2
@property(readonly, nonatomic) NSNumber *maxExpensiveConditionsConnectionAttempts;
@property(readonly, nonatomic) NSNumber *powerOptimizationsForExpensiveNetworkingDisabled;
@property(readonly, nonatomic) NSNumber *minimumIntervalFallbackEnabled;
@property(readonly, nonatomic) NSNumber *nagleEnabled;
@property(readonly, nonatomic) NSNumber *lastIPCachingTTLMinutesV2;
@property(readonly, nonatomic) NSNumber *lastIPCachingTTLMinutes;
@property(readonly, nonatomic) NSNumber *lastIPCachingPercentage;
@property(readonly, nonatomic) NSNumber *keepAliveV2TimeDriftMaximum;
@property(readonly, nonatomic) NSNumber *disableCostDrivenDualChannelAttempts;
@property(readonly, nonatomic) NSNumber *piggybackDualChannelAttempts;
@property(readonly, nonatomic) NSNumber *costDrivenDualChannelAttempts;
@property(readonly, nonatomic) NSNumber *forcedShortTimeoutInterval;
- (id)activeInterval;	// IMP=0x001000000006fa39
@property(readonly, nonatomic) NSNumber *awdSlowReceiveThreshold;
@property(readonly, nonatomic) NSNumber *wwanTrackedLinkQualityOffTransitions;
@property(readonly, nonatomic) NSNumber *wwanTrackedLinkQualityTimeInterval;
@property(readonly, nonatomic) NSNumber *maximumLowPriorityBatchesPerHour;
@property(readonly, nonatomic) NSNumber *lowPriorityMessageBatchSize;
@property(readonly, nonatomic) NSNumber *criticalMessageTimeout;
@property(readonly, nonatomic) NSNumber *criticalMessageKeepAliveTimerDuration;
@property(readonly, nonatomic) NSNumber *numberOfCriticalMessageKeepAlivesBeforeDisconnecting;
@property(readonly, nonatomic) int status;
@property(readonly, nonatomic) unsigned long long serverCount;
@property(readonly, nonatomic) NSString *hostname;
- (void)_finishLoadWithResponse:(id)arg1 urlHost:(id)arg2 data:(id)arg3;	// IMP=0x001000000006f405
- (void)_failWithError:(id)arg1;	// IMP=0x001000000006f2e6
- (void)_callCompletionBlocksWithError:(id)arg1;	// IMP=0x001000000006f065
- (void)addCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000006ef13
- (id)pendingCompletionBocks;	// IMP=0x001000000006ef05
- (void)dealloc;	// IMP=0x001000000006eec6
- (id)initWithEnvironment:(id)arg1 interface:(long long)arg2;	// IMP=0x001000000006e88c

@end

