//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMapTable, NSMutableDictionary, NSString;
@protocol APSIDSProxyManagerDelegate, APSIDSService;

@interface APSIDSProxyManager : NSObject
{
    id <APSIDSService> _idsService;	// 8 = 0x8
    id <APSIDSProxyManagerDelegate> _delegate;	// 16 = 0x10
    NSMapTable *_environmentToListener;	// 24 = 0x18
    _Bool _nearby;	// 32 = 0x20
    NSString *_recentDaemonAliveGuid;	// 40 = 0x28
    NSMutableDictionary *_apsOutgoingMessageMap;	// 48 = 0x30
}

+ (_Bool)shouldAssertWiFi;	// IMP=0x0020000000081af8
+ (id)_idsSendQueue;	// IMP=0x001000000007cb18
- (void).cxx_destruct;	// IMP=0x0020000000082662
@property(copy, nonatomic) NSString *recentDaemonAliveGuid; // @synthesize recentDaemonAliveGuid=_recentDaemonAliveGuid;
@property(readonly, nonatomic, getter=isNearby) _Bool nearby; // @synthesize nearby=_nearby;
@property(nonatomic) __weak id <APSIDSProxyManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)service:(id)arg1 didSwitchActivePairedDevice:(id)arg2 acknowledgementBlock:(CDUnknownBlockType)arg3;	// IMP=0x00100000000824e0
- (void)service:(id)arg1 linkedDevicesChanged:(id)arg2;	// IMP=0x0010000000082430
- (void)service:(id)arg1 nearbyDevicesChanged:(id)arg2;	// IMP=0x00100000000823cb
- (void)service:(id)arg1 devicesChanged:(id)arg2;	// IMP=0x001000000008231b
- (void)_updateTimerIfNecessaryWithDevices:(id)arg1;	// IMP=0x0010000000082315
- (void)_retrieveAllDevicesAndDo:(CDUnknownBlockType)arg1;	// IMP=0x0010000000082193
- (void)_checkNearbyDevices:(id)arg1;	// IMP=0x0010000000081d06
- (void)_assertWiFiIfPossible;	// IMP=0x0010000000081c84
- (void)__assertWiFiIfPossible;	// IMP=0x0010000000081b00
- (void)service:(id)arg1 account:(id)arg2 incomingData:(id)arg3 fromID:(id)arg4 context:(id)arg5;	// IMP=0x001000000007ffce
- (void)service:(id)arg1 account:(id)arg2 identifier:(id)arg3 didSendWithSuccess:(_Bool)arg4 error:(id)arg5;	// IMP=0x001000000007fd5b
- (void)removeAllPendingAPSMessages;	// IMP=0x001000000007fcb2
- (void)sendProxyIsConnected:(_Bool)arg1 guid:(id)arg2 environmentName:(id)arg3;	// IMP=0x001000000007fba6
- (void)sendAppTokenGenerateResponse:(id)arg1 error:(id)arg2 guid:(id)arg3 environmentName:(id)arg4;	// IMP=0x001000000007fa2e
- (void)sendExpiredNonceWithServerTime:(id)arg1 guid:(id)arg2 environmentName:(id)arg3;	// IMP=0x001000000007f925
- (void)sendReversePushResponse:(long long)arg1 messageGUID:(id)arg2 messageId:(unsigned long long)arg3 guid:(id)arg4 environmentName:(id)arg5;	// IMP=0x001000000007f7c1
- (void)sendMessage:(id)arg1 guid:(id)arg2 environmentName:(id)arg3;	// IMP=0x001000000007f4df
- (void)sendTokenGenerateMessageWithTopicHash:(id)arg1 baseToken:(id)arg2 appId:(unsigned short)arg3 expirationTTL:(unsigned int)arg4 vapidPublicKeyHash:(id)arg5 type:(long long)arg6 guid:(id)arg7 environmentName:(id)arg8;	// IMP=0x001000000007f1b9
- (void)sendMessageTracingStatus:(int)arg1 topic:(id)arg2 tracingUUID:(id)arg3 token:(id)arg4 guid:(id)arg5 environmentName:(id)arg6;	// IMP=0x001000000007f04a
- (void)sendResponse:(long long)arg1 messageId:(id)arg2 token:(id)arg3 interface:(long long)arg4 generation:(unsigned long long)arg5 guid:(id)arg6 environmentName:(id)arg7;	// IMP=0x001000000007ee87
- (void)sendInactiveWithEnvironmentName:(id)arg1 guid:(id)arg2;	// IMP=0x001000000007ee03
- (void)sendPubSubChannelListRequest:(long long)arg1 environmentName:(id)arg2 guid:(id)arg3;	// IMP=0x001000000007ec94
- (void)sendPubSubUpdateMessage:(id)arg1 interface:(long long)arg2 environmentName:(id)arg3 guid:(id)arg4;	// IMP=0x001000000007eb02
- (void)sendPubSubChannelListResponse:(id)arg1 environmentName:(id)arg2 guid:(id)arg3;	// IMP=0x001000000007e9b5
- (void)sendPubSubChannelList:(id)arg1 messageID:(unsigned int)arg2 token:(id)arg3 interface:(long long)arg4 environmentName:(id)arg5 guid:(id)arg6;	// IMP=0x001000000007e7ce
- (void)sendFilterWithEnvironmentName:(id)arg1 guid:(id)arg2 enabledTopics:(id)arg3 ignoredTopics:(id)arg4 opportunisticTopics:(id)arg5 nonWakingTopics:(id)arg6 topicSalts:(id)arg7;	// IMP=0x001000000007e4c4
- (void)sendPresenceWithEnvironmentName:(id)arg1 guid:(id)arg2 token:(id)arg3 hwVersion:(id)arg4 swVersion:(id)arg5 swBuild:(id)arg6 certificate:(id)arg7 nonce:(id)arg8 signature:(id)arg9;	// IMP=0x001000000007e20b
- (void)sendReceivedPush:(id)arg1 onInterface:(long long)arg2 generation:(unsigned long long)arg3 guid:(id)arg4 environmentName:(id)arg5;	// IMP=0x001000000007e00c
- (void)sendLargeMessageSize:(unsigned long long)arg1 guid:(id)arg2 environmentName:(id)arg3;	// IMP=0x001000000007de83
- (void)sendMessageSize:(unsigned long long)arg1 guid:(id)arg2 environmentName:(id)arg3;	// IMP=0x001000000007dcfa
- (void)sendPushToken:(id)arg1 guid:(id)arg2 environmentName:(id)arg3;	// IMP=0x001000000007db8e
- (void)_sendDaemonAliveMessage;	// IMP=0x001000000007dab3
- (void)sendProxyMessage:(id)arg1 forAPSMessage:(id)arg2;	// IMP=0x001000000007d27f
- (void)sendProxyMessage:(id)arg1;	// IMP=0x001000000007d26b
- (id)_recipientDevice;	// IMP=0x001000000007d0f8
- (void)removeListener:(id)arg1 environment:(id)arg2;	// IMP=0x001000000007cfe0
- (void)setListener:(id)arg1 environment:(id)arg2;	// IMP=0x001000000007cf1d
@property(readonly, nonatomic) _Bool canUseProxy;
- (void)dealloc;	// IMP=0x001000000007ce21
- (id)init;	// IMP=0x001000000007cb6f

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

