//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@interface TASKNotifyAck : PBCodable
{
}

- (void)mergeFrom:(id)arg1;	// IMP=0x00400000000726a0
- (unsigned long long)hash;	// IMP=0x0010000000072698
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000072653
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000007261a
- (void)copyTo:(id)arg1;	// IMP=0x0010000000072614
- (void)writeTo:(id)arg1;	// IMP=0x001000000007260e
- (_Bool)readFrom:(id)arg1;	// IMP=0x0010000000072601
- (id)dictionaryRepresentation;	// IMP=0x00100000000724e2
- (id)description;	// IMP=0x0010000000072433

@end

