//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface InAppTransaction
{
}

+ (id)defaultProperties;	// IMP=0x004000000008353c
+ (Class);	// IMP=0x001000000008352b
@property(readonly, nonatomic) NSString *receipt;
@property(readonly, nonatomic) _Bool isFinished;

@end

