//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSNumber, NSString, SQLiteStatement;

@interface SQLiteQueryResults : NSObject
{
    SQLiteStatement *_statement;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00200000000722c6
- (int)clearBindings;	// IMP=0x00100000000722b0
- (void)bindURL:(id)arg1 atPosition:(int)arg2;	// IMP=0x001000000007229a
- (void)bindUUID:(id)arg1 atPosition:(int)arg2;	// IMP=0x0010000000072284
- (void)bindStringCopy:(id)arg1 atPosition:(int)arg2;	// IMP=0x001000000007226e
- (void)bindString:(id)arg1 atPosition:(int)arg2;	// IMP=0x0010000000072258
- (void)bindNumber:(id)arg1 atPosition:(int)arg2;	// IMP=0x0010000000072242
- (void)bindNullAtPosition:(int)arg1;	// IMP=0x001000000007222c
- (void)bindInt64:(long long)arg1 atPosition:(int)arg2;	// IMP=0x0010000000072216
- (void)bindInt:(int)arg1 atPosition:(int)arg2;	// IMP=0x0010000000072200
- (void)bindFloat:(float)arg1 atPosition:(int)arg2;	// IMP=0x00100000000721ea
- (void)bindDouble:(double)arg1 atPosition:(int)arg2;	// IMP=0x00100000000721d4
- (void)bindDictionary:(id)arg1 atPosition:(int)arg2;	// IMP=0x00100000000721be
- (void)bindDate:(id)arg1 atPosition:(int)arg2;	// IMP=0x00100000000721a8
- (void)bindDataCopy:(id)arg1 atPosition:(int)arg2;	// IMP=0x0010000000072192
- (void)bindData:(id)arg1 atPosition:(int)arg2;	// IMP=0x001000000007217c
- (void)bindArray:(id)arg1 atPosition:(int)arg2;	// IMP=0x0010000000072166
@property(readonly, nonatomic) _Bool hasRows;
@property(readonly, copy, nonatomic) NSNumber *firstNumberValue;
@property(readonly, nonatomic) long long firstInt64Value;
- (void)enumerateRowsUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x0010000000071ce3
- (id)initWithStatement:(id)arg1;	// IMP=0x0010000000071c78

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

