//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class AKAuthenticationUILiaison, AKClient;
@protocol AKDServerUIDelegate;

@interface AKDServerUIController : NSObject
{
    AKAuthenticationUILiaison *_authUILiaison;	// 8 = 0x8
    id <AKDServerUIDelegate> _delegate;	// 16 = 0x10
    AKClient *_client;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x002000000008fc09
- (id)_fetchPhoneInformationWithAdditionalInfo:(id)arg1 error:(id *)arg2;	// IMP=0x001000000008fb7c
- (void)_fetchIDSCertificateWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x001000000008fb01
- (void)_decorateLoadDelegate:(id)arg1 withContext:(id)arg2;	// IMP=0x001000000008f6ef
- (id)resourceLoadDelegateWithContext:(id)arg1 authResponse:(id)arg2;	// IMP=0x001000000008f3ce
- (id)resourceLoadDelegateWithContext:(id)arg1;	// IMP=0x001000000008f373
- (void)getServerUILoadDelegateWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000008f08f
- (void)getServerUILoadDelegateWithServerContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000008ed1c
- (id)_errorFromServerResponse:(id)arg1;	// IMP=0x001000000008eb89
- (void)_showServerUIWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000008e133
- (void)showServerUIWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000008ded9
- (id)_AKIDSCertificateFetchQueue;	// IMP=0x001000000008de58
- (id)initWithLiaison:(id)arg1 client:(id)arg2 delegate:(id)arg3;	// IMP=0x001000000008ddae
- (id)initWithClient:(id)arg1;	// IMP=0x001000000008dd54

@end

