//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AssistantServices/AFSiriResponse.h>

@protocol SAAceCommand;

@interface ADAcePassthroughSiriResponse : AFSiriResponse
{
    id <SAAceCommand> _replyCommand;	// 8 = 0x8
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0040000000104b89
- (void).cxx_destruct;	// IMP=0x0020000000104ca9
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000104c0e
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0010000000104b91
- (id)replyCommand;	// IMP=0x0010000000104b74
- (id)initWithRequest:(id)arg1 replyCommand:(id)arg2;	// IMP=0x0010000000104afc

@end

