//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface ADDeviceSyncCommandPushGenerationsResponse : NSObject
{
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0020000000114150
+ (id)newWithBuilder:(CDUnknownBlockType)arg1;	// IMP=0x0010000000114034
- (void)encodeWithCoder:(id)arg1;	// IMP=0x001000000011416a
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000114158
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000114145
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000114116
- (unsigned long long)hash;	// IMP=0x00100000001140e7
- (id)_descriptionWithIndent:(unsigned long long)arg1;	// IMP=0x00100000001140a9
- (id)description;	// IMP=0x0010000000114095
- (id)init;	// IMP=0x0010000000114081
- (id)initWithBuilder:(CDUnknownBlockType)arg1;	// IMP=0x0010000000113f8d
- (id)mutatedCopyWithMutator:(CDUnknownBlockType)arg1;	// IMP=0x00100000001141f6

@end

