//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSDate;

@interface ADDeviceSyncSnapshot : NSObject
{
    unsigned long long _generation;	// 8 = 0x8
    NSDate *_date;	// 16 = 0x10
    NSArray *_items;	// 24 = 0x18
}

+ (_Bool)supportsSecureCoding;	// IMP=0x002000000009782a
+ (id)newWithBuilder:(CDUnknownBlockType)arg1;	// IMP=0x001000000009742c
- (void).cxx_destruct;	// IMP=0x0010000000097a54
@property(readonly, copy, nonatomic) NSArray *items; // @synthesize items=_items;
@property(readonly, copy, nonatomic) NSDate *date; // @synthesize date=_date;
@property(readonly, nonatomic) unsigned long long generation; // @synthesize generation=_generation;
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0010000000097985
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000097832
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000009781f
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000976fa
- (unsigned long long)hash;	// IMP=0x0010000000097672
- (id)_descriptionWithIndent:(unsigned long long)arg1;	// IMP=0x00100000000975e0
- (id)description;	// IMP=0x00100000000975cc
- (id)initWithGeneration:(unsigned long long)arg1 date:(id)arg2 items:(id)arg3;	// IMP=0x001000000009748d
- (id)init;	// IMP=0x0010000000097479
- (id)initWithBuilder:(CDUnknownBlockType)arg1;	// IMP=0x00100000000972dd
- (id)mutatedCopyWithMutator:(CDUnknownBlockType)arg1;	// IMP=0x0010000000097c05

@end

