//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ADHomeInfo, ADPreferredMediaUserInfo, AFHomeAccessoryInfo, HMAccessory, HMHome, HMHomeManager, MISSING_TYPE, NSHashTable, NSMutableDictionary, NSString, NSUUID, SASetHomeContext;
@protocol OS_dispatch_queue;

@interface ADHomeInfoManager : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    HMHomeManager *_homeManager;	// 16 = 0x10
    HMAccessory *_currentAccessory;	// 24 = 0x18
    AFHomeAccessoryInfo *_currentAccessoryInfo;	// 32 = 0x20
    NSUUID *_accessoryLoggingSalt;	// 40 = 0x28
    HMHome *_currentHome;	// 48 = 0x30
    ADHomeInfo *_currentHomeInfo;	// 56 = 0x38
    NSMutableDictionary *_homeUserSettings;	// 64 = 0x40
    _Bool _assistantRequestedToTurnOffVoiceID;	// 72 = 0x48
    NSMutableDictionary *_homeSharingStates;	// 80 = 0x50
    MISSING_TYPE *_instanceContext;	// 88 = 0x58
    NSHashTable *_listeners;	// 96 = 0x60
    SASetHomeContext *_homeContext;	// 104 = 0x68
    ADPreferredMediaUserInfo *_preferredMediaUserInfo;	// 112 = 0x70
    _Bool _allowATVRmVHomeSettingSync;	// 120 = 0x78
}

+ (id)sharedInfoManager;	// IMP=0x002000000019868e
- (void).cxx_destruct;	// IMP=0x00200000001a71f9
- (void)emitHomeMetricInvocationEvent;	// IMP=0x00100000001a6ebe
- (id)_activityNotificationsForHomes:(id)arg1;	// IMP=0x00100000001a6c39
- (id)updatedHomeInfoForRootInfo:(id)arg1;	// IMP=0x00100000001a6abd
- (id)_getAccessoryCategoryForExecutionInfo:(id)arg1;	// IMP=0x00100000001a68ed
- (void)getAccessoryCategoryForExecutionInfo:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000001a673c
- (void)getLocalizedAccessoryCategoryForExecutionInfo:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000001a6609
- (_Bool)_hasSiriCapableDeviceInHome:(id)arg1;	// IMP=0x00100000001a63cc
- (void)getHomeManagerWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000001a62fb
- (id)_homesWithSiriCapableDevices;	// IMP=0x00100000001a612e
- (_Bool)areActivityNotificationsOffForAllHomes;	// IMP=0x00100000001a5f95
- (id)rootAfHomeInfoForThisDevice;	// IMP=0x00100000001a5f0f
- (void)accessoryDidUpdateSupportsThirdPartyMusic:(id)arg1;	// IMP=0x00100000001a5e39
- (void)accessory:(id)arg1 didUpdateSettings:(id)arg2;	// IMP=0x00100000001a5e33
- (void)accessoryDidUpdatePreferredMediaUser:(id)arg1;	// IMP=0x00100000001a5df4
- (void)accessoryDidUpdateName:(id)arg1;	// IMP=0x00100000001a5c1f
- (void)homeDidEnableMultiUser:(id)arg1;	// IMP=0x00100000001a5c19
- (void)home:(id)arg1 didUpdateRoom:(id)arg2 forAccessory:(id)arg3;	// IMP=0x00100000001a5a20
- (void)home:(id)arg1 didRemoveAccessory:(id)arg2;	// IMP=0x00100000001a595a
- (void)home:(id)arg1 didAddAccessory:(id)arg2;	// IMP=0x00100000001a58b1
- (void)home:(id)arg1 didRemoveUser:(id)arg2;	// IMP=0x00100000001a58ab
- (void)home:(id)arg1 didAddUser:(id)arg2;	// IMP=0x00100000001a572d
- (void)homeDidUpdateName:(id)arg1;	// IMP=0x00100000001a5514
- (void)shareManager:(id)arg1 didReceiveShareInvitation:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000001a547f
- (void)_propagateSiriDataSharingOptInStatus:(long long)arg1 toAccessory:(id)arg2;	// IMP=0x00100000001a4eb1
- (void)user:(id)arg1 didUpdateAssistantAccessControl:(id)arg2 forHome:(id)arg3;	// IMP=0x00100000001a4cd6
- (void)settingsWillUpdate:(id)arg1;	// IMP=0x00100000001a4c51
- (void)settingsDidUpdate:(id)arg1;	// IMP=0x00100000001a45da
- (void)homeManagerDidUpdateAssistantIdentifiers:(id)arg1;	// IMP=0x00100000001a44a8
- (void)homeManagerDidUpdateDataSyncState:(id)arg1;	// IMP=0x00100000001a4334
- (void)homeManagerDidUpdateCurrentHome:(id)arg1;	// IMP=0x00100000001a4202
- (void)homeManager:(id)arg1 didUpdateStatus:(unsigned long long)arg2;	// IMP=0x00100000001a3fdc
- (void)homeManager:(id)arg1 didRemoveHome:(id)arg2;	// IMP=0x00100000001a3f33
- (void)homeManager:(id)arg1 didAddHome:(id)arg2;	// IMP=0x00100000001a3be7
- (void)homeManagerDidUpdateHomes:(id)arg1;	// IMP=0x00100000001a3a66
- (void)_homeManagerUpdatedHomes:(id)arg1 homesToDelete:(id)arg2;	// IMP=0x00100000001a3944
- (void)_homeManagerUpdatedHomes:(id)arg1;	// IMP=0x00100000001a3930
- (void)_checkAndDisableVoiceIDIfRequired;	// IMP=0x00100000001a3910
- (void)_startCloudKitActivityForHomes:(id)arg1 homesToDelete:(id)arg2;	// IMP=0x00100000001a390a
- (void)fetchAccessoriesInRoom:(id)arg1 matchingCategoryTypes:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000001a334f
- (void)fetchMultiUserMetricsWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000001a2eb9
- (void)_enumerateListenersUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000001a2d8a
- (void)removeListener:(id)arg1;	// IMP=0x00100000001a2cdc
- (void)addListener:(id)arg1;	// IMP=0x00100000001a2c2e
- (void)getCurrentAccessoryInfoWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000001a2b5d
@property(readonly, nonatomic) AFHomeAccessoryInfo *currentAccessoryInfo;
@property(readonly, nonatomic) NSUUID *accessoryLoggingSalt;
- (id)_accessoryLoggingSalt;	// IMP=0x00100000001a28e5
- (void)_updateCurrentAccessoryInfoWithAccessory:(id)arg1;	// IMP=0x00100000001a25f6
- (id)_accessoryInfoForAccessory:(id)arg1;	// IMP=0x00100000001a1f2b
- (id)_currentAccessoryInfo;	// IMP=0x00100000001a1ee2
- (id)_currentAccessory;	// IMP=0x00100000001a1d39
- (id)_accessoryForIdentifier:(id)arg1 inHome:(id *)arg2;	// IMP=0x00100000001a1460
- (id)getCurrentASRLanguages;	// IMP=0x00100000001a1317
- (void)getHomeContext:(CDUnknownBlockType)arg1;	// IMP=0x00100000001a1270
- (void)setRecognizeMyVoiceEnabled:(_Bool)arg1;	// IMP=0x00100000001a0c27
- (void)restartShareDeletion;	// IMP=0x00100000001a0c21
- (void)restartSharing;	// IMP=0x00100000001a0bba
- (void)getSpeakerCapabilityForAccessoryWithUUID:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00100000001a0b44
- (void)getCurrentAccessoryWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000001a0a73
- (void)_onceSiriDataSharingAdjustment:(id)arg1;	// IMP=0x001000000019ff62
- (void)_siriDataSharingAdjustment:(id)arg1;	// IMP=0x001000000019fea7
- (void)setAllowHeySiriHomeKitSetting:(_Bool)arg1;	// IMP=0x001000000019fea1
- (void)getHomeIdForAccessoryId:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000019fd37
- (void)getVoiceSettingsForHomeMembers:(CDUnknownBlockType)arg1;	// IMP=0x001000000019fa89
- (void)settingsForMultiUserWithRefresh:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000019f939
- (void)getCurrentHomeMemberIds:(CDUnknownBlockType)arg1;	// IMP=0x001000000019f4b3
- (void)_setPreferredMediaUserForAccessory:(id)arg1;	// IMP=0x001000000019ed1d
- (void)_setPreferredMediaUserForAccessories:(id)arg1;	// IMP=0x001000000019e9a2
- (id)preferredMediaUserInfo;	// IMP=0x001000000019e8af
- (id)infoForThisDevice;	// IMP=0x001000000019e76c
- (id)_homesWithMultiUserEnabled;	// IMP=0x001000000019e3f6
- (_Bool)_updateHomeUserSettings;	// IMP=0x001000000019c5bf
- (id)_settingsForHomeUser:(id)arg1 forHome:(id)arg2;	// IMP=0x001000000019c2a3
- (_Bool)_allowExplicitContentSettingForUser:(id)arg1 forHome:(id)arg2;	// IMP=0x001000000019c24a
- (void)_resolveSiriDataSharingStatusMismatch:(id)arg1;	// IMP=0x001000000019be35
- (void)_siriDataSharingOptInStatusDidChange:(id)arg1;	// IMP=0x001000000019b8bc
- (void)_logRelevantAnalyticsOnHomeUserSettingsUpdateForCurrentSettings:(id)arg1 allowVoiceIdSettingValue:(long long)arg2 isPrimaryUser:(_Bool)arg3;	// IMP=0x001000000019b6ff
- (id)_currentHomeInfo;	// IMP=0x001000000019b0c6
- (id)_currentHome;	// IMP=0x001000000019ab5c
- (void)currentHomeWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000019aa8b
- (void)_updateHomeContext:(id)arg1;	// IMP=0x001000000019a175
- (void)dealloc;	// IMP=0x001000000019a08b
- (id)_homeManager;	// IMP=0x0010000000199f97
- (void)startAcceptingCloudSharesForMultiUserService;	// IMP=0x0010000000199f91
- (_Bool)hasOptedInHH2;	// IMP=0x0010000000199f4d
- (id)initWithHomeManager:(id)arg1 queue:(id)arg2;	// IMP=0x0010000000199e12
- (void)updateCurrentUserRMVSettingForHome:(id)arg1 enabled:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000001995e6
- (void)updateRMVSettingForUser:(id)arg1 enabled:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000198ad1
- (id)_initWithContext:(id)arg1;	// IMP=0x001000000019878e
- (id)_init;	// IMP=0x0010000000198734

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

