//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString, SABaseCommand, SARestartRequest;
@protocol SAServerBoundCommand;

@interface ADRetryManager : NSObject
{
    int _retryCount;	// 8 = 0x8
    SARestartRequest *_restartRequest;	// 16 = 0x10
    NSMutableArray *_requestObjects;	// 24 = 0x18
    _Bool _needsToRetryNakedObjects;	// 32 = 0x20
    NSMutableArray *_nakedObjects;	// 40 = 0x28
    SABaseCommand<SAServerBoundCommand> *_originalRequest;	// 48 = 0x30
    NSString *_latestMappedRequestId;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x002000000026c48b
@property(copy, nonatomic) NSString *latestMappedRequestId; // @synthesize latestMappedRequestId=_latestMappedRequestId;
- (void)clearNakedObjects;	// IMP=0x001000000026c45e
- (id)nakedObjectsToRetry;	// IMP=0x001000000026c446
- (void)setNeedsToRetryNakedObjects;	// IMP=0x001000000026c43c
- (id)retryRequestId;	// IMP=0x001000000026c3c0
- (id)originalRequestId;	// IMP=0x001000000026c3aa
- (_Bool)commandRefsRestartCommand:(id)arg1;	// IMP=0x001000000026c313
- (id)objectsToRetry;	// IMP=0x001000000026bfe1
- (void)_objectsToRemapFromRefId:(id)arg1 toRefId:(id)arg2 retryFullRequest:(_Bool)arg3 commandsToRetry:(id)arg4;	// IMP=0x001000000026bc8c
- (_Bool)_canRestartRequest;	// IMP=0x001000000026bc55
- (void)setLastReceivedCommand:(id)arg1;	// IMP=0x001000000026bb9c
- (void)endRetryableRequestForCommandAceId:(id)arg1 refId:(id)arg2;	// IMP=0x001000000026ba25
- (void)endRetryableRequestForCommand:(id)arg1;	// IMP=0x001000000026b93d
- (_Bool)shouldRetryOnConnectionFailure;	// IMP=0x001000000026b930
- (void)appendSessionObjectToRequest:(id)arg1;	// IMP=0x001000000026b8b9
- (void)beginRetryableRequest:(id)arg1;	// IMP=0x001000000026b672
- (_Bool)_commandRefsOrIsCurrentRequest:(id)arg1;	// IMP=0x001000000026b5a5
- (void)_clearRequestCommands;	// IMP=0x001000000026b565

@end

