//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC13callservicesd22RTCCSDConversationInfo : NSObject
{
    MISSING_TYPE *uuid;	// 8 = 0x8
    MISSING_TYPE *relativeStart;	// 24 = 0x18
    MISSING_TYPE *CID;	// 32 = 0x20
    MISSING_TYPE *conversationBaseTime;	// 0 = 0x0
    MISSING_TYPE *conversationProvider;	// 0 = 0x0
    MISSING_TYPE *hasLink;	// 2004049759 = 0x77735f5f
    MISSING_TYPE *isPending;	// 1701406303 = 0x6569665f
    MISSING_TYPE *relativeEnd;	// 1163157343 = 0x45545f5f
    MISSING_TYPE *duration;	// 0 = 0x0
    MISSING_TYPE *uPlusOneModeAtStart;	// 4019880 = 0x3d56a8
    MISSING_TYPE *uPlusOneModeAtEnd;	// 13536 = 0x34e0
    MISSING_TYPE *isHandoffContinuation;	// 4019880 = 0x3d56a8
    MISSING_TYPE *originatingUIType;	// 0 = 0x0
    MISSING_TYPE *maximumMemberCount;	// 0 = 0x0
    MISSING_TYPE *initialMemberCount;	// 0 = 0x0
    MISSING_TYPE *finalMemberCount;	// 2004049759 = 0x77735f5f
    MISSING_TYPE *maxNumberOfParticipants;	// 1936941407 = 0x7373615f
    MISSING_TYPE *AVCBlobRecoveryAttempts;	// 1163157343 = 0x45545f5f
    MISSING_TYPE *AVCBlobRecoveryTimeouts;	// 0 = 0x0
    MISSING_TYPE *transitionAttempts;	// 4033416 = 0x3d8b88
    MISSING_TYPE *numberLMIRequests;	// 1424 = 0x590
    MISSING_TYPE *numberLMIApprovals;	// 4033416 = 0x3d8b88
    MISSING_TYPE *numberLMIDismissals;	// 0 = 0x0
    MISSING_TYPE *messageRetryAttempts;	// 0 = 0x0
    MISSING_TYPE *messageRetryFailures;	// 0 = 0x0
    MISSING_TYPE *messageRetrySuccesses;	// 2004049759 = 0x77735f5f
    MISSING_TYPE *avcBlobRecoveryMessageRetryAttempts;	// 1869770847 = 0x6f72705f
    MISSING_TYPE *avcBlobRecoveryMessageRetryFailures;	// 1163157343 = 0x45545f5f
    MISSING_TYPE *avcBlobRecoveryMessageRetrySuccesses;	// 0 = 0x0
    MISSING_TYPE *timebase;	// 0 = 0x0
    MISSING_TYPE *hasHadActiveParticipants;	// 4034840 = 0x3d9118
    MISSING_TYPE *cumulativeTimeAlone;	// 1584 = 0x630
    MISSING_TYPE *timeAloneAtEnd;	// 4034840 = 0x3d9118
    MISSING_TYPE *lastTimeNotAlone;	// 0 = 0x0
}

- (void).cxx_destruct;	// IMP=0x00400000002e44d0
- (id)init;	// IMP=0x00100000002e3fd0

@end

