//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CSDCallController, CSDCallStateController, CSDRelayMessagingController, NSString, TUDTMFSoundPlayer;

@interface CSDRelayCallDelegate : NSObject
{
    CSDCallStateController *_callStateController;	// 8 = 0x8
    TUDTMFSoundPlayer *_dtmfSoundPlayer;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0020000000184045
@property(readonly, nonatomic) TUDTMFSoundPlayer *dtmfSoundPlayer; // @synthesize dtmfSoundPlayer=_dtmfSoundPlayer;
@property(nonatomic) __weak CSDCallStateController *callStateController; // @synthesize callStateController=_callStateController;
- (void)relayCallConferenceDidStop:(id)arg1 cleanly:(_Bool)arg2 error:(id)arg3;	// IMP=0x0010000000183ed9
- (void)relayCallConferenceFailedToStart:(id)arg1;	// IMP=0x0010000000183ddd
- (void)relayCallConferenceDidStartSuccessfullyForPulledCall:(id)arg1;	// IMP=0x0010000000183d1d
- (void)relayCallConferenceDidStartSuccessfullyForOutgoingDialedCall:(id)arg1;	// IMP=0x0010000000183d0b
- (void)relayCallConferenceDidStartSuccessfullyForIncomingAnsweredCall:(id)arg1;	// IMP=0x0010000000183cb9
- (void)relayCallDidBecomeEndpointForPull:(id)arg1;	// IMP=0x0010000000183aeb
- (void)relayCallDidSendHardPauseDigits:(id)arg1;	// IMP=0x0010000000183a79
- (void)relayCall:(id)arg1 didPlayLocalDTMFToneForKey:(unsigned char)arg2;	// IMP=0x0010000000183a2d
- (void)relayCallDidUngroup:(id)arg1;	// IMP=0x00100000001839bb
- (void)relayCall:(id)arg1 didGroupWithOtherCall:(id)arg2;	// IMP=0x0010000000183935
- (void)relayCallDidUnhold:(id)arg1;	// IMP=0x00100000001838c3
- (void)relayCallDidHold:(id)arg1;	// IMP=0x0010000000183851
- (void)relayCallDidDisconnect:(id)arg1;	// IMP=0x00100000001837df
- (void)relayCall:(id)arg1 didAnswerWithRequest:(id)arg2;	// IMP=0x0010000000183546
- (void)relayCallDidDial:(id)arg1;	// IMP=0x0010000000182eca
- (id)localProviderWithIdentifier:(id)arg1;	// IMP=0x0010000000182e03
- (void)_setAllCallsToHeldExceptCall:(id)arg1;	// IMP=0x0010000000182c5e
@property(readonly, nonatomic) CSDCallController *callController;
@property(readonly, nonatomic) CSDRelayMessagingController *relayMessagingController;
- (id)init;	// IMP=0x0010000000182b68

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

