//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSObject, NSString;
@protocol OS_dispatch_queue;

@interface CSDRelayCommonController
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000098059
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void)handleRequestActionMessage:(id)arg1;	// IMP=0x0010000000097f35
- (void)handleUpdateSystemVolumeMessageFromHost:(id)arg1;	// IMP=0x0010000000097ea8
- (void)handleSuppressRingtoneMessage:(id)arg1;	// IMP=0x0010000000097d4b
- (void)handleSetUplinkMutedMessage:(id)arg1;	// IMP=0x0010000000097ba5
- (void)handleSetTTYTypeMessage:(id)arg1;	// IMP=0x0010000000097a00
- (void)handlePlayDTMFToneForKeyMessage:(id)arg1;	// IMP=0x0010000000097869
- (void)handleRequestedAnswerMessage:(id)arg1 withBehavior:(long long)arg2;	// IMP=0x001000000009773f
- (id)callWithUniqueProxyIdentifier:(id)arg1;	// IMP=0x00100000000976bf
- (id)initWithQueue:(id)arg1;	// IMP=0x0010000000097651

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

