//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface ASCEmptyOfferMetadata
{
}

+ (_Bool)supportsSecureCoding;	// IMP=0x004000000001647c
- (_Bool)isEmpty;	// IMP=0x00400000000164d7
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000001648c
- (unsigned long long)hash;	// IMP=0x0010000000016484
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000001644d
- (id)init;	// IMP=0x001000000001641e

@end

