//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC4Siri25SRCarPlayToggleEffectView : UIView
{
    MISSING_TYPE *trackColor;	// 8 = 0x8
    MISSING_TYPE *isOn;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0040000000082480
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0010000000082420
- (double)maximumAlphaFromUserInterfaceStyle:(long long)arg1;	// IMP=0x0010000000082300
- (id)initWithCoder:(id)arg1;	// IMP=0x00100000000822c0
- (id)initWithInitialState:(_Bool)arg1;	// IMP=0x00100000000822a0
@property(nonatomic) _Bool isOn; // @synthesize isOn;

@end

