//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface SRBackgroundTaskManager : NSObject
{
    unsigned long long _taskIdentifier;	// 8 = 0x8
}

- (void)_endBackgroundTask;	// IMP=0x00200000000744c2
- (void)dealloc;	// IMP=0x00100000000743fd
- (id)init;	// IMP=0x00100000000741f8

@end

