//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, PBSystemServiceConnection;
@protocol PBSPictureInPictureDelegateServiceInterface;

@interface PBPictureInPictureService : NSObject
{
    PBSystemServiceConnection *_remoteConnection;	// 8 = 0x8
    id <PBSPictureInPictureDelegateServiceInterface> _serviceDelegate;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000016a25c
@property(readonly, nonatomic) id <PBSPictureInPictureDelegateServiceInterface> serviceDelegate; // @synthesize serviceDelegate=_serviceDelegate;
@property(readonly, nonatomic) __weak PBSystemServiceConnection *remoteConnection; // @synthesize remoteConnection=_remoteConnection;
- (void)pictureInPictureManager:(id)arg1 didSendPlaybackCommand:(unsigned long long)arg2;	// IMP=0x001000000016a221
- (void)pictureInPictureManager:(id)arg1 didRequestMute:(_Bool)arg2 skippingBundleID:(id)arg3;	// IMP=0x001000000016a082
- (void)pictureInPictureManager:(id)arg1 didUpdateState:(id)arg2;	// IMP=0x001000000016a068
- (_Bool)hasValidEntitlementWithReply:(CDUnknownBlockType)arg1;	// IMP=0x0010000000169eb4
- (_Bool)hasValidEntitlement;	// IMP=0x0010000000169e9f
- (void)expandPictureInPicture;	// IMP=0x0010000000169e49
- (void)movePictureInPicture;	// IMP=0x0010000000169e04
- (void)cancelPictureInPictureFromPlayerInterface:(long long)arg1;	// IMP=0x0010000000169d5c
- (void)mutePictureInPicture:(_Bool)arg1;	// IMP=0x0010000000169cb1
- (void)fetchCurrentPictureInPictureStateWithReply:(CDUnknownBlockType)arg1;	// IMP=0x0010000000169c3c
- (void)setServiceDelegate:(id)arg1;	// IMP=0x0010000000169c2a
- (void)invalidate;	// IMP=0x0010000000169b96
- (void)dealloc;	// IMP=0x0010000000169b21
- (id)initWithRemoteConnection:(id)arg1;	// IMP=0x0010000000169a79

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

