//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class MISSING_TYPE, PBSystemGestureManager;

@protocol PBSystemGestureManagerDebugPublisher <NSObject>
- (void)systemGestureManager:(PBSystemGestureManager *)arg1 didActivateHandleOfSystemGesture:(unsigned long long)arg2;
- (MISSING_TYPE *)systemGestureManager:didInvokeHandleOfSystemGesture:deferringFrom: /* Error: Ran out of types for this method. */;
- (void)systemGestureManager:(PBSystemGestureManager *)arg1 didInvokeHandleOfSystemGesture:(unsigned long long)arg2;
@end

