//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIViewController.h>

@class NSString, UIView;
@protocol PBSystemOverlayContentDelegate;

@interface PBWallpaperViewController : UIViewController
{
    _Bool _idleModeActive;	// 8 = 0x8
    _Bool _allowsInteraction;	// 9 = 0x9
    _Bool _acceptsEventFocus;	// 10 = 0xa
    id <PBSystemOverlayContentDelegate> _contentDelegate;	// 16 = 0x10
    UIView *_wallpaperView;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x002000000012f2f7
@property(nonatomic) _Bool acceptsEventFocus; // @synthesize acceptsEventFocus=_acceptsEventFocus;
@property(readonly, nonatomic) _Bool allowsInteraction; // @synthesize allowsInteraction=_allowsInteraction;
@property(retain, nonatomic) UIView *wallpaperView; // @synthesize wallpaperView=_wallpaperView;
@property(readonly, nonatomic, getter=isIdleModeActive) _Bool idleModeActive; // @synthesize idleModeActive=_idleModeActive;
@property(nonatomic) __weak id <PBSystemOverlayContentDelegate> contentDelegate; // @synthesize contentDelegate=_contentDelegate;
- (void)sceneManager:(id)arg1 didChangeCurrentApplicationFromSceneHandle:(id)arg2 toSceneHandle:(id)arg3;	// IMP=0x001000000012f24c
- (void)dismissContentAnimated:(_Bool)arg1 clientOptions:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x001000000012f0e4
- (void)presentContentAnimated:(_Bool)arg1 clientOptions:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x001000000012ef74
@property(readonly, nonatomic) _Bool expectsEventForwarding;
@property(readonly, nonatomic, getter=isInterruptible) _Bool interruptible;
- (id)_wallpaperForApplicationSceneHandle:(id)arg1 withVariant:(long long)arg2;	// IMP=0x001000000012eeb4
- (void)_updateWallpaperForApplicationSceneHandle:(id)arg1;	// IMP=0x001000000012edac
- (void)updateWallpaperWithTransitionContext:(id)arg1;	// IMP=0x001000000012eaef
- (void)setIdleModeActive:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x001000000012e8a9
- (void)viewDidLoad;	// IMP=0x001000000012e80e
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x001000000012e78e

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

