//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface MRDIdleTopologySimplifier : NSObject
{
    NSObject<OS_dispatch_queue> *_serialQueue;	// 8 = 0x8
    NSMutableDictionary *_playbackTimers;	// 16 = 0x10
    double _recentlyPlayingInterval;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00200000000cff9b
@property(readonly, nonatomic) double recentlyPlayingInterval; // @synthesize recentlyPlayingInterval=_recentlyPlayingInterval;
@property(retain, nonatomic) NSMutableDictionary *playbackTimers; // @synthesize playbackTimers=_playbackTimers;
- (void)_onQueue_simplifyToplogyOfPlayerPathIfNeeded:(id)arg1;	// IMP=0x00100000000cf520
- (void)_onQueue_adjustPlaybackTimerIfNeededForPlayerPath:(id)arg1;	// IMP=0x00100000000cf0b7
- (void)_handleIsPlayingDidChangeNotification:(id)arg1;	// IMP=0x00100000000cef6e
- (void)unregisterForChanges;	// IMP=0x00100000000cef14
- (void)registerForChanges;	// IMP=0x00100000000ceea3
- (_Bool)isMultiplayerHost;	// IMP=0x00100000000cee58
- (id)localDeviceUID;	// IMP=0x00100000000cee38
- (double)timeSincePlayingForPlayerPath:(id)arg1;	// IMP=0x00100000000ced5a
- (id)lastPlayingDateForPlayerPath:(id)arg1;	// IMP=0x00100000000cec77
- (unsigned int)playbackStateForPlayerPath:(id)arg1;	// IMP=0x00100000000ceba0
- (void)dealloc;	// IMP=0x00100000000ceadf
- (void)_initialize;	// IMP=0x00100000000cea3c
- (id)init;	// IMP=0x00100000000ce937

@end

