//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface MRDNowPlayingPlaybackQueueServer : NSObject
{
}

- (id)_resolveRequest:(id)arg1 withCapabilities:(unsigned long long)arg2;	// IMP=0x0040000000068673
- (unsigned int)_cachingPolicyForRequest:(id)arg1;	// IMP=0x0010000000068653
- (void)relayArtworkRequest:(id)arg1 forContentItems:(id)arg2 withMessage:(id)arg3 fromNowPlayingClient:(id)arg4 andNotifyXPCClient:(id)arg5;	// IMP=0x0010000000067a9d
- (void)relayPlaybackQueueRequest:(id)arg1 withMessage:(id)arg2 toNowPlayingClient:(id)arg3 backToXpcClient:(id)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x0010000000066fdd
- (void)sendPlaybackQueueResponse:(id)arg1 forRequest:(id)arg2 withMessage:(id)arg3 fromNowPlayingClient:(id)arg4 toXpcClient:(id)arg5;	// IMP=0x0010000000066e84
- (void)handlePlaybackQueueRequest:(id)arg1 fromClient:(id)arg2;	// IMP=0x0010000000066255

@end

