//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <VoiceOverServices/VOSCommandManager.h>

@interface VOSCommandManager (VOSCommandSupport)
- (id)eventForKeyChord:(id)arg1;	// IMP=0x0010000000015d1a
- (id)eventForKeyChord:(id)arg1 resolver:(id)arg2;	// IMP=0x0010000000015d05
- (id)eventForKeyChord:(id)arg1 resolver:(id)arg2 info:(id)arg3;	// IMP=0x0010000000015bc2
- (id)eventForTouchGesture:(id)arg1 resolver:(id)arg2;	// IMP=0x0010000000015bad
- (id)eventForTouchGesture:(id)arg1 resolver:(id)arg2 info:(id)arg3;	// IMP=0x00100000000159e1
@end

