//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class AXUIElement, MISSING_TYPE, NSArray, NSString, NSURL, VOTElementSnapshot, VOTElementUniqueIdentification;
@protocol UIElementProtocol;

@interface VOTElement : NSObject
{
    id <UIElementProtocol> _uiElement;	// 8 = 0x8
    VOTElement *_elementForGesturedTextInput;	// 16 = 0x10
    int _lastOrbSoundLevel;	// 24 = 0x18
    _Bool shouldSkipValidateElement;	// 28 = 0x1c
    _Bool _isFirstItemInDescriptionList;	// 29 = 0x1d
    _Bool _checkedRemoteParent;	// 30 = 0x1e
    _Bool _checkedImmediateRemoteParent;	// 31 = 0x1f
    unsigned int _cachedDisplayId;	// 32 = 0x20
    VOTElementUniqueIdentification *_uniqueIdentification;	// 40 = 0x28
    NSString *_supplementalBrailleDescription;	// 48 = 0x30
    long long _aspectMask;	// 56 = 0x38
    VOTElement *_cachedRemoteParent;	// 64 = 0x40
    VOTElement *_cachedImmediateRemoteParent;	// 72 = 0x48
    VOTElement *_cachedRemoteApplication;	// 80 = 0x50
}

+ (id)customPublicRotorDictionaryForRotorId:(id)arg1 startRange:(struct _NSRange)arg2 direction:(long long)arg3;	// IMP=0x0020000000021b98
+ (id)organizedActionsByCategory:(id)arg1;	// IMP=0x00100000000207c7
+ (id)defaultCustomActionCategory;	// IMP=0x00100000000207aa
+ (void)setElementAtPointIntercept:(CDUnknownBlockType)arg1;	// IMP=0x00100000000164d9
+ (CDUnknownBlockType)elementAtPointIntercept;	// IMP=0x00100000000164c0
+ (id)_elementWithAXUIElementRef:(struct __AXUIElement *)arg1;	// IMP=0x001000000001645a
+ (id)_elementWithAXUIElementRef:(struct __AXUIElement *)arg1 cache:(id)arg2 identification:(id)arg3;	// IMP=0x00100000000163a9
+ (id)elementWithUIElement:(id)arg1;	// IMP=0x0010000000016360
+ (void)resetSystemAppElement;	// IMP=0x0010000000016312
+ (id)springBoardApplication;	// IMP=0x00100000000162d9
+ (id)systemAppApplication;	// IMP=0x00100000000160fc
+ (void)setSystemAppApplication:(id)arg1;	// IMP=0x00100000000160e8
+ (id)systemWideElement;	// IMP=0x0010000000015f7d
+ (void)initialize;	// IMP=0x0010000000015f34
- (void).cxx_destruct;	// IMP=0x001000000002905a
@property(retain, nonatomic) VOTElement *cachedRemoteApplication; // @synthesize cachedRemoteApplication=_cachedRemoteApplication;
@property(nonatomic) _Bool checkedImmediateRemoteParent; // @synthesize checkedImmediateRemoteParent=_checkedImmediateRemoteParent;
@property(retain, nonatomic) VOTElement *cachedImmediateRemoteParent; // @synthesize cachedImmediateRemoteParent=_cachedImmediateRemoteParent;
@property(nonatomic) _Bool checkedRemoteParent; // @synthesize checkedRemoteParent=_checkedRemoteParent;
@property(retain, nonatomic) VOTElement *cachedRemoteParent; // @synthesize cachedRemoteParent=_cachedRemoteParent;
@property(nonatomic) unsigned int cachedDisplayId; // @synthesize cachedDisplayId=_cachedDisplayId;
@property(nonatomic) long long aspectMask; // @synthesize aspectMask=_aspectMask;
@property(nonatomic) _Bool isFirstItemInDescriptionList; // @synthesize isFirstItemInDescriptionList=_isFirstItemInDescriptionList;
@property(copy, nonatomic) NSString *supplementalBrailleDescription; // @synthesize supplementalBrailleDescription=_supplementalBrailleDescription;
@property(nonatomic) _Bool shouldSkipValidateElement; // @synthesize shouldSkipValidateElement;
- (long long)versionedPID;	// IMP=0x0010000000028f35
- (id)currentLocalization;	// IMP=0x0010000000028f1a
- (unsigned int)secureName;	// IMP=0x0010000000028ecd
- (void)showEditingHUD;	// IMP=0x0010000000028eb2
@property(readonly, nonatomic) VOTElementSnapshot *snapshot;
- (long long)differenceAspectMask:(id)arg1;	// IMP=0x0010000000028b99
- (void)resetAspectMask;	// IMP=0x0010000000028b82
- (_Bool)includesTrendlineSonification;	// IMP=0x0010000000028b7a
- (id)dataSeriesElement;	// IMP=0x0010000000028b63
- (_Bool)isDataSeriesElement;	// IMP=0x0010000000028b18
- (id)activeKeyboard;	// IMP=0x0010000000028b01
- (_Bool)isInternationalKeyboardKey;	// IMP=0x0010000000028ae6
- (_Bool)isKeyboardContinuousPathTracking;	// IMP=0x0010000000028aa9
- (_Bool)isKeyboardContinuousPathAvailable;	// IMP=0x0010000000028a8e
- (void)updateTouchForceSounds:(double)arg1;	// IMP=0x001000000002893b
- (void)postFingerLiftAtPoint:(struct CGPoint)arg1 withContextId:(unsigned int)arg2;	// IMP=0x0010000000028839
- (void)postFingerDragAtPoint:(struct CGPoint)arg1 withForce:(double)arg2 withContextId:(unsigned int)arg3;	// IMP=0x00100000000286f4
- (void)postFingerTouchAtPoint:(struct CGPoint)arg1 withForce:(double)arg2 withContextId:(unsigned int)arg3;	// IMP=0x00100000000285ae
- (void)postStylusLiftAtPoint:(struct CGPoint)arg1 withContextId:(unsigned int)arg2;	// IMP=0x00100000000284bb
- (void)postStylusDragAtPoint:(struct CGPoint)arg1 withForce:(double)arg2 altitude:(double)arg3 azimuth:(double)arg4 withContextId:(unsigned int)arg5;	// IMP=0x001000000002832b
- (void)postStylusTouchAtPoint:(struct CGPoint)arg1 withForce:(double)arg2 altitude:(double)arg3 azimuth:(double)arg4 withContextId:(unsigned int)arg5;	// IMP=0x001000000002819b
- (_Bool)performSimpleTapAtPoint:(struct CGPoint)arg1 withForce:(double)arg2 withContextId:(unsigned int)arg3 withDelay:(float)arg4 forElement:(id)arg5;	// IMP=0x0010000000027d8a
- (_Bool)performSimpleTapAtPoint:(struct CGPoint)arg1 forElement:(id)arg2;	// IMP=0x0010000000027d65
- (_Bool)supportsDirectionOrbManipulation;	// IMP=0x0010000000027d4a
- (void)notifyAnnouncementFinishedWithString:(id)arg1 didFinishSuccessfully:(_Bool)arg2;	// IMP=0x0010000000027c31
- (void)sendUserEventOccurred;	// IMP=0x0010000000027c16
- (void)sendTouchCancelledEvent;	// IMP=0x0010000000027bfb
- (void)sendBrightnessEvent:(id)arg1;	// IMP=0x0010000000027bdd
- (void)repostEvent:(id)arg1;	// IMP=0x0010000000027b02
- (id)windowContextIDs;	// IMP=0x0010000000027ae7
- (_Bool)dispatchKeyboardEvent:(id)arg1;	// IMP=0x0010000000027a8b
- (void)unsetEventCaptureMode:(int)arg1;	// IMP=0x0010000000027a2e
- (void)setEventCaptureMode:(int)arg1;	// IMP=0x00100000000279d1
- (id)customActionGroupIdentifier;	// IMP=0x00100000000279b6
- (void)setRotationCapabilityEnabled:(_Bool)arg1;	// IMP=0x0010000000027959
- (void)setAccelemoterDisabled:(_Bool)arg1;	// IMP=0x001000000002793c
- (void)setDeviceOrientation:(long long)arg1;	// IMP=0x0010000000027936
- (id)dataSeriesAxesDescription;	// IMP=0x0010000000027483
- (id)dataSeriesYAxisValueDescriptionForPosition:(double)arg1;	// IMP=0x001000000002740b
- (id)dataSeriesXAxisValueDescriptionForPosition:(double)arg1;	// IMP=0x0010000000027393
- (id)dataSeriesCategoryLabelsForAxis:(long long)arg1;	// IMP=0x0010000000027307
- (id)dataSeriesGridlinePositionsForAxis:(long long)arg1;	// IMP=0x001000000002727b
- (id)dataSeriesUnitsLabelForAxis:(long long)arg1;	// IMP=0x00100000000271af
- (double)dataSeriesMaximumValueForAxis:(long long)arg1;	// IMP=0x00100000000270cf
- (double)dataSeriesMinimumValueForAxis:(long long)arg1;	// IMP=0x0010000000026fef
- (id)dataSeriesTitleForAxis:(long long)arg1;	// IMP=0x0010000000026f0c
- (id)dataSeriesValuesForAxis:(long long)arg1;	// IMP=0x0010000000026e80
- (double)dataSeriesSonificationPlaybackDuration;	// IMP=0x0010000000026ddf
- (_Bool)includesTrendlineInSonification;	// IMP=0x0010000000026d6c
@property(readonly, nonatomic) _Bool supportsAudiographs;
- (_Bool)supportsDataSeriesSonification;	// IMP=0x0010000000026c53
- (_Bool)supportsDataSeriesSummarization;	// IMP=0x0010000000026be0
@property(readonly, nonatomic) _Bool supportsAudiographActions;
- (long long)dataSeriesType;	// IMP=0x0010000000026af9
- (id)dataSeriesName;	// IMP=0x0010000000026a7a
@property(readonly, nonatomic) NSString *chartStructureDescription;
@property(readonly, nonatomic) VOTElement *chartElement;
- (id)chartDescriptor;	// IMP=0x00100000000268ee
- (id)isolatedWindow;	// IMP=0x00100000000268d7
- (id)elementCommunityIdentifier;	// IMP=0x0010000000026882
- (_Bool)shouldSpeakMathEquationTrait;	// IMP=0x0010000000026839
- (_Bool)prefersContextlessPassthrough;	// IMP=0x0010000000026831
- (_Bool)activateDragWithDescriptorDictionary:(id)arg1;	// IMP=0x0010000000026806
- (id)staticRecognitionText;	// IMP=0x00100000000267ed
- (id)visionFeatureDescriptionOptions;	// IMP=0x00100000000266b9
- (id)staticTextString;	// IMP=0x0010000000026519
@property(readonly, nonatomic) NSString *visibleText;
- (struct CGRect)convertAccessibilityFrameToScreenCoordinates:(struct CGRect)arg1;	// IMP=0x00100000000263d0
- (int)applicationInterfaceOrientation;	// IMP=0x001000000002636d
- (_Bool)applicationHandleRemoteRightButton;	// IMP=0x0010000000026352
- (_Bool)applicationHandleRemoteLeftButton;	// IMP=0x0010000000026337
- (_Bool)applicationHandleRemoteDownButton;	// IMP=0x000000000002631c
- (_Bool)applicationHandleRemoteUpButton;	// IMP=0x0010000000026301
- (_Bool)isApplication;	// IMP=0x0010000000026242
- (CDStruct_4bcfbbae)nonPersistentUniqueId;	// IMP=0x00100000000261f5
- (_Bool)webSearchResultsActive;	// IMP=0x00100000000261b8
@property(readonly, nonatomic) VOTElementUniqueIdentification *uniqueIdentification; // @synthesize uniqueIdentification=_uniqueIdentification;
- (_Bool)shouldStartReadAllOnFocus;	// IMP=0x00100000000260c3
@property(readonly, nonatomic) NSString *toggleStatusLabel;
@property(readonly, copy) NSString *description;
- (_Bool)isElementFirstElement:(_Bool)arg1 orLastElement:(_Bool)arg2 withType:(unsigned long long)arg3;	// IMP=0x0010000000025b49
- (id)lastElementInStatusBar;	// IMP=0x0010000000025a9f
- (_Bool)finishSetupIfAppropriate;	// IMP=0x0010000000025a84
- (const struct CGPath *)convertPath:(struct CGPath *)arg1 fromContextId:(unsigned int)arg2 fromDisplayId:(unsigned int)arg3;	// IMP=0x0010000000025a16
- (struct CGRect)convertFrame:(struct CGRect)arg1 fromContextId:(unsigned int)arg2 fromDisplayId:(unsigned int)arg3;	// IMP=0x00100000000259e5
- (const struct CGPath *)convertPath:(struct CGPath *)arg1 fromContextId:(unsigned int)arg2;	// IMP=0x0010000000025986
- (struct CGPoint)convertPoint:(struct CGPoint)arg1 fromContextId:(unsigned int)arg2;	// IMP=0x0010000000025978
- (struct CGPoint)convertPoint:(struct CGPoint)arg1 toContextId:(unsigned int)arg2;	// IMP=0x001000000002596a
- (struct CGRect)convertRect:(struct CGRect)arg1 fromContextId:(unsigned int)arg2;	// IMP=0x001000000002588b
- (_Bool)avoidAnnouncingDirectTouchArea;	// IMP=0x001000000002584e
- (id)statusBarElements;	// IMP=0x0010000000025837
- (id)firstElementInStatusBar;	// IMP=0x001000000002578d
- (void)restoreUserPreferencesChangedByHandwriting;	// IMP=0x0010000000025772
- (_Bool)showControlCenter:(_Bool)arg1;	// IMP=0x0010000000025712
- (_Bool)showBulletinBoard:(_Bool)arg1;	// IMP=0x00100000000256b2
- (_Bool)isSystemWideGestureInProgress;	// IMP=0x0010000000025675
- (_Bool)isSiriTalkingOrListening;	// IMP=0x0010000000025601
- (struct CGPoint)contentOffset;	// IMP=0x00100000000255c4
- (void)setContentOffset:(struct CGPoint)arg1;	// IMP=0x00100000000255a9
- (id)currentSoftwareKeyboardLayout;	// IMP=0x0010000000025538
- (id)currentSoftwareKeyboardLanguage;	// IMP=0x00100000000254fb
- (id)currentHardwareKeyboardLayout;	// IMP=0x00100000000254be
- (_Bool)isDictationListening;	// IMP=0x0010000000025481
- (_Bool)isVoiceControlRunning;	// IMP=0x0010000000025444
- (struct CGPoint)centerPointOfScreen;	// IMP=0x0010000000025429
- (_Bool)isQuietModeEnabled;	// IMP=0x0010000000025421
- (id)focusModeActivityName;	// IMP=0x0010000000025406
- (void)launchAppWithDisplayID:(id)arg1;	// IMP=0x00100000000253e8
- (id)appSwitcherApps;	// IMP=0x00100000000253ab
- (id)launchableApps;	// IMP=0x001000000002536e
- (_Bool)isSystemBatteryLow;	// IMP=0x0010000000025331
- (_Bool)isSystemLocked;	// IMP=0x00100000000252f4
- (_Bool)isAlarmRinging;	// IMP=0x00100000000252b7
- (_Bool)isSystemSleeping;	// IMP=0x001000000002527a
- (long long)applicationOrientation;	// IMP=0x0010000000025217
- (_Bool)isKeyboardActiveOrAttached;	// IMP=0x00100000000251c9
- (_Bool)usingBrailleHardwareKeyboard;	// IMP=0x001000000002515f
- (long long)valueChangeOriginationSource;	// IMP=0x00100000000250f0
- (_Bool)usingHardwareKeyboard;	// IMP=0x0010000000025086
- (_Bool)isSoftwareKeyboardActive;	// IMP=0x0010000000025049
- (_Bool)isSoftwareKeyboardMimic;	// IMP=0x001000000002502e
- (_Bool)softwareKeyboardSupportsGestureKeyboard;	// IMP=0x0010000000025013
- (_Bool)startStopToggle;	// IMP=0x0010000000024ff8
- (id)parentTableOrCollectionView;	// IMP=0x0010000000024fe1
- (struct _NSRange)indexPathAsRange;	// IMP=0x0010000000024fc6
- (struct _NSRange)columnRange;	// IMP=0x0010000000024fab
@property(readonly, nonatomic) _Bool areMediaLegibilityEventsBeingTapped;
@property(readonly, nonatomic) _Bool isContainedByVideoElement;
@property(readonly, nonatomic) _Bool allowsActivationWithoutBeingNativeFocused;
@property(readonly, nonatomic) _Bool isContainedByPreferredNativeFocusElement;
@property(readonly, nonatomic) _Bool shouldIncludeRowRangeInDescription;
@property(readonly, nonatomic) struct _NSRange rowRange;
- (void)jumpToTableIndex:(id)arg1;	// IMP=0x0010000000024ea7
- (id)elementAtRow:(long long)arg1 andColumn:(long long)arg2;	// IMP=0x0010000000024dcc
- (id)typingCandidateElements;	// IMP=0x0010000000024db5
- (id)textReplacements;	// IMP=0x0010000000024d9a
- (_Bool)isClipViewService;	// IMP=0x0010000000024d4c
- (_Bool)isSpotlight;	// IMP=0x0010000000024cfe
- (_Bool)isIBooks;	// IMP=0x0010000000024cb3
- (_Bool)isMaps;	// IMP=0x0010000000024c68
- (_Bool)isMail;	// IMP=0x0010000000024c1a
- (_Bool)isAccessibilitySystemUIServer;	// IMP=0x0010000000024bcf
- (_Bool)isAssistiveTouch;	// IMP=0x0010000000024b84
- (_Bool)isGoogleChrome;	// IMP=0x0010000000024b39
- (_Bool)isSafari;	// IMP=0x0010000000024aee
- (_Bool)isMobilePhone;	// IMP=0x0010000000024aa3
- (_Bool)isClockFace;	// IMP=0x0010000000024a9b
- (_Bool)isSetupBuddy;	// IMP=0x0010000000024a50
- (_Bool)isSystemApp;	// IMP=0x0010000000024a05
- (_Bool)isPineBoard;	// IMP=0x00100000000249ba
- (_Bool)isChronod;	// IMP=0x001000000002496f
- (_Bool)isSpringBoard;	// IMP=0x0010000000024924
- (_Bool)hasBadge;	// IMP=0x0010000000024909
- (_Bool)isInFolder;	// IMP=0x00100000000248ee
- (_Bool)isInAlert;	// IMP=0x00100000000248d3
- (_Bool)isInStatusBar;	// IMP=0x00100000000248b7
- (_Bool)isInAppSwitcher;	// IMP=0x00100000000248af
- (_Bool)isLiveCaptionsTextView;	// IMP=0x0010000000024864
- (id)bundleIdentifier;	// IMP=0x00100000000247c6
- (id)accessibleAncestor;	// IMP=0x00100000000247af
- (id)accessibleDescendants;	// IMP=0x0010000000024798
- (id)explorerElements;	// IMP=0x0010000000024781
- (id)titleElements;	// IMP=0x0010000000024779
- (void)updateTitleElements;	// IMP=0x0010000000024773
- (_Bool)elementActsAsTitleElement:(id)arg1;	// IMP=0x001000000002470a
- (void)addTitleElementToCache:(id)arg1;	// IMP=0x001000000002466a
- (id)headerElementsForRow:(unsigned long long)arg1;	// IMP=0x00100000000245ff
- (id)headerElementsForColumn:(unsigned long long)arg1;	// IMP=0x0010000000024594
@property(readonly, nonatomic) NSArray *linkedUIElements;
@property(readonly, nonatomic) NSArray *headerElements;
- (id)summaryElement;	// IMP=0x001000000002454f
- (id)textMarkerArrayOfText:(id)arg1;	// IMP=0x0010000000024282
- (id)stringForTextMarkers:(id)arg1;	// IMP=0x0010000000024264
- (id)elementForTextMarker:(id)arg1;	// IMP=0x001000000002424a
- (struct CGRect)textMarkerFrame:(id)arg1;	// IMP=0x00100000000241ba
- (id)textLineStartMarker:(id)arg1;	// IMP=0x001000000002419c
- (void)setSelectionToTextMarker:(id)arg1;	// IMP=0x0010000000024175
- (_Bool)textOperationsAvailable;	// IMP=0x00100000000240ca
- (id)textMarkersForRange:(struct _NSRange)arg1;	// IMP=0x0010000000024064
- (_Bool)isTourGuideRunning;	// IMP=0x0010000000024027
- (_Bool)isCameraIrisOpen;	// IMP=0x0010000000023fea
- (_Bool)shouldAnnounceFontInfo;	// IMP=0x0010000000023fcf
- (struct _NSRange)rangeForTextMarker:(id)arg1;	// IMP=0x0010000000023f54
- (id)textLineEndMarker:(id)arg1;	// IMP=0x0010000000023ed7
- (id)pageTextMarkerRange;	// IMP=0x0010000000023e54
- (id)textPreviousMarker:(id)arg1;	// IMP=0x0010000000023e36
- (id)textNextMarker:(id)arg1;	// IMP=0x0010000000023e18
- (id)textMarkersForPoints:(id)arg1;	// IMP=0x0010000000023bf5
- (id)textMarkerForPoint:(struct CGPoint)arg1;	// IMP=0x0010000000023b91
- (id)url;	// IMP=0x0010000000023b28
- (id)attachmentFilenameForCID:(id)arg1;	// IMP=0x0010000000023b0a
- (id)webAreaURL;	// IMP=0x0010000000023aa1
- (id)textMarkerRange;	// IMP=0x0010000000023a86
- (struct _NSRange)textMarkerSelectionRange;	// IMP=0x0010000000023a49
- (id)textMarkerRangeForSelection;	// IMP=0x0010000000023a0c
- (id)expandedTextValue;	// IMP=0x00100000000239f1
- (struct CGRect)boundsForRange:(struct _NSRange)arg1;	// IMP=0x0010000000023965
- (_Bool)replaceTextInRange:(struct _NSRange)arg1 withString:(id)arg2;	// IMP=0x001000000002386e
- (void)replaceCharactersAtCursor:(unsigned long long)arg1 withString:(id)arg2 source:(long long)arg3;	// IMP=0x0010000000023746
- (id)_sourceNameForChangeOriginator:(long long)arg1;	// IMP=0x0010000000023727
- (long long)_changeOriginatorForSourceName:(id)arg1;	// IMP=0x0010000000023685
- (void)deleteCharacterAtCursorWithSource:(long long)arg1;	// IMP=0x0010000000023622
- (void)decreaseWebSelection:(long long)arg1;	// IMP=0x00100000000235d0
- (void)increaseWebSelection:(long long)arg1;	// IMP=0x001000000002357e
- (id)_selectionStringForSegment:(long long)arg1;	// IMP=0x001000000002355f
- (id)objectForRange:(struct _NSRange)arg1 withParameterizedAttribute:(long long)arg2;	// IMP=0x00100000000234ee
- (id)attributedValueForRange:(struct _NSRange)arg1;	// IMP=0x0010000000023488
- (id)valueForRange:(struct _NSRange)arg1;	// IMP=0x0010000000023422
- (id)nextTextNavigationElement;	// IMP=0x001000000002340b
- (id)previousTextNavigationElement;	// IMP=0x00100000000233f4
- (struct _NSRange)rangeForLineNumberAndColumn:(id)arg1;	// IMP=0x0010000000023358
- (id)lineNumberAndColumnForPoint:(struct CGPoint)arg1;	// IMP=0x00100000000232b1
- (void)setCurrentWordContextForBook:(id)arg1;	// IMP=0x0010000000023293
- (long long)lineNumberForPoint:(struct CGPoint)arg1;	// IMP=0x00100000000231b3
- (struct CGRect)frameForRange:(struct _NSRange)arg1;	// IMP=0x0010000000023127
- (_Bool)supportsFrameForRange;	// IMP=0x001000000002310c
- (struct CGRect)frameForLineNumber:(long long)arg1;	// IMP=0x0010000000023077
- (id)stringForLineNumber:(long long)arg1;	// IMP=0x0010000000022ff3
- (struct _NSRange)rangeForLineNumber:(long long)arg1;	// IMP=0x0010000000022f4d
- (_Bool)supportsRangeForLineNumber;	// IMP=0x0010000000022f32
- (id)pageContent;	// IMP=0x0010000000022f17
- (void)updatePageContent;	// IMP=0x0010000000022efc
- (_Bool)isReadingContent;	// IMP=0x0010000000022ef4
- (_Bool)includeDuringContentReading;	// IMP=0x0010000000022ed9
- (_Bool)shouldSpeakScrollStatusOnEntry;	// IMP=0x0010000000022ebe
- (struct _NSRange)lineRangeForPosition:(unsigned long long)arg1;	// IMP=0x0010000000022e18
- (struct _NSRange)characterRangeForPosition:(unsigned long long)arg1;	// IMP=0x0010000000022d72
- (long long)lineEndPosition;	// IMP=0x0010000000022d0f
- (long long)lineStartPosition;	// IMP=0x0010000000022cac
- (void)_updateFocusForFKA:(_Bool)arg1;	// IMP=0x00100000000229df
- (void)setVoiceOverFocused:(_Bool)arg1;	// IMP=0x0010000000022797
- (void)handwritingSendCarriageReturn;	// IMP=0x001000000002277c
- (_Bool)activateKeyboardReturnKey;	// IMP=0x00100000000225f4
- (_Bool)requiresLaTeXInput;	// IMP=0x00100000000225d9
- (void)updateGesturedTextInputAttributes;	// IMP=0x00100000000225be
- (_Bool)hasImage;	// IMP=0x00100000000225a3
- (id)gesturedTextInputAttributes;	// IMP=0x00100000000224b5
- (id)elementForGesturedTextInput;	// IMP=0x001000000002231d
- (void)clearElementForGesturedTextInput;	// IMP=0x0010000000022303
- (void)insertText:(id)arg1 source:(long long)arg2;	// IMP=0x00100000000221de
@property(readonly, nonatomic) _Bool includeRoleDescription;
- (_Bool);	// IMP=0x001000000002214c
- (void)_updateValueChangeOriginatorForApplication:(long long)arg1;	// IMP=0x0010000000022056
- (void)setSelectedTextRange:(struct _NSRange)arg1 refreshBraille:(_Bool)arg2;	// IMP=0x0010000000022002
- (void)setFirstResponder:(id)arg1;	// IMP=0x0010000000021fa0
- (struct _NSRange)selectedTextRange;	// IMP=0x0010000000021f63
- (id)customPublicRotorResultWithItem:(id)arg1 startElement:(id)arg2;	// IMP=0x0010000000021d0b
- (id)customPublicRotorName:(id)arg1;	// IMP=0x0010000000021a50
- (long long)customPublicRotorLinkCountForRotor:(id)arg1;	// IMP=0x0010000000021898
- (_Bool)customPublicRotorIsVisibleInTouchRotor:(id)arg1;	// IMP=0x00100000000216f8
- (id)customPublicRotorForSystemType:(id)arg1;	// IMP=0x00100000000215dc
- (id)customPublicRotorNames;	// IMP=0x001000000002126e
- (id)customPublicRotors;	// IMP=0x0010000000021108
- (_Bool)attemptToShowContextMenuWithTargetPointValue:(id)arg1;	// IMP=0x0010000000021057
- (_Bool)performCustomActionWithIdentifier:(id)arg1 data:(id)arg2;	// IMP=0x0010000000020e6e
- (_Bool)performCustomActionWithIdentifier:(id)arg1;	// IMP=0x0010000000020e5a
- (long long)overriddenInterpretationForCommand:(long long)arg1;	// IMP=0x0010000000020dd3
- (_Bool)fullscreenVideoViewIsVisible;	// IMP=0x0010000000020db8
- (_Bool)shouldSpeakExplorerElementsAfterFocus;	// IMP=0x0010000000020d9d
@property(readonly, nonatomic) _Bool shouldSetNativeFocusWhenBecomingCurrentElement;
- (_Bool)shouldPlaySoundWhenFocused;	// IMP=0x0010000000020d70
@property(readonly, nonatomic) _Bool canBecomeNativeFocused;
@property(readonly, nonatomic) _Bool hasNativeFocus;
- (_Bool)setNativeFocus;	// IMP=0x0010000000020d1f
- (id)customRotorActions;	// IMP=0x0010000000020c29
- (id)cachedCustomRotorActions;	// IMP=0x00100000000203d4
- (_Bool)shouldIncludeRegionDescription;	// IMP=0x00100000000203b9
- (_Bool)shouldIncludeRemoteParentCustomActions;	// IMP=0x001000000002039e
- (id)customContent;	// IMP=0x0010000000020142
- (_Bool)shouldAddAlternateActionForLinkElement;	// IMP=0x00100000000200a6
- (_Bool)includeURLLabelInLabel;	// IMP=0x001000000002002d
- (_Bool)retainsCustomRotorActionSetting;	// IMP=0x0010000000020012
- (_Bool)allowCustomActionHintSpeakOverride;	// IMP=0x001000000001fff7
- (id)cellWithRowIndexPath:(struct _NSRange)arg1 parentView:(id)arg2;	// IMP=0x001000000001fd9e
- (_Bool)elementOnSameLine:(id)arg1;	// IMP=0x001000000001fa9b
- (id)firstWebElement;	// IMP=0x001000000001fa84
- (id)firstElementInApplicationForReadFromTop;	// IMP=0x001000000001fa0b
- (id)firstElementInApplicationForFocus;	// IMP=0x001000000001f6aa
- (id)firstElementInApplication;	// IMP=0x001000000001f46e
- (id)firstResponderElementForFocus;	// IMP=0x001000000001f3f5
- (id)nativeFocusPreferredElement;	// IMP=0x001000000001f3de
- (id)nativeFocusElement;	// IMP=0x001000000001f3c7
- (id)firstResponderElement;	// IMP=0x001000000001f34e
- (id)firstVisibleElementInList;	// IMP=0x001000000001f337
- (_Bool)readingContentCausesPageTurn;	// IMP=0x001000000001f314
- (_Bool)showsDualPages;	// IMP=0x001000000001f2d7
- (id)scrollStatus;	// IMP=0x001000000001f29a
- (void)scrollRectToVisible:(struct CGRect)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x001000000001f178
- (void)scrollToPoint:(struct CGPoint)arg1;	// IMP=0x001000000001f11f
- (_Bool)scrollPreviousPage;	// IMP=0x001000000001f108
- (_Bool)scrollNextPage;	// IMP=0x001000000001f0f1
- (void)scrollLeftPage;	// IMP=0x001000000001f0da
- (void)scrollRightPage;	// IMP=0x001000000001f0c3
- (void)scrollDownPage;	// IMP=0x001000000001f0ac
- (void)scrollUpPage;	// IMP=0x001000000001f095
- (_Bool)_scrollForAction:(int)arg1;	// IMP=0x001000000001ef25
- (void)_iterateSelfAndRemoteParentsUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000001ee53
- (id)immediateRemoteParent;	// IMP=0x001000000001ed69
- (id)textualContext;	// IMP=0x001000000001ed4e
- (_Bool)remoteParentIsViewHost;	// IMP=0x001000000001ed46
- (id)remoteParent;	// IMP=0x001000000001ec5c
- (double)absoluteValue;	// IMP=0x001000000001ebe9
- (double)maxValue;	// IMP=0x001000000001eb8c
- (double)minValue;	// IMP=0x001000000001eb2f
- (_Bool)_attemptPerformActivateActionWithElement:(id)arg1;	// IMP=0x001000000001e82d
@property(nonatomic) long long temporaryVoiceOverStatus;
- (_Bool)performSimpleTap:(_Bool)arg1;	// IMP=0x001000000001db65
- (_Bool)activateIfSupported;	// IMP=0x001000000001da5e
- (_Bool)performSimpleTap;	// IMP=0x001000000001da4a
- (void)performDoubleTap;	// IMP=0x001000000001d9f6
- (_Bool)allowsAutoAlternativeCharacterActivation;	// IMP=0x001000000001d9db
- (_Bool)performTapAtPoint:(struct CGPoint)arg1 withForce:(double)arg2 playSound:(_Bool)arg3;	// IMP=0x001000000001d888
- (id)resolvedEditingStyles;	// IMP=0x001000000001d7f3
- (_Bool)verifyElementExists:(struct CGPoint *)arg1;	// IMP=0x001000000001d245
- (_Bool)supportsSecondaryActivate;	// IMP=0x001000000001d22a
- (_Bool)supportsActivate;	// IMP=0x001000000001d198
- (void)findSearchResult:(_Bool)arg1 withSearchText:(id)arg2;	// IMP=0x001000000001d123
- (_Bool)performEscape;	// IMP=0x001000000001d010
- (struct CGPoint)elementFrameLocation:(int)arg1;	// IMP=0x001000000001cc81
- (void)performTextOperation:(id)arg1;	// IMP=0x001000000001cc63
- (id)textOperations;	// IMP=0x001000000001cc26
- (id)textOperationsOperator;	// IMP=0x001000000001cc0f
- (void)increaseTrackingDetail;	// IMP=0x001000000001cbf4
- (void)decreaseTrackingDetail;	// IMP=0x001000000001cbd9
- (void)zoomOutAtLocation:(struct CGPoint)arg1;	// IMP=0x001000000001cb80
- (_Bool)roadContainsTrackingPoint:(struct CGPoint)arg1;	// IMP=0x001000000001cafa
- (id)mapsExplorationChangeVerbosity:(_Bool)arg1;	// IMP=0x001000000001cadb
- (id)mapsExplorationCurrentIntersectionDescription;	// IMP=0x001000000001cac0
- (struct CGPoint)mapsExplorationCurrentLocation;	// IMP=0x001000000001caa5
- (id)mapsExplorationCurrentRoadsWithAngles;	// IMP=0x001000000001ca8a
- (_Bool)mapsExplorationIsPending;	// IMP=0x001000000001ca6f
- (_Bool)mapsExplorationIsActive;	// IMP=0x001000000001ca54
- (void)mapsExplorationEnd;	// IMP=0x001000000001ca39
- (void)mapsExplorationContinueWithVertexIndex:(unsigned long long)arg1;	// IMP=0x001000000001c9e0
- (void)mapsExplorationBeginFromCurrentElement:(_Bool)arg1;	// IMP=0x001000000001c9bf
- (void)mapsExplorationRecordTouchpoint:(struct CGPoint)arg1;	// IMP=0x001000000001c966
- (id)upcomingRoadsAtPoint:(struct CGPoint)arg1 withDirection:(float)arg2;	// IMP=0x001000000001c6fe
- (float)distanceToEndOfRoad:(struct CGPoint)arg1 withDirection:(float)arg2;	// IMP=0x001000000001c5c9
- (float)distanceToOtherRoad:(struct CGPoint)arg1 withDirection:(float)arg2 otherRoad:(id)arg3;	// IMP=0x001000000001c440
- (_Bool)lastHitTestNearBorder;	// IMP=0x001000000001c403
- (id)mapDetailedInformationAtPoint:(struct CGPoint)arg1;	// IMP=0x001000000001c3c5
- (long long)mapFeatureType;	// IMP=0x001000000001c378
- (_Bool)isMapItem;	// IMP=0x001000000001c35f
- (id)photoDescription;	// IMP=0x001000000001c344
- (id)imageOverlayElements;	// IMP=0x001000000001c32d
- (void)zoomInAtLocation:(struct CGPoint)arg1;	// IMP=0x001000000001c2d4
- (void)decrementAction;	// IMP=0x001000000001c2b9
- (void)setGesturePracticeInfo:(id)arg1;	// IMP=0x001000000001c29b
- (void)incrementAction;	// IMP=0x001000000001c280
- (void)scrollToElementForDirectional:(long long)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x001000000001bf2d
- (_Bool)shouldIgnoreTextEditingTrait;	// IMP=0x001000000001be49
@property(readonly, nonatomic) unsigned long long traits;
- (_Bool)doesHaveTraitsForGesturedTextInput;	// IMP=0x001000000001bdc9
- (_Bool)onlyHasTraits:(unsigned long long)arg1;	// IMP=0x001000000001bd7d
- (_Bool)doesHaveAllTraits:(unsigned long long)arg1;	// IMP=0x001000000001bd57
- (_Bool)doesHaveTraits:(unsigned long long)arg1;	// IMP=0x001000000001bd34
- (_Bool)brailleTextEntrySupported;	// IMP=0x001000000001bce9
- (_Bool)isEditableTextArea;	// IMP=0x001000000001bca0
- (struct _NSRange)textInputElementRange;	// IMP=0x001000000001bc48
- (id)textInputElement;	// IMP=0x001000000001bc2f
- (_Bool)suppressCustomActionHint;	// IMP=0x001000000001bc14
- (id)roleDescription;	// IMP=0x001000000001bbf9
- (unsigned long long)blockquoteLevel;	// IMP=0x001000000001bbac
- (id)elementsInDirection:(long long)arg1 withCount:(unsigned long long)arg2;	// IMP=0x001000000001b86c
- (id)lastContainedElement;	// IMP=0x001000000001b7aa
- (id)_lastContainedElementIncludingRemotes:(_Bool)arg1;	// IMP=0x001000000001b590
- (_Bool)elementIsAncestor:(id)arg1;	// IMP=0x001000000001b575
- (_Bool)elementIsDescendant:(id)arg1;	// IMP=0x001000000001b4cc
- (id)groupedParent;	// IMP=0x001000000001b421
- (unsigned long long)groupedChildrenCount;	// IMP=0x001000000001b3d4
- (id)firstContainedElement;	// IMP=0x001000000001b20b
- (_Bool)supportsHeaderElementOutput;	// IMP=0x001000000001b1b9
- (_Bool)realtimeElementCompleted;	// IMP=0x001000000001b19e
- (_Bool)realtimeElementUnread;	// IMP=0x001000000001b183
- (id)realtimeElements;	// IMP=0x001000000001b16c
- (id)autoSpeakWatchElements;	// IMP=0x001000000001b155
- (id)previousElement;	// IMP=0x001000000001b06b
- (id)nextElement;	// IMP=0x001000000001af81
- (id)remoteApplication;	// IMP=0x001000000001aef4
- (id)application;	// IMP=0x001000000001aed5
- (void)updateFocusActiveActivityDisplayName;	// IMP=0x001000000001aeba
- (void)updateEquivalenceTag;	// IMP=0x001000000001ae9f
- (void)updateLanguage;	// IMP=0x001000000001ae84
- (void)updateHint;	// IMP=0x001000000001ae69
- (void)updateTraits;	// IMP=0x001000000001ae4e
- (void)updateValue;	// IMP=0x001000000001ae33
- (void)updateRoleDescription;	// IMP=0x001000000001ae18
- (void)updateExpandedStatus;	// IMP=0x001000000001adfd
- (void)updateVisiblePoint;	// IMP=0x001000000001ade2
- (void)updateCenterPoint;	// IMP=0x001000000001adc7
- (void)updateLabel;	// IMP=0x001000000001adac
- (void)updatePaths;	// IMP=0x001000000001ad91
- (void)updateFrame;	// IMP=0x001000000001ad74
- (void)updateCache;	// IMP=0x001000000001abe8
- (id)dataDetectorURL:(struct CGPoint)arg1;	// IMP=0x001000000001ab4b
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000001aabd
@property(readonly) unsigned long long hash;
- (id)instructions;	// IMP=0x001000000001a821
- (_Bool)shouldSpeakHelpInGestureArea;	// IMP=0x001000000001a7d8
- (_Bool)handlesGestureArea;	// IMP=0x001000000001a7b2
- (_Bool)isPressed;	// IMP=0x001000000001a775
- (_Bool)supportsPressedState;	// IMP=0x001000000001a75a
- (id)ancestryForTraits:(unsigned long long)arg1;	// IMP=0x001000000001a6ef
@property(readonly, nonatomic) NSString *guideElementHeaderText;
@property(readonly, nonatomic) VOTElement *nextGuideElement;
@property(readonly, nonatomic) VOTElement *previousGuideElement;
- (id)previousContainer;	// IMP=0x001000000001a529
- (id)nextContainer;	// IMP=0x001000000001a4a6
- (id)errorMessageElements;	// IMP=0x001000000001a48f
- (id)flowToElements;	// IMP=0x001000000001a478
- (void)updateFlowToElements;	// IMP=0x001000000001a45d
- (MISSING_TYPE *)linkedElement;	// IMP=0x001000000001a446
- (_Bool)shouldIncludeMediaDescriptionsRotor;	// IMP=0x001000000001a42b
- (_Bool)touchContainerShouldOutputBraille;	// IMP=0x001000000001a410
- (id)labeledTouchContainer;	// IMP=0x001000000001a370
- (id)touchContainer;	// IMP=0x001000000001a275
- (id)touchContainerParent;	// IMP=0x001000000001a17a
- (const struct __AXUIElement *)touchContainerAXElement;	// IMP=0x0010000000019f39
- (struct __AXUIElement *)touchContainerParentAXElement;	// IMP=0x0010000000019e5b
- (id)elementsForAttribute:(long long)arg1;	// IMP=0x0010000000019e47
- (id)elementsForAttribute:(long long)arg1 withParameter:(id)arg2;	// IMP=0x0010000000019c37
- (id)_elementForAttribute:(long long)arg1 shouldUpdateCache:(_Bool)arg2 shouldFetchAttributes:(_Bool)arg3;	// IMP=0x0010000000019a98
- (id)_elementForAttribute:(long long)arg1 shouldUpdateCache:(_Bool)arg2;	// IMP=0x0010000000019a80
- (id)elementForAttribute:(long long)arg1;	// IMP=0x0010000000019a69
- (_Bool)servesAsHeadingLandmark;	// IMP=0x0010000000019a4e
- (id)opaqueElementInDirection:(long long)arg1 searchType:(long long)arg2 range:(struct _NSRange *)arg3;	// IMP=0x00100000000197fe
- (_Bool)supportsTextSelection;	// IMP=0x00100000000197e3
- (float)activationDelay;	// IMP=0x001000000001978a
- (id)focusedApplications;	// IMP=0x0010000000019626
- (id)stringForParameterizedAttribute:(long long)arg1 parameter:(id)arg2;	// IMP=0x00100000000195c3
- (id)arrayForParameterizedAttribute:(long long)arg1 parameter:(id)arg2;	// IMP=0x0010000000019560
- (id)elementForParameterizedAttribute:(long long)arg1 parameter:(id)arg2;	// IMP=0x00100000000194c1
@property(readonly, nonatomic) NSURL *photoLibraryURL;
@property(readonly, nonatomic) _Bool isPHAssetLocallyAvailable;
- (id)imageAssetLocalIdentifier;	// IMP=0x0010000000019422
@property(readonly, nonatomic) VOTElement *mediaAnalysisElement;
@property(readonly, nonatomic) _Bool shouldSkipImageTraitDescription;
@property(readonly, nonatomic) struct CGRect mediaAnalysisFrame;
@property(readonly, nonatomic) unsigned int mediaAnalysisOptions;
@property(readonly, nonatomic) _Bool supportsMediaAnalysis;
- (_Bool)isAccessibleGroup;	// IMP=0x0010000000019316
- (_Bool)isAccessibleElement;	// IMP=0x00100000000192fb
- (_Bool)isHeader;	// IMP=0x00100000000192d8
- (_Bool)isTouchContainer;	// IMP=0x001000000001921f
- (id)hint;	// IMP=0x0010000000019204
@property(readonly, nonatomic) NSString *label;
@property(nonatomic) _Bool isFirstItemInTree; // @dynamic isFirstItemInTree;
@property(nonatomic) _Bool isFirstItemInFieldset; // @dynamic isFirstItemInFieldset;
@property(nonatomic) _Bool isFirstItemInLandmark; // @dynamic isFirstItemInLandmark;
@property(nonatomic) _Bool isFirstItemInTable; // @dynamic isFirstItemInTable;
@property(nonatomic) _Bool isFirstItemInList; // @dynamic isFirstItemInList;
@property(copy, nonatomic) NSString *userDefinedLabel; // @dynamic userDefinedLabel;
- (id)elementStoredUserLabel;	// IMP=0x0010000000018c44
- (_Bool)savePhotoLabeliCloud:(id)arg1;	// IMP=0x0010000000018c26
@property(copy, nonatomic) NSString *definedLabel; // @dynamic definedLabel;
- (id)urlLabel;	// IMP=0x00100000000188b6
- (id)equivalenceTag;	// IMP=0x001000000001889b
- (id)identifier;	// IMP=0x0010000000018880
- (id)originalLabel;	// IMP=0x0010000000018830
- (id)headingLevelValue;	// IMP=0x0010000000018815
- (id)linkRelationshipType;	// IMP=0x00100000000187fa
@property(readonly, nonatomic) NSString *value;
- (struct CGRect)gesturePracticeRegion;	// IMP=0x00100000000184fc
- (id)notificationSummary:(unsigned long long)arg1;	// IMP=0x001000000001844b
- (unsigned long long)notificationCount;	// IMP=0x00100000000183e8
- (void)resetBannerTimer;	// IMP=0x00100000000183cd
- (_Bool)isBannerNotification;	// IMP=0x00100000000183b2
- (_Bool)isAwayAlertItemNew;	// IMP=0x0010000000018397
- (_Bool)isAwayAlertItem;	// IMP=0x001000000001837c
- (id)currentOpaqueElement;	// IMP=0x001000000001835e
- (id)visibleOpaqueElements;	// IMP=0x0010000000018347
- (_Bool)isAccessibilityOpaqueElementProvider;	// IMP=0x001000000001832c
- (id)localOpaqueParent;	// IMP=0x0010000000018313
- (id)outermostLocalOpaqueParent;	// IMP=0x001000000001828a
- (id)opaqueParent;	// IMP=0x001000000001812a
- (id)window;	// IMP=0x0010000000018111
- (id)windowSceneIdentifier;	// IMP=0x00100000000180f6
- (id)directParent;	// IMP=0x00100000000180dd
- (_Bool)isStrongPasswordField;	// IMP=0x00100000000180c2
- (_Bool)useElementAtPositionAfterActivation;	// IMP=0x00100000000180a7
- (double)delayBeforeUpdatingOnActivation;	// IMP=0x001000000001804e
- (struct CGRect)frameForDirectInteraction;	// IMP=0x0010000000018012
- (_Bool)elementVisibilityAffectsLayout;	// IMP=0x0010000000017ff7
- (_Bool)overridesVoiceOverInstructions;	// IMP=0x0010000000017fdc
- (_Bool)keyboardKeyAllowsTouchTyping;	// IMP=0x0010000000017f79
- (_Bool)dismissAlternativeKeyboardPicker;	// IMP=0x0010000000017f5e
- (_Bool)isInTableCell;	// IMP=0x0010000000017f43
- (_Bool)isInDescriptionDefinition;	// IMP=0x0010000000017f28
- (_Bool)isInDescriptionTerm;	// IMP=0x0010000000017f0d
- (_Bool)isComboBox;	// IMP=0x0010000000017ef2
- (struct CGRect)textCursorFrame;	// IMP=0x0010000000017e9c
- (unsigned long long)ariaColumnIndex;	// IMP=0x0010000000017e4f
- (unsigned long long)ariaRowIndex;	// IMP=0x0010000000017e02
- (unsigned long long)ariaColumnCount;	// IMP=0x0010000000017db5
- (unsigned long long)ariaRowCount;	// IMP=0x0010000000017d68
- (unsigned long long)columnCount;	// IMP=0x0010000000017d1b
- (unsigned long long)rowCount;	// IMP=0x0010000000017cce
- (id)sortDirection;	// IMP=0x0010000000017cb3
- (id)currentStatus;	// IMP=0x0010000000017c98
- (id)invalidStatus;	// IMP=0x0010000000017c7d
- (id)popupValue;	// IMP=0x0010000000017c62
- (_Bool)hasPopup;	// IMP=0x0010000000017c47
- (_Bool)isRequired;	// IMP=0x0010000000017c2c
- (id)contextDescriptors;	// IMP=0x0010000000017c11
- (_Bool)expandedStatusTogglesOnActivate;	// IMP=0x0010000000017bf6
- (long long)expandedStatus;	// IMP=0x0010000000017ba9
- (_Bool)isVisible;	// IMP=0x0010000000017b8e
- (void)updateIsVisible;	// IMP=0x0010000000017b73
- (id)fbSceneIdentifier;	// IMP=0x0010000000017ac0
- (unsigned int)windowContextIdForPress;	// IMP=0x00100000000179b9
- (unsigned int)windowContextId;	// IMP=0x00100000000178c4
- (void)updateWindowContextId;	// IMP=0x00100000000178a9
- (unsigned int)displayId;	// IMP=0x0010000000017771
- (const struct CGPath *)path;	// IMP=0x0010000000017756
- (struct CGRect)visibleFrame;	// IMP=0x001000000001771a
@property(readonly, nonatomic) struct CGRect frame;
- (_Bool)isRemoteElement;	// IMP=0x00100000000176c3
- (id)supportedLanguageIfNecessary;	// IMP=0x001000000001730b
- (id)formattedDatetime;	// IMP=0x0010000000017274
- (unsigned long long)containerType;	// IMP=0x0010000000017227
- (id)containerTypes;	// IMP=0x00100000000171e0
- (_Bool)containedIn:(unsigned long long)arg1;	// IMP=0x0010000000017165
- (struct CGPoint)visiblePoint;	// IMP=0x001000000001714a
- (struct CGPoint)centerPoint;	// IMP=0x001000000001712f
- (_Bool)applicationIsRTL;	// IMP=0x0010000000017114
- (_Bool)isRTL;	// IMP=0x00100000000170f9
- (void)setNavigationDirectionMode:(long long)arg1;	// IMP=0x00100000000170a0
- (void)updateRTL;	// IMP=0x0010000000017085
- (id)language;	// IMP=0x001000000001706a
@property(readonly, nonatomic) AXUIElement *uiElement;
- (_Bool)isValidForApplication:(id)arg1;	// IMP=0x0010000000017005
- (_Bool)isAlive;	// IMP=0x0010000000016fc8
- (_Bool)isValid;	// IMP=0x0010000000016fb2
- (int)pid;	// IMP=0x0010000000016f9c
- (void)_copyInternalsToElement:(id)arg1;	// IMP=0x0010000000016dfd
- (id)copyWithCache;	// IMP=0x0010000000016ca5
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000016bb0
- (id)initWithPosition:(struct CGPoint)arg1;	// IMP=0x00100000000168fe
- (id)initWithPosition:(struct CGPoint)arg1 application:(id)arg2 contextId:(unsigned int)arg3;	// IMP=0x0010000000016848
- (id)initWithPosition:(struct CGPoint)arg1 startWithElement:(id)arg2;	// IMP=0x00100000000167a7
- (void)initializeAssociatedPids;	// IMP=0x0010000000016719
- (id)_initWithUIElement:(id)arg1 identification:(id)arg2 initializeAssociatedPids:(_Bool)arg3;	// IMP=0x0010000000016627
- (id)initWithUIElement:(id)arg1 initializeAssociatedPids:(_Bool)arg2;	// IMP=0x0010000000016610
- (id)initWithUIElement:(id)arg1;	// IMP=0x00100000000165f9
- (id)initWithAXElement:(struct __AXUIElement *)arg1;	// IMP=0x001000000001659f
- (id)initApplicationWithPosition:(struct CGPoint)arg1;	// IMP=0x00100000000164fa
- (void)applyCVMLGeneratedContentToRequest:(id)arg1 explicitUserRequest:(_Bool)arg2;	// IMP=0x00100000000d7df1
- (id)generateCVMLContentForBraille;	// IMP=0x00100000000d7ae6
- (id)applicationProvidedOCRText;	// IMP=0x00100000000d7a5b
- (id)concatenateLabelsWithLinebreaksBasedOnFrame:(id)arg1;	// IMP=0x00100000000d77c8
- (void)_applyTableRowColumnSpan:(id)arg1 language:(id)arg2;	// IMP=0x00100000000d7502
- (void)_applyTableColumnIndex:(id)arg1 options:(unsigned long long)arg2 language:(id)arg3;	// IMP=0x00100000000d7322
- (void)_applyTableRowIndex:(id)arg1 options:(unsigned long long)arg2 language:(id)arg3;	// IMP=0x00100000000d7142
- (void)_applyHeaderStatus:(id)arg1 language:(id)arg2;	// IMP=0x00100000000d6fc9
- (void)applyTableDimension:(id)arg1 language:(id)arg2;	// IMP=0x00100000000d6d52
- (id)tableDimensionStringWithRow:(unsigned long long)arg1 andColumn:(unsigned long long)arg2;	// IMP=0x00100000000d6c20
- (_Bool)hasExplicitColumnInfo;	// IMP=0x00100000000d6bab
- (_Bool)hasExplicitRowInfo;	// IMP=0x00100000000d6b36
- (_Bool)shouldAnnounceTableInfo;	// IMP=0x00100000000d6a41
- (void)regionDescriptionWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000000d67c4
- (id)regionDescriptionWithFrame:(struct CGRect)arg1;	// IMP=0x00100000000d633f
- (struct CGRect)adaptFrameForSystemElement:(struct CGRect)arg1;	// IMP=0x00100000000d6276
- (void)_applyRoleDescription:(id)arg1 language:(id)arg2 interactOption:(long long)arg3;	// IMP=0x00100000000d615e
- (id)_roleDescriptionWithInteractOption:(long long)arg1 language:(id)arg2;	// IMP=0x00100000000d5feb
- (void)_configureAsSingleLinkElementWithRequest:(id)arg1 linkTraitTitle:(id)arg2 hint:(id)arg3;	// IMP=0x00100000000d5f48
- (void)applyTextEditingInformation:(id)arg1 request:(id)arg2 options:(unsigned long long)arg3;	// IMP=0x00100000000d53bf
- (void)announceTableInfo:(id)arg1 options:(unsigned long long)arg2 language:(id)arg3;	// IMP=0x00100000000d5313
- (void)announceAdditionalTextualInformation:(id)arg1;	// IMP=0x00100000000d528f
- (void)_applyStickyCustomActions:(id)arg1 customAction:(id)arg2 language:(id)arg3;	// IMP=0x00100000000d50c3
- (void)_applyCustomContent:(id)arg1 language:(id)arg2;	// IMP=0x00100000000d4e2f
- (_Bool)_elementActionsEquivalent:(id)arg1 withElement:(id)arg2;	// IMP=0x00100000000d4cc0
- (_Bool)_ignoreCustomActionIndicator:(id)arg1 withElement:(id)arg2;	// IMP=0x00100000000d4aa7
- (void)addTextualInformationToRequest:(id)arg1 options:(unsigned long long)arg2 dataPackage:(id)arg3;	// IMP=0x00100000000d1020
- (id)_resolvedOutputLanguage:(_Bool *)arg1;	// IMP=0x00100000000d0e33
- (void)_applySelectedTrait:(id)arg1 language:(id)arg2;	// IMP=0x00100000000d0ca3
- (void)_applyExpandedStatus:(id)arg1 language:(id)arg2;	// IMP=0x00000000000d0bec
- (void)_applyLinkRelationshipType:(id)arg1 language:(id)arg2;	// IMP=0x00100000000d0b50
- (id)_languageRangesForText:(id)arg1;	// IMP=0x00100000000d0703
- (void)_applyLanguageTokens:(id)arg1 attributedString:(id)arg2;	// IMP=0x00100000000d0446
- (void)_applyBrailleTextFormattingOptions:(id)arg1 attributedString:(id)arg2 brailleLineRange:(struct _NSRange)arg3 rangeOffset:(unsigned long long)arg4;	// IMP=0x00100000000d014f
- (void)addTextualInformationToBrailleLine:(id)arg1 forPosition:(unsigned long long)arg2 rotorSelection:(id)arg3 shouldPreferRotorSelection:(_Bool)arg4 lineRange:(struct _NSRange *)arg5 descriptionRange:(struct _NSRange *)arg6 lineRangeKnown:(_Bool)arg7 isNewTouchContainer:(_Bool)arg8 previousElement:(id)arg9;	// IMP=0x00100000000ce3d8
- (id)_copyMathTextualInformationWithBrailleLineRange:(struct _NSRange *)arg1 brailleDescriptionRange:(struct _NSRange *)arg2 position:(unsigned long long)arg3 rotorSelection:(id)arg4 shouldPreferRotorSelection:(_Bool)arg5;	// IMP=0x00100000000cde1e
- (struct _NSRange)_brailleLineRangeForDescription:(id)arg1 position:(unsigned long long)arg2;	// IMP=0x00100000000cdd52
- (void)_applySortDirection:(id)arg1 language:(id)arg2;	// IMP=0x00100000000cdbea
- (void)_applyDatetimeAttribute:(id)arg1 language:(id)arg2;	// IMP=0x00100000000cdaec
- (void)_applyCurrentStatus:(id)arg1 language:(id)arg2;	// IMP=0x00100000000cd8dc
- (void)applyInvalidStatusToRequest:(id)arg1;	// IMP=0x00100000000cd85d
- (void)_applyInvalidStatus:(id)arg1 language:(id)arg2;	// IMP=0x00100000000cd518
- (void)_addErrorMessageElement:(id)arg1 toRequest:(id)arg2;	// IMP=0x00100000000cd304
- (void)_applyTraitsToRequest:(id)arg1 options:(unsigned long long)arg2 numHeaderActions:(unsigned long long)arg3 language:(id)arg4;	// IMP=0x00100000000cc966
- (void)_applyHasPopupAttribute:(id)arg1 withLanguage:(id)arg2;	// IMP=0x00100000000cc7bc
- (_Bool)applySelectedText:(id)arg1 language:(id)arg2;	// IMP=0x00100000000cc650
- (void)_applyValueToRequest:(id)arg1 options:(unsigned long long)arg2 lastSeenLineAndColumn:(id)arg3 language:(id)arg4;	// IMP=0x00100000000cbd52
- (void)applyHeaderElementsToRequest:(id)arg1;	// IMP=0x00100000000cbb97
- (void)applyRowHeadersToRequest:(id)arg1;	// IMP=0x00100000000cba2a
- (void)_addHeaderElement:(id)arg1 toRequest:(id)arg2;	// IMP=0x00100000000cb79e
- (void)_applyLabelToRequest:(id)arg1 includeBlockQuote:(_Bool)arg2 language:(id)arg3 isWebLanguageChoice:(_Bool)arg4 interactOption:(long long)arg5;	// IMP=0x00100000000cb151
- (_Bool)isWesternTextForNonWesternLanguage:(id)arg1 language:(id)arg2;	// IMP=0x00100000000cb04d
- (id)_removeBadDeveloperDecisions:(id)arg1;	// IMP=0x00100000000cad8a
- (void)_applyAttributesFromText:(id)arg1 toRequest:(id)arg2 withLanguage:(id)arg3;	// IMP=0x00100000000cad5f
- (id)arrayOfTraitsAsStringsWithTraitOrder:(id)arg1;	// IMP=0x00100000000caccf
- (id)arrayOfTraitsAsStrings;	// IMP=0x00100000000cacbb
- (id)arrayOfTraitsAsStringsWithTraitOrder:(id)arg1 language:(id)arg2;	// IMP=0x00100000000c8f48
- (id)mathSummary;	// IMP=0x001000000012256e
- (void)expandMathEquation;	// IMP=0x00100000001224dc
- (_Bool)canExpandMathEquation;	// IMP=0x00100000001223c1
- (id)mathBrailleDescription;	// IMP=0x0010000000122338
- (_Bool)canNavigateMathSegments;	// IMP=0x0010000000122315
- (id)mathSegmentsWithGranularityLevel:(unsigned long long)arg1;	// IMP=0x0010000000121fca
- (unsigned long long)_minimumSegmentDepth;	// IMP=0x0010000000121f67
- (unsigned long long)_minimumSegmentDepthForExpression:(id)arg1 withMaximumDepth:(unsigned long long)arg2;	// IMP=0x0010000000121ed2
- (id)mathEquationDescription;	// IMP=0x0010000000121e52
- (id)_mathAXStringFromAttributedString:(id)arg1;	// IMP=0x001000000012190d
- (id)_mathExpression;	// IMP=0x00100000001218a3
- (id)_rawMathEquation;	// IMP=0x001000000012187e

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, nonatomic) _Bool includeRoleOnlyForGroupNavigation;
@property(readonly) Class superclass;

@end

