//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface EscrowGetCountrySMSCodesRequest
{
}

- (id)bodyDictionary;	// IMP=0x004000000001e99f
- (id)command;	// IMP=0x001000000001e992
- (Class)responseClass;	// IMP=0x001000000001e981

@end

