//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSError;

@interface SBEscrowOperationEndEvent
{
    NSError *_error;	// 56 = 0x38
}

+ (_Bool)supportsSecureCoding;	// IMP=0x00400000000558f1
- (void).cxx_destruct;	// IMP=0x0020000000055bd5
@property(readonly, nonatomic) NSError *error; // @synthesize error=_error;
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000055aea
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0010000000055a6d
- (id)initWithStartEvent:(id)arg1 results:(id)arg2 error:(id)arg3 context:(id)arg4;	// IMP=0x00100000000558f9

@end

