//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface MCAirPlayPayloadHandler
{
}

+ (void)recomputeAirPlaySettings;	// IMP=0x0040000000071e5a
- (void)unsetAside;	// IMP=0x0040000000071e48
- (void)remove;	// IMP=0x0010000000071ddc
- (void)setAside;	// IMP=0x0010000000071dca
- (void)_removeDependency;	// IMP=0x00100000000719a3
- (void)_addDependency;	// IMP=0x001000000007157c
- (_Bool)installWithInstaller:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x0010000000071125

@end

