//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface MCNotificationSettingsPayloadHandler
{
}

- (id)notificationSettingsFilePath;	// IMP=0x004000000005862c
- (void)unsetAside;	// IMP=0x0010000000058592
- (void)setAside;	// IMP=0x001000000005851a
- (void)remove;	// IMP=0x0010000000058463
- (_Bool)installWithInstaller:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x00100000000580ad

@end

