//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface MCSetupAssistantPayloadHandler
{
}

- (void)_removeSetupAssistantSettings;	// IMP=0x0040000000011175
- (void)_saveSetupAssistantSettings;	// IMP=0x00100000000110f3
- (void)unsetAside;	// IMP=0x00100000000110e1
- (void)setAside;	// IMP=0x00100000000110cf
- (void)remove;	// IMP=0x0010000000011063
- (_Bool)installWithInstaller:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x0010000000010d4a

@end

