//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class CPLCloudKitLibraryShareZoneIdentification, MISSING_TYPE;

@interface CPLCloudKitStagingZoneIdentification
{
    CPLCloudKitLibraryShareZoneIdentification *_stagedZoneIdentification;	// 40 = 0x28
}

+ (MISSING_TYPE *)libraryInfoRecordName;	// IMP=0x0040000000119710
+ (_Bool)isSupportedShareType:(id)arg1;	// IMP=0x00100000001196de
+ (id)shareType;	// IMP=0x00100000001196c5
+ (id)shareRecordName;	// IMP=0x00100000001196ac
+ (_Bool)supportsCloudKitScope:(id)arg1 engineScope:(id)arg2;	// IMP=0x00100000001192e0
+ (long long)scopeTypeForCloudKitScope:(id)arg1 proposedScopeType:(long long)arg2 fetchedRecords:(id)arg3 currentUserID:(id)arg4;	// IMP=0x001000000011921f
+ (id)recordsToFetchToIdentifyZoneID:(id)arg1 proposedScopeType:(long long)arg2 currentUserID:(id)arg3;	// IMP=0x0010000000119146
- (void).cxx_destruct;	// IMP=0x0020000000119755
- (id)shareRecordIDToDelete;	// IMP=0x0010000000119739
- (_Bool)supportsZoneCreation;	// IMP=0x0010000000119731
- (_Bool)supportsZoneDelete;	// IMP=0x0010000000119729
- (_Bool)isSupportedShareType:(id)arg1;	// IMP=0x00100000001196f7
- (id)scopeChangeFromCKRecords:(id)arg1 currentUserID:(id)arg2 previousScopeChange:(id)arg3;	// IMP=0x00100000001192fd

@end

