//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface AppClusterMapping
{
}

+ (Class)databaseEntityClass;	// IMP=0x002000000007cc74
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x004000000007cc45
- (id)description;	// IMP=0x001000000007caf6
- (id)init;	// IMP=0x001000000007cac7

@end

