//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSMutableArray, NSNumber;

@interface AppEvent
{
    NSMutableArray *_mutableForegroundEvents;	// 8 = 0x8
    NSNumber *_temporaryAccountID;	// 16 = 0x10
}

+ (Class)databaseEntityClass;	// IMP=0x002000000005736e
- (void).cxx_destruct;	// IMP=0x002000000005737f
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000000572fc
- (id)description;	// IMP=0x001000000005708b
- (id)init;	// IMP=0x0010000000055967

@end

