//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface AppInstallsDatabaseStore
{
}

+ (_Bool)createOrMigrateStoreUsingSchema:(id)arg1;	// IMP=0x00400000001aebe7
+ (id)storeDescriptor;	// IMP=0x00100000001aeb71
- (void)readUsingSession:(CDUnknownBlockType)arg1;	// IMP=0x00400000001afb4a
- (void)modifyUsingTransaction:(CDUnknownBlockType)arg1;	// IMP=0x00100000001aebf8

@end

