//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface ArcadeMetricsHandler
{
}

- (id)_getLaunchAppEventsWithContext:(id)arg1 rawLaunchEvents:(id)arg2;	// IMP=0x004000000008672c
- (_Bool)shouldCollectMetrics;	// IMP=0x0010000000086724
- (void)recordLaunches:(id)arg1;	// IMP=0x00100000000862d6
- (_Bool)isCandidateAppProxy:(id)arg1 isMetadataLookup:(_Bool)arg2;	// IMP=0x0010000000086284
- (_Bool)isCandidateAppMetadata:(id)arg1;	// IMP=0x001000000008626e

@end

