//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class AppInstallsDatabaseStore, NSArray;

@interface ManagedAppStatusTask
{
    AppInstallsDatabaseStore *_databaseStore;	// 8 = 0x8
    NSArray *_statusItems;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0020000000059371
- (void)main;	// IMP=0x0010000000058e92
- (id)init;	// IMP=0x0010000000058e2d

@end

