//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface SoftwareUpdateListener
{
}

- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x002000000019c9c2
- (void)shouldUseModernUpdatesWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000019c864
- (void)updateAllWithOrder:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x001000000019c589
- (void)updateAllWithJobResults:(CDUnknownBlockType)arg1;	// IMP=0x001000000019c2c5
- (void)reloadManagedUpdatesWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000019c105
- (void)reloadFromServerWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000019bf48
- (void)reloadFromServerInBackgroundWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000019bc1b
- (void)removeUpdateBulletins;	// IMP=0x001000000019bb27
- (void)showApplicationBadgeForPendingUpdates;	// IMP=0x001000000019b9f9
- (void)showApplicationUpdatesBulletin;	// IMP=0x001000000019b905
- (void)refreshUpdatesWithCompletionBlock:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x001000000019b7e5
- (void)refreshUpdateCountWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000019b539
- (void)migrateUpdatesStoreWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000019b4a9
- (void)hideApplicationBadgeForPendingUpdates;	// IMP=0x001000000019b37b
- (void)getManagedUpdatesWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000019b1be
- (void)getUpdatesWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000019b002
- (void)getUpdatesMetricsWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000019af53
- (void)getUpdatesIncludingMetricsWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000019ad96
- (void)clearExpiredUpdateHistoryWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000019ac76
- (id)init;	// IMP=0x001000000019ac47

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

