//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSMutableArray;

@interface TFGetImageUploadUrlsResponse : PBCodable
{
    unsigned long long _expiresTimeMillis;	// 8 = 0x8
    NSMutableArray *_uploadUrls;	// 16 = 0x10
    struct {
        unsigned int expiresTimeMillis:1;
    } _has;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0020000000059bea
- (unsigned long long)hash;	// IMP=0x0010000000059b9a
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000059ad9
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000005990b
- (void)writeTo:(id)arg1;	// IMP=0x00100000000597a3
- (_Bool)readFrom:(id)arg1;	// IMP=0x0010000000059583
- (id)dictionaryRepresentation;	// IMP=0x00100000000594c3
- (id)description;	// IMP=0x0010000000059414

@end

