//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@interface XDCLaunchAppResponse : PBCodable
{
    int _status;	// 8 = 0x8
}

- (unsigned long long)hash;	// IMP=0x002000000016f9e0
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000016f983
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000016f932
- (void)writeTo:(id)arg1;	// IMP=0x001000000016f916
- (_Bool)readFrom:(id)arg1;	// IMP=0x001000000016f74b
- (id)dictionaryRepresentation;	// IMP=0x001000000016f6c3
- (id)description;	// IMP=0x001000000016f614

@end

