//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface VCPMADOCRAssetProcessingTask
{
}

+ (id)fetchPropertySets;	// IMP=0x002000000003f2ff
+ (unsigned long long)taskID;	// IMP=0x001000000003f2f4
+ (id)name;	// IMP=0x001000000003f2e7
- (id)batchWithAnalysisDatabase:(id)arg1 allowDownload:(_Bool)arg2 cancelBlock:(CDUnknownBlockType)arg3;	// IMP=0x004000000003f40c
- (_Bool)shouldProcessAsset:(id)arg1;	// IMP=0x001000000003f3f7
- (void)dealloc;	// IMP=0x001000000003f385

@end

