//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@interface ALCMCoarseElevationDeprecated : PBCodable
{
    unsigned int _elevationAscended;	// 8 = 0x8
}

@property(nonatomic) unsigned int elevationAscended; // @synthesize elevationAscended=_elevationAscended;
- (void)mergeFrom:(id)arg1;	// IMP=0x00100000007b0d21
- (unsigned long long)hash;	// IMP=0x00100000007b0d08
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000007b0cc5
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000007b0c74
- (void)copyTo:(id)arg1;	// IMP=0x00100000007b0c61
- (void)writeTo:(id)arg1;	// IMP=0x00100000007b0c45
- (_Bool)readFrom:(id)arg1;	// IMP=0x00100000007b0c38
- (id)dictionaryRepresentation;	// IMP=0x00100000007b0a07
- (id)description;	// IMP=0x00100000007b0990

@end

