//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSData;

@interface ALCMWorkoutEventDeprecated : PBCodable
{
    NSData *_sessionId;	// 8 = 0x8
    int _workoutEvent;	// 16 = 0x10
    int _workoutType;	// 20 = 0x14
    struct {
        unsigned int workoutType:1;
    } _has;	// 24 = 0x18
}

@property(retain, nonatomic) NSData *sessionId; // @synthesize sessionId=_sessionId;
@property(nonatomic) int workoutEvent; // @synthesize workoutEvent=_workoutEvent;
- (void)mergeFrom:(id)arg1;	// IMP=0x00100000007f9095
- (unsigned long long)hash;	// IMP=0x00100000007f9036
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000007f8f97
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000007f8ef9
- (void)copyTo:(id)arg1;	// IMP=0x00100000007f8ea4
- (void)writeTo:(id)arg1;	// IMP=0x00100000007f8e36
- (_Bool)readFrom:(id)arg1;	// IMP=0x00100000007f8e29
- (id)dictionaryRepresentation;	// IMP=0x00100000007f86da
- (id)description;	// IMP=0x00100000007f8663
@property(readonly, nonatomic) _Bool hasSessionId;
- (int)StringAsWorkoutType:(id)arg1;	// IMP=0x00100000007f8120
- (id)workoutTypeAsString:(int)arg1;	// IMP=0x00100000007f7d5b
@property(nonatomic) _Bool hasWorkoutType;
@property(nonatomic) int workoutType; // @synthesize workoutType=_workoutType;
- (int)StringAsWorkoutEvent:(id)arg1;	// IMP=0x00100000007f7c31
- (id)workoutEventAsString:(int)arg1;	// IMP=0x00100000007f7bf8
- (void)dealloc;	// IMP=0x00100000007f7bb8

@end

