//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface CLBeaconFenceAuthorizationManagerAdapter
{
}

+ (id)getSilo;	// IMP=0x00200000009c76f6
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x00100000009c76dd
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x00100000009c7680
- (int)syncgetCanBundle:(id)arg1 performFenceOperationFor:(id)arg2;	// IMP=0x00200000009c8646
- (_Bool)syncgetFences:(void *)arg1 forBundle:(id)arg2 onBehalfOf:(id)arg3;	// IMP=0x00100000009c8562
- (_Bool)syncgetFences:(void *)arg1 forBundle:(id)arg2;	// IMP=0x00100000009c84c5
- (_Bool)syncgetRemoveFence:(const void *)arg1;	// IMP=0x00100000009c80ec
- (_Bool)syncgetAddFence:(const void *)arg1;	// IMP=0x00100000009c790a
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x00100000009c78e2
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x00100000009c78b5
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x00100000009c788d
- (void *)adaptee;	// IMP=0x00100000009c785a
- (void)endService;	// IMP=0x00100000009c783f
- (void)beginService;	// IMP=0x00100000009c778f
- (id)init;	// IMP=0x00100000009c7752

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

