//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <LocationSupport/CLIntersiloService.h>

@class NSObject, NSString;
@protocol OS_dispatch_source;

@interface CLCardioChangeService : CLIntersiloService
{
    struct shared_ptr<CLCardioChangeHistoryDb> fOutputDb;	// 8 = 0x8
    struct unique_ptr<CLActivityAggregator<CLCardioChange::EstimateResult>, std::default_delete<CLActivityAggregator<CLCardioChange::EstimateResult>>> fChangeAggregator;	// 24 = 0x18
    NSObject<OS_dispatch_source> *fAggregationTimer;	// 32 = 0x20
    struct Stats fStats;	// 40 = 0x28
    struct unique_ptr<CLNatalimetryNotifier_Type::Client, std::default_delete<CLNatalimetryNotifier_Type::Client>> fNatalimetryClient;	// 88 = 0x58
    struct unique_ptr<CLCardioChangeEstimator, std::default_delete<CLCardioChangeEstimator>> fCardioChangeEstimator;	// 96 = 0x60
    struct unique_ptr<CLCardioChange::HealthKitQueryDelegate, std::default_delete<CLCardioChange::HealthKitQueryDelegate>> fHKQueryDelegate;	// 104 = 0x68
}

+ (_Bool)isSupported;	// IMP=0x00200000009d34db
+ (id)getSilo;	// IMP=0x00100000009d3442
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x00100000009d3429
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x00100000009d33cc
- (id).cxx_construct;	// IMP=0x00200000009d5ed2
- (void).cxx_destruct;	// IMP=0x00100000009d5e63
- (void)sendAnalytics;	// IMP=0x00100000009d575c
- (void)logAnalytics:(struct EstimateResult *)arg1;	// IMP=0x00100000009d5436
- (void)markXpcActivityDone:(id)arg1;	// IMP=0x00100000009d5333
- (void)resetCardioChangeEstimationActivity:(id)arg1 withDelay:(long long)arg2;	// IMP=0x00100000009d51c9
- (void)executeCardioChangeEstimation:(id)arg1;	// IMP=0x00100000009d4c20
- (void)scheduleChangeEstimation;	// IMP=0x00100000009d4509
- (void)onChangeEstimationActivity:(id)arg1;	// IMP=0x00100000009d4294
- (void)onNatalimetryNotification:(const int *)arg1 data:(const union NotificationData *)arg2;	// IMP=0x00100000009d4116
- (void)setUpAggregationOnTimer;	// IMP=0x00100000009d396d
- (void)endService;	// IMP=0x00100000009d38c4
- (void)beginService;	// IMP=0x00100000009d3524
- (id)init;	// IMP=0x00100000009d349e

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

