//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface CLMotionSyncStoreAdapter
{
}

+ (id)getSilo;	// IMP=0x002000000084d086
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x001000000084d06d
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x001000000084d010
- (void)resetStoredCalibrations;	// IMP=0x002000000084d29a
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x001000000084d272
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x001000000084d245
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x001000000084d21d
- (void *)adaptee;	// IMP=0x001000000084d1ea
- (void)endService;	// IMP=0x001000000084d1cf
- (void)beginService;	// IMP=0x001000000084d11f
- (id)init;	// IMP=0x001000000084d0e2

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

