//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface CLOnBodyNotifierAdapter
{
}

+ (id)getSilo;	// IMP=0x001000000058a726
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x001000000058a70d
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x001000000058a6b0
+ (_Bool)isSupported;	// IMP=0x001000000058a93a
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x002000000058a912
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x001000000058a8e5
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x001000000058a8bd
- (void *)adaptee;	// IMP=0x001000000058a88a
- (void)endService;	// IMP=0x001000000058a86f
- (void)beginService;	// IMP=0x001000000058a7bf
- (id)init;	// IMP=0x001000000058a782

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

