//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <LocationSupport/CLIntersiloService.h>

@class NSString;

@interface CLPressureStatsCollector : CLIntersiloService
{
    struct unique_ptr<CLMotionNotifier::Dispatcher, std::default_delete<CLMotionNotifier::Dispatcher>> fPressureDispatcher;	// 8 = 0x8
    struct unique_ptr<CLDaemonStatus_Type::Client, std::default_delete<CLDaemonStatus_Type::Client>> fStatusClient;	// 16 = 0x10
    _Bool fCharging;	// 24 = 0x18
    struct CLK2Detector fK2Detector;	// 32 = 0x20
    struct CLRobustSlopeEstimator fSlopeEstimator;	// 152 = 0x98
    _Bool fAllowLogging;	// 264 = 0x108
}

+ (_Bool)isSupported;	// IMP=0x002000000062ac22
+ (id)getSilo;	// IMP=0x001000000062abc6
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x001000000062abad
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x001000000062ab50
- (id).cxx_construct;	// IMP=0x002000000062d255
- (void).cxx_destruct;	// IMP=0x001000000062d1e5
- (void)sendCAMetric:(CDStruct_517f28af)arg1;	// IMP=0x001000000062d1df
- (void)submitAWDMetric;	// IMP=0x001000000062c601
- (void)displayCache;	// IMP=0x001000000062c3d3
- (void)cleanCache;	// IMP=0x001000000062c1aa
- (void)saveFeaturesToCache:(CDStruct_517f28af)arg1;	// IMP=0x001000000062bef5
- (void)reset;	// IMP=0x001000000062bea2
- (int)getFlightOfStairsIn24Hr;	// IMP=0x001000000062bdce
- (void)onDaemonStatus:(const int *)arg1 data:(const union NotificationData *)arg2;	// IMP=0x001000000062ba52
- (void)onPressureData:(const Sample_b71dd899 *)arg1;	// IMP=0x001000000062b02c
- (void)disableCollection;	// IMP=0x001000000062aff2
- (void)enableCollection;	// IMP=0x001000000062afb0
- (void)endService;	// IMP=0x001000000062af9e
- (void)beginService;	// IMP=0x001000000062ae2f
- (id)init;	// IMP=0x001000000062ac70

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

