//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface CLStreamingAwareLocationProviderAdapter
{
}

+ (id)getSilo;	// IMP=0x00200000006c1266
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x00100000006c124d
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x00100000006c11f0
- (void)remoteDeviceMotionUpdate:(int)arg1 atTime:(double)arg2;	// IMP=0x00200000006c1795
- (void)releaseAccuracyEnablementAssertionForClient:(byref id)arg1;	// IMP=0x00100000006c1620
- (void)takeAccuracyEnablementAssertionForClient:(byref id)arg1 withDesiredAccuracy:(double)arg2;	// IMP=0x00100000006c147a
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x00100000006c1452
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x00100000006c1425
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x00100000006c13fd
- (void *)adaptee;	// IMP=0x00100000006c13ca
- (void)endService;	// IMP=0x00100000006c13af
- (void)beginService;	// IMP=0x00100000006c12ff
- (id)init;	// IMP=0x00100000006c12c2

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

