//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface CLTurnStateAdapter
{
}

+ (id)getSilo;	// IMP=0x00200000009e7526
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x00100000009e750d
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x00100000009e74b0
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x00200000009e7712
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x00100000009e76e5
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x00100000009e76bd
- (void *)adaptee;	// IMP=0x00100000009e768a
- (void)endService;	// IMP=0x00100000009e766f
- (void)beginService;	// IMP=0x00100000009e75bf
- (id)init;	// IMP=0x00000000009e7582

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

