//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString;

@interface CMPedometerTable : NSObject
{
    NSString *_tableName;	// 8 = 0x8
    NSString *_valueInName;	// 16 = 0x10
    NSString *_valueOutName;	// 24 = 0x18
    double _defaultValue;	// 32 = 0x20
    vector_0e047154 _binBoundariesWalk;	// 40 = 0x28
    vector_0e047154 _binBoundariesRun;	// 64 = 0x40
    vector_0e047154 _binBoundaries;	// 88 = 0x58
    _Bool _testMode;	// 112 = 0x70
    void *_persistentStore;	// 120 = 0x78
    NSMutableArray *_bins;	// 128 = 0x80
}

+ (id)convertToCMStrideCalibrationData:(id)arg1;	// IMP=0x00400000005a22b1
+ (id)convertToCMPedometerBins:(id)arg1;	// IMP=0x00100000005a2163
- (id).cxx_construct;	// IMP=0x00200000005a244b
- (void).cxx_destruct;	// IMP=0x00100000005a23ff
- (void)updateBinsWithValueOut:(double)arg1 valueIn:(double)arg2 alpha:(double)arg3;	// IMP=0x00100000005a1c63
- (id)description;	// IMP=0x00100000005a1a67
- (unsigned long long)walkBinCount;	// IMP=0x00100000005a1a55
- (_Bool)testMode;	// IMP=0x00100000005a1a4c
- (void)binsDidChange;	// IMP=0x00100000005a1a46
- (void)logBins;	// IMP=0x00100000005a1a40
- (void)setBins:(id)arg1;	// IMP=0x00100000005a198d
- (CDStruct_2c43369c)binIntervalForValueIn:(double)arg1;	// IMP=0x00100000005a192c
- (_Bool)isValueInValid:(double)arg1;	// IMP=0x00100000005a1909
- (unsigned long long)binIndexForValueIn:(double)arg1;	// IMP=0x00100000005a1872
- (_Bool)isValueInRun:(double)arg1;	// IMP=0x00100000005a1860
- (_Bool)isBin:(unsigned long long)arg1 sameActivityAsBin:(unsigned long long)arg2;	// IMP=0x00100000005a17f2
- (void)updateAdjacentBin:(unsigned long long)arg1 withAlpha:(double)arg2 valueOut:(double)arg3 nativeBin:(unsigned long long)arg4;	// IMP=0x00100000005a16a9
- (void)updateNativeBin:(unsigned long long)arg1 withAlpha:(double)arg2 valueOut:(double)arg3;	// IMP=0x00100000005a159e
- (_Bool)isRunNativeValueOutAvailable;	// IMP=0x00100000005a1559
- (_Bool)isWalkNativeValueOutAvailable;	// IMP=0x00100000005a1514
- (_Bool)isNativeValueOutAvailableInBinsFromIndex:(unsigned long long)arg1 withLength:(unsigned long long)arg2;	// IMP=0x00100000005a1398
- (double)valueOutForValueIn:(double)arg1;	// IMP=0x00100000005a0f85
- (id)copyBins;	// IMP=0x00100000005a0f2d
- (void)dealloc;	// IMP=0x00100000005a0ed2
- (id)defaultBins;	// IMP=0x00100000005a0dfd
- (id)binArrayToArchivedData:(id)arg1;	// IMP=0x00100000005a0d7a
- (id)initWithTableName:(id)arg1 valueInName:(id)arg2 valueOutName:(id)arg3 defaultValue:(double)arg4 binBoundariesWalk:(vector_0e047154)arg5 binBoundariesRun:(vector_0e047154)arg6 testMode:(_Bool)arg7;	// IMP=0x00100000005a088a

@end

