//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString;
@protocol OS_dispatch_queue;

@interface CKDaemon : NSObject
{
    NSObject<OS_dispatch_queue> *_serialQueue;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_concurrentQueue;	// 16 = 0x10
    NSMutableDictionary *_cachedHandlers;	// 24 = 0x18
}

+ (id)sharedDaemon;	// IMP=0x002000000000a36e
- (void).cxx_destruct;	// IMP=0x00200000000076a2
@property(retain, nonatomic) NSMutableDictionary *cachedHandlers; // @synthesize cachedHandlers=_cachedHandlers;
- (void)disableSyncAndDeleteCloudDataWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000007611
- (void)dropLinksBetweenSubject:(id)arg1 andObject:(id)arg2 inStoreWithIdentifier:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x00100000000074fa
- (void)dropLinksWithLabel:(id)arg1 fromSubject:(id)arg2 inStoreWithIdentifier:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x00100000000073e3
- (void)dropLinkWithLabel:(id)arg1 betweenSubject:(id)arg2 andObject:(id)arg3 inStoreWithIdentifier:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;	// IMP=0x0010000000007299
- (void)decreaseWeightForLinkWithLabel:(id)arg1 betweenSubject:(id)arg2 andObject:(id)arg3 inStoreWithIdentifier:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;	// IMP=0x001000000000714f
- (void)increaseWeightForLinkWithLabel:(id)arg1 betweenSubject:(id)arg2 andObject:(id)arg3 inStoreWithIdentifier:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;	// IMP=0x0010000000007005
- (void)setWeightForLinkWithLabel:(id)arg1 betweenSubject:(id)arg2 andObject:(id)arg3 toValue:(long long)arg4 inStoreWithIdentifier:(id)arg5 completionHandler:(CDUnknownBlockType)arg6;	// IMP=0x0010000000006eae
- (void)removeAllValuesFromSynchedStoreWithIdentifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000006e9c
- (void)removeAllValuesFromStoreWithIdentifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000006de5
- (void)removeValuesMatchingCondition:(id)arg1 fromSynchedStoreWithIdentifier:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000006dd3
- (void)removeValuesMatchingCondition:(id)arg1 fromStoreWithIdentifier:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000006cec
- (void)removeValuesForKeys:(id)arg1 fromSynchedStoreWithIdentifier:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000006cda
- (void)removeValuesForKeys:(id)arg1 fromStoreWithIdentifier:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000006bf3
- (void)removeValueForKey:(id)arg1 fromSynchedStoreWithIdentifier:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000006be1
- (void)removeValueForKey:(id)arg1 fromStoreWithIdentifier:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000006afa
- (void)recordEventWithIdentifier:(id)arg1 startDate:(id)arg2 endDate:(id)arg3 metadata:(id)arg4 toStoreWithIdentifier:(id)arg5 completionHandler:(CDUnknownBlockType)arg6;	// IMP=0x00100000000067f7
- (void)saveKeysAndValues:(id)arg1 toSynchedStoreWithIdentifier:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x00100000000067e5
- (void)saveKeysAndValues:(id)arg1 toStoreWithIdentifier:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000006701
- (void)triplesComponentsMatching:(id)arg1 inStoreWithIdentifier:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x001000000000661a
- (void)keysAndValuesForKeysMatchingCondition:(id)arg1 inStoreWithIdentifier:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000006533
- (void)keysAndValuesInStoreWithIdentifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000000647c
- (void)valuesForKeysMatchingCondition:(id)arg1 inStoreWithIdentifier:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000006395
- (void)valuesForKeys:(id)arg1 inStoreWithIdentifier:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000006210
- (void)valuesInStoreWithIdentifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000006159
- (void)valueForKey:(id)arg1 inStoreWithIdentifier:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000006072
- (void)keysMatchingCondition:(id)arg1 inStoreWithIdentifier:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000005f8b
- (void)keysInStoreWithIdentifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000005ed4
- (id)init;	// IMP=0x0010000000005dc5

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

