//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TVSettingKit/TSKViewController.h>

@interface TVSettingsMediaLibraryTCCViewController : TSKViewController
{
}

- (id)_facade;	// IMP=0x0040000000011d2a
- (id)previewForItemAtIndexPath:(id)arg1;	// IMP=0x0010000000011c26
- (id)loadSettingGroups;	// IMP=0x0010000000011a7c

@end

