//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TVSettingKit/TSKViewController.h>

@class NSString, NSURL, TSKPreviewViewController, TSKSettingItem, TVSettingsUsageFacade;

@interface TVSettingsLocalStorageViewController : TSKViewController
{
    _Bool _displayQuotaExceededIfNeeded;	// 8 = 0x8
    TSKSettingItem *_lastFocusedItem;	// 16 = 0x10
    TSKPreviewViewController *_appIconPreviewViewController;	// 24 = 0x18
    TVSettingsUsageFacade *_usageFacade;	// 32 = 0x20
    NSString *_quotaMessage;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x0020000000067d4f
@property(nonatomic) _Bool displayQuotaExceededIfNeeded; // @synthesize displayQuotaExceededIfNeeded=_displayQuotaExceededIfNeeded;
@property(retain, nonatomic) NSString *quotaMessage; // @synthesize quotaMessage=_quotaMessage;
@property(retain, nonatomic) TVSettingsUsageFacade *usageFacade; // @synthesize usageFacade=_usageFacade;
@property(retain, nonatomic) TSKPreviewViewController *appIconPreviewViewController; // @synthesize appIconPreviewViewController=_appIconPreviewViewController;
@property(retain, nonatomic) TSKSettingItem *lastFocusedItem; // @synthesize lastFocusedItem=_lastFocusedItem;
- (id)_byteCountFormatter;	// IMP=0x0010000000067c82
- (void)_updateQuotaMessage;	// IMP=0x0010000000067947
- (void)_showDeleteConfirmationForItem:(id)arg1;	// IMP=0x001000000006739b
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x0010000000067351
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;	// IMP=0x001000000006711b
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;	// IMP=0x0010000000067110
- (id)previewForItemAtIndexPath:(id)arg1;	// IMP=0x0010000000066ed6
- (id)title;	// IMP=0x0010000000066ec5
- (id)loadSettingGroups;	// IMP=0x0010000000066b64
- (void)dealloc;	// IMP=0x0010000000066b0a
- (void)viewDidLoad;	// IMP=0x0010000000066a42
- (void)displayTriggeredByURL:(id)arg1;	// IMP=0x0010000000066a1d
- (id)initWithStyle:(long long)arg1;	// IMP=0x0010000000066813

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(copy, nonatomic) NSURL *lastDeepLinkURL;
@property(readonly) Class superclass;

@end

