//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDate, NSString, UINavigationController, UIWindow;

@interface TVSettingsAppDelegate : NSObject
{
    UINavigationController *_navigationController;	// 8 = 0x8
    NSDate *_backgroundedDate;	// 16 = 0x10
    UIWindow *_window;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00100000000e6897
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void)_connectToIMAgent;	// IMP=0x00100000000e6717
- (void)_handleAuthKitURLIfNeededFromResourceDictionary:(id)arg1 overViewController:(id)arg2;	// IMP=0x00100000000e6244
- (_Bool)_openURLConfiguration:(id)arg1;	// IMP=0x00100000000e54e3
- (_Bool)application:(id)arg1 openURL:(id)arg2 options:(id)arg3;	// IMP=0x00100000000e51e3
- (void)applicationWillEnterForeground:(id)arg1;	// IMP=0x00100000000e5050
- (void)applicationDidEnterBackground:(id)arg1;	// IMP=0x00100000000e4f56
- (void)applicationWillTerminate:(id)arg1;	// IMP=0x00100000000e4f3d
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;	// IMP=0x00100000000e4d9b
- (id)_findFirstViewOfClass:(Class)arg1 inViewHierarchy:(id)arg2 depth:(int)arg3;	// IMP=0x0010000000056bbc
- (void)_presentRegionsAlertController;	// IMP=0x0010000000056b31
- (void)startScrollTestForScrollViewClass:(Class)arg1 fromViewHierarchy:(id)arg2 testName:(id)arg3 axis:(unsigned long long)arg4 options:(id)arg5;	// IMP=0x001000000005668f
- (void)startLogTest:(id)arg1;	// IMP=0x001000000005657d
- (_Bool)application:(id)arg1 runTest:(id)arg2 options:(id)arg3;	// IMP=0x00100000000561ce

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

