//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TVSettingKit/TSKPreviewViewController.h>

@class NSLayoutConstraint, TVSUIConferenceRoomDisplaySmallView;

@interface TVSettingsCRDPreviewViewController : TSKPreviewViewController
{
    TVSUIConferenceRoomDisplaySmallView *_crdView;	// 8 = 0x8
    NSLayoutConstraint *_contentViewCenterXConstraint;	// 16 = 0x10
    NSLayoutConstraint *_contentViewCenterYConstraint;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00200000000f00ce
- (id)_newCRDView;	// IMP=0x00100000000effbf
- (id)_crdView;	// IMP=0x00100000000eff7a
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00100000000efdfc
- (id)contentContainerSnapshot;	// IMP=0x00100000000efd26
- (void)setContentView:(id)arg1 animated:(_Bool)arg2;	// IMP=0x00100000000efaf5
- (void)viewDidLoad;	// IMP=0x00100000000efa16
- (void)dealloc;	// IMP=0x00100000000ef948
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x00100000000ef865

@end

