//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface BKFirstBootKernelSemaphoreToken : NSObject
{
    _Bool _semaphoreExists;	// 8 = 0x8
}

+ (id)token;	// IMP=0x002000000001286d
- (void)_revertToFirstBoot;	// IMP=0x00200000000127a6
- (void)unsetToken;	// IMP=0x00100000000126a4
- (_Bool)isTokenSet;	// IMP=0x0010000000012697
@property(readonly, copy) NSString *description;
- (id)init;	// IMP=0x001000000001259d

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

