//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface BKTetherController : NSObject
{
    int _tetherState;	// 8 = 0x8
    int _lastOrientationCode;	// 12 = 0xc
    _Bool _orientationNotificationsDisabled;	// 16 = 0x10
}

+ (id)sharedInstance;	// IMP=0x004000000003e40f
@property(nonatomic, getter=isOrientationNotificationDisabled) _Bool orientationNotificationDisabled; // @synthesize orientationNotificationDisabled=_orientationNotificationsDisabled;
- (void)updatePreferencesIfNeeded;	// IMP=0x001000000003e36b
- (_Bool)_reverseTetheringActive;	// IMP=0x001000000003e363
- (_Bool)_serviceExists:(struct __CFString *)arg1;	// IMP=0x001000000003e35b
- (void)setDitheringEnabled:(int)arg1;	// IMP=0x001000000003e355
- (void)noteInterfaceOrientationChangedWithInterfaceOrientation:(int)arg1;	// IMP=0x001000000003e34f
- (void)_handleDemoModeChanged;	// IMP=0x001000000003e349
- (_Bool)usesDisplayPortTethering;	// IMP=0x001000000003e31e
- (_Bool)isTethered;	// IMP=0x001000000003e316
- (void)_setTetherState:(int)arg1;	// IMP=0x001000000003e24a
- (void)_postDisplayPortNotificationCode:(int)arg1;	// IMP=0x001000000003e161
- (void)dealloc;	// IMP=0x001000000003e120
- (id)init;	// IMP=0x001000000003e031

@end

