//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class BKDisplayAnnotationController, NSString;
@protocol OS_dispatch_queue;

@interface BKTouchAnnotationController : NSObject
{
    _Bool _shouldVisualizeTouches;	// 8 = 0x8
    _Bool _shouldVisualizeHitTestRegions;	// 9 = 0x9
    BKDisplayAnnotationController *_displayAnnotationController;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_workQueue;	// 24 = 0x18
}

+ (id)workQueue;	// IMP=0x0020000000021d02
- (void).cxx_destruct;	// IMP=0x0020000000021186
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *workQueue; // @synthesize workQueue=_workQueue;
@property(retain, nonatomic) BKDisplayAnnotationController *displayAnnotationController; // @synthesize displayAnnotationController=_displayAnnotationController;
- (void)_queue_touchWasSoftCanceled:(unsigned int)arg1;	// IMP=0x0010000000020f58
- (void)_queue_touchWasHardCanceled:(unsigned int)arg1;	// IMP=0x0010000000020e9c
- (void)_queue_setCenter:(struct CGPoint)arg1 forTouchIdentifier:(unsigned int)arg2;	// IMP=0x0010000000020d46
- (id)_keyPathForTouchIdentifier:(unsigned int)arg1;	// IMP=0x0010000000020d22
- (int)_pidForClientPort:(unsigned int)arg1;	// IMP=0x0010000000020ca9
- (id)_stringDescribingContextID:(unsigned int)arg1 clientPort:(unsigned int)arg2;	// IMP=0x0010000000020b8f
- (id)_stringDescribingPID:(int)arg1;	// IMP=0x0010000000020a7a
- (id)_stringByRemovingPrefix:(id)arg1 fromString:(id)arg2;	// IMP=0x00100000000209bf
- (void)_queue_removeAnnotationForTouch:(unsigned int)arg1 withUniqueIdentifier:(id)arg2;	// IMP=0x001000000002099d
- (void)_queue_annotateTouch:(unsigned int)arg1 withString:(id)arg2 uniqueIdentifier:(id)arg3 fromPID:(int)arg4;	// IMP=0x00100000000206e6
- (void)_queue_annotateTouch:(unsigned int)arg1 withUniqueString:(id)arg2;	// IMP=0x00100000000206cb
- (void)hitTestRegionsDidChange:(id)arg1;	// IMP=0x0010000000020640
- (void)touchDidFinishProcessingTouchCollection;	// IMP=0x001000000002063a
- (void)touchWillStartProcessingTouchCollection;	// IMP=0x0010000000020634
- (void)touchDidSoftCancel:(unsigned int)arg1;	// IMP=0x00100000000205e6
- (void)touch:(unsigned int)arg1 didAlwaysRouteToContext:(unsigned int)arg2 clientPort:(unsigned int)arg3;	// IMP=0x0010000000020591
- (void)touchDidHIDCancel:(unsigned int)arg1;	// IMP=0x0010000000020543
- (void)touch:(unsigned int)arg1 pathIndex:(long long)arg2 rangeOutAtPoint:(struct CGPoint)arg3;	// IMP=0x00100000000204f5
- (void)touch:(unsigned int)arg1 pathIndex:(long long)arg2 upAtPoint:(struct CGPoint)arg3 detached:(_Bool)arg4;	// IMP=0x00100000000204a7
- (void)touch:(unsigned int)arg1 didMoveToPoint:(struct CGPoint)arg2 eventMask:(unsigned int)arg3;	// IMP=0x001000000002044f
- (void)touchDidTransfer:(unsigned int)arg1 destination:(id)arg2;	// IMP=0x00100000000203b8
- (void)touchDidDetach:(unsigned int)arg1 destinations:(id)arg2;	// IMP=0x001000000002036a
- (void)touch:(unsigned int)arg1 didHitTestToDestination:(id)arg2 hostingChainIndex:(long long)arg3;	// IMP=0x00100000000202cc
- (void)touch:(unsigned int)arg1 pathIndex:(long long)arg2 downAtPoint:(struct CGPoint)arg3 eventMask:(unsigned int)arg4 transducerType:(unsigned int)arg5;	// IMP=0x001000000002026c
- (void)touch:(unsigned int)arg1 pathIndex:(long long)arg2 rangeInAtPoint:(struct CGPoint)arg3 eventMask:(unsigned int)arg4 transducerType:(unsigned int)arg5;	// IMP=0x0010000000020210
- (void)_queue_applyBasicAnnotationTextForTouchIdentifier:(unsigned int)arg1 pathIndex:(long long)arg2;	// IMP=0x00100000000200a4
- (void)annotateTouch:(unsigned int)arg1 withString:(id)arg2 uniqueIdentifier:(id)arg3 fromPID:(int)arg4;	// IMP=0x001000000001ffd6
- (void)annotateTouch:(unsigned int)arg1 withString:(id)arg2 uniqueIdentifier:(id)arg3;	// IMP=0x001000000001ff13
- (void)annotateTouch:(unsigned int)arg1 withUniqueString:(id)arg2;	// IMP=0x000000000001fe7c
@property _Bool shouldVisualizeHitTestRegions;
@property _Bool shouldVisualizeTouches;
- (id)initWithDisplayUUID:(id)arg1;	// IMP=0x001000000001fbed

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

