//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSUUID;

@interface PBAttentionMonitorStateMachine : NSObject
{
    long long _state;	// 8 = 0x8
    _Bool _automaticEnabled;	// 16 = 0x10
    _Bool _enteredOnStateAutomatically;	// 17 = 0x11
    NSUUID *_automaticOnStateChangeConfirmationID;	// 24 = 0x18
    double _enabledOffset;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0020000000008d0b
@property(nonatomic) double enabledOffset; // @synthesize enabledOffset=_enabledOffset;
- (void)_enterOffStateForced;	// IMP=0x0010000000008cef
- (void)_enterOnStateForced;	// IMP=0x0010000000008ce9
- (void)_enterOffStateAutomatically;	// IMP=0x0010000000008ce3
- (void)_enterOnStateAutomatically;	// IMP=0x0010000000008cdd
- (void)_cancelAutomaticOnStateChangeConfirmation;	// IMP=0x0010000000008cd7
- (void)_confirmAutomaticOnStateChangeWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0010000000008cc6
- (_Bool)_canBeInOnStateAutomatically;	// IMP=0x0010000000008cbe
- (id)_logString;	// IMP=0x0010000000008c4b
- (void)_cancelAutomaticOnStateChangeConfirmationIfNeeded;	// IMP=0x0010000000008c15
@property(readonly, nonatomic) _Bool enteredOnStateAutomatically;
- (void)enterOffStateForced;	// IMP=0x0010000000008af3
- (void)enterOnStateForced;	// IMP=0x00100000000089da
- (void)enterOffStateAutomatically;	// IMP=0x00100000000088c1
- (void)adjustStateAutomatically;	// IMP=0x0010000000008313
- (void)automaticDisable;	// IMP=0x001000000000824a
- (void)automaticEnable;	// IMP=0x0010000000008181
@property(readonly, nonatomic, getter=isAutomaticEnabled) _Bool automaticEnabled;
- (void)_setStateOff;	// IMP=0x00100000000080aa
- (void)_setStateOn;	// IMP=0x0010000000007fdc
@property(readonly, nonatomic) _Bool isOn;
@property(readonly, nonatomic) _Bool isOff;
- (id)init;	// IMP=0x0010000000007f7c

@end

