//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface PBOSUpdateAssetManager : NSObject
{
    _Bool processingSpaceRequest;	// 8 = 0x8
    _Bool processingAssetRequest;	// 9 = 0x9
    _Bool processedAssetCatalogDownloadResponse;	// 10 = 0xa
}

+ (long long)_compareOSVersion:(id)arg1 andBuild:(id)arg2 withOSVersion:(id)arg3 andBuild:(id)arg4;	// IMP=0x004000000012418c
+ (id)sharedManager;	// IMP=0x001000000011b2e0
@property(nonatomic) _Bool processedAssetCatalogDownloadResponse; // @synthesize processedAssetCatalogDownloadResponse;
@property(nonatomic) _Bool processingAssetRequest; // @synthesize processingAssetRequest;
@property(nonatomic) _Bool processingSpaceRequest; // @synthesize processingSpaceRequest;
- (long long)_purgeAsset:(id)arg1;	// IMP=0x0010000000123b2f
- (void)_reportAssetCatalogDownloadWithResult:(long long)arg1 forAttempt:(long long)arg2;	// IMP=0x0010000000123571
- (void)_refreshAssetCatalogUsingOptions:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000122944
- (id)_downloadOptionsForScanOptions:(id)arg1;	// IMP=0x001000000012200b
- (long long)_purgeableSizeFor:(id)arg1;	// IMP=0x0010000000121c21
- (id)_postedDateForQuery:(id)arg1;	// IMP=0x0010000000121718
- (long long)_performMetadataQuery:(id)arg1;	// IMP=0x00100000001211db
- (id)_queryForLocalAssetSearch;	// IMP=0x001000000012111e
- (id)_queryForAssetDownload;	// IMP=0x0010000000121073
- (id)_queryForAssetPurge;	// IMP=0x0010000000120fb6
- (_Bool)_asset:(id)arg1 withReleaseDate:(id)arg2 matchesUpdate:(id)arg3;	// IMP=0x0010000000120f35
- (long long)_compareAsset:(id)arg1 withAsset:(id)arg2;	// IMP=0x0010000000120c06
- (_Bool)_isAsset:(id)arg1 eligibleForAction:(unsigned long long)arg2 delayingUpdates:(_Bool)arg3;	// IMP=0x001000000012006f
- (void)_finishInstalledAssetForUpdate:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x001000000011f470
- (void)_finishAssetForAction:(unsigned long long)arg1 options:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x001000000011e348
- (void)_configureForVPN;	// IMP=0x001000000011e342
- (void)dateAtWhichDelayedUpdatesExpireWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000011dbd6
- (void)descriptorForCurrentlyInstalledAssetWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000011d63e
- (id)descriptorForAsset:(id)arg1 withReleaseDate:(id)arg2;	// IMP=0x001000000011cd93
- (void)installedAssetForUpdate:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x001000000011cae7
- (void)assetForAction:(unsigned long long)arg1 options:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x001000000011c502
- (void)purgeLocalAssetsWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000011bc6b
- (void)purgeableAssetSpaceWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000011b38d
- (id)init;	// IMP=0x001000000011b337

@end

