//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <BaseBoard/BSTransaction.h>

@class CAAnimation, CALayer, NSString;

@interface PBUICAAnimationTransaction : BSTransaction
{
    CALayer *_layer;	// 8 = 0x8
    CAAnimation *_animation;	// 16 = 0x10
    NSString *_key;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00200000000810a2
@property(readonly, nonatomic) NSString *key; // @synthesize key=_key;
@property(readonly, nonatomic) CAAnimation *animation; // @synthesize animation=_animation;
@property(readonly, nonatomic) CALayer *layer; // @synthesize layer=_layer;
- (void)invalidate;	// IMP=0x0010000000081043
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;	// IMP=0x0010000000081029
- (void)_begin;	// IMP=0x0010000000080f81
- (id)initWithLayer:(id)arg1 animation:(id)arg2 name:(id)arg3;	// IMP=0x0010000000080df2
- (id)initWithLayer:(id)arg1 animation:(id)arg2;	// IMP=0x0010000000080ddc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

