//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString, SSErrorHandler;
@protocol PBUserNotificationDelegate;

@interface PBUserNotificationCenter : NSObject
{
    _Bool _connected;	// 8 = 0x8
    id <PBUserNotificationDelegate> _delegate;	// 16 = 0x10
    SSErrorHandler *_errorHandler;	// 24 = 0x18
    NSMutableDictionary *_registeredOperationClasses;	// 32 = 0x20
}

+ (void)initializeNotificationCenterWithDelegate:(id)arg1;	// IMP=0x00200000000e66a9
+ (id)sharedInstance;	// IMP=0x00100000000e6697
- (void).cxx_destruct;	// IMP=0x00200000000e7f52
@property(retain, nonatomic) NSMutableDictionary *registeredOperationClasses; // @synthesize registeredOperationClasses=_registeredOperationClasses;
@property(getter=isConnected) _Bool connected; // @synthesize connected=_connected;
@property(retain, nonatomic) SSErrorHandler *errorHandler; // @synthesize errorHandler=_errorHandler;
@property(nonatomic) __weak id <PBUserNotificationDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_handleCarMCheck:(id)arg1;	// IMP=0x00100000000e7c39
- (void)_handle2SVCheck:(id)arg1;	// IMP=0x00100000000e7995
- (void)_handleCVVCheck:(id)arg1;	// IMP=0x00100000000e76d1
- (void)errorHandler:(id)arg1 handleSession:(id)arg2;	// IMP=0x00100000000e74b1
- (void)errorHandlerDidDisconnect:(id)arg1;	// IMP=0x00100000000e73a5
- (void)stopErrorHandler;	// IMP=0x00100000000e72f9
- (void)startErrorHandler;	// IMP=0x00100000000e7144
- (void)initializeStoreErrorHandler;	// IMP=0x00100000000e7025
- (void)registerOperationClass:(Class)arg1 forFailureType:(long long)arg2;	// IMP=0x00100000000e6fa1
- (void)_didHandleCFUserNotification:(id)arg1;	// IMP=0x00100000000e6f82
- (id)cfUserNotificationForToken:(int)arg1;	// IMP=0x00100000000e6e2b
- (void)startUserNotificationCenter;	// IMP=0x00100000000e67ca

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

