//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface RMJSONSerialization : NSObject
{
}

+ (id)serializeValue:(id)arg1;	// IMP=0x002000000004ee3a
+ (id)dateFormatter;	// IMP=0x001000000004ed3c

@end

