//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSManagedObjectContext, NSManagedObjectID, NSString, RMPersistentHistoryNotifier;
@protocol RMConduitDelegate;

@interface RMMDMConduit : NSObject
{
    _Bool _madeChangesDuringSync;	// 8 = 0x8
    id <RMConduitDelegate> _delegate;	// 16 = 0x10
    RMPersistentHistoryNotifier *_persistentHistoryNotifier;	// 24 = 0x18
    NSManagedObjectContext *_context;	// 32 = 0x20
    NSManagedObjectID *_managementSourceObjectID;	// 40 = 0x28
}

+ (id)_generateEnrollmentToken;	// IMP=0x00200000000530d7
- (void).cxx_destruct;	// IMP=0x002000000005926c
@property(readonly, nonatomic) NSManagedObjectID *managementSourceObjectID; // @synthesize managementSourceObjectID=_managementSourceObjectID;
@property(readonly, nonatomic) NSManagedObjectContext *context; // @synthesize context=_context;
@property(nonatomic) _Bool madeChangesDuringSync; // @synthesize madeChangesDuringSync=_madeChangesDuringSync;
@property(retain, nonatomic) RMPersistentHistoryNotifier *persistentHistoryNotifier; // @synthesize persistentHistoryNotifier=_persistentHistoryNotifier;
@property(nonatomic) __weak id <RMConduitDelegate> delegate; // @synthesize delegate=_delegate;
- (void)persistentHistoryNotifier:(id)arg1 hasChanges:(id)arg2;	// IMP=0x001000000005902a
- (_Bool)persistentHistoryNotifier:(id)arg1 isChangeInteresting:(id)arg2 stop:(_Bool *)arg3;	// IMP=0x0010000000058adf
- (void)_executeRequestForEndpoint:(id)arg1 requestData:(id)arg2 expectedResponseClass:(Class)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x00100000000587bd
- (id)_requestDataForPayload:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000058787
- (_Bool);	// IMP=0x00100000000583d0
- (_Bool)_processErrorResponse:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000057e08
- (id)_processResponse:(id)arg1 payloadClass:(Class)arg2 error:(id *)arg3;	// IMP=0x0010000000057ac9
- (void)_writeQAStatusData:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000057866
- (void)_didFinishSendingStatusWithError:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000005747c
- (void)sendStatusData:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000005727d
- (void)_didFinishFetchingObject:(id)arg1 objectID:(id)arg2 class:(Class)arg3 endpoint:(id)arg4 response:(id)arg5 error:(id)arg6 completionHandler:(CDUnknownBlockType)arg7;	// IMP=0x00100000000569bc
- (void)_fetchNextObjectOfClass:(Class)arg1 endpoint:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000056198
- (void)_fetchPartialObjectsWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000055ed7
- (void)_processDeclarationItemsWithContext:(id)arg1 infos:(id)arg2 declarationItemClass:(Class)arg3 declarationItemKeyPath:(id)arg4;	// IMP=0x001000000005573d
- (void)_didFinishFetchingDeclarationItems:(id)arg1 error:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000055113
- (void)_fetchDeclarationItemsOnlyIfNeeded:(_Bool)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000054c1c
- (void)_updateWithSyncTokens:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000548a3
- (void)updateWithTokensResponse:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000005474c
- (void)updateWithPushMessage:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000054628
- (void)syncOnlyIfNeeded:(_Bool)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000053fd8
- (_Bool)isSyncAllowed;	// IMP=0x0010000000053fd0
- (void)_didFinishFetchingServerTokens:(id)arg1 error:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000053a6d
- (void)_fetchTokensOnlyIfNeeded:(_Bool)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000534fb
- (void)unenrollWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x001000000005311d
- (void)enrollWithStatusItems:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000052b18
- (id)_statusItemsToSendOnceAfterEnrollment;	// IMP=0x0010000000052894
- (id)statusItemsToSendDuringEnrollment;	// IMP=0x001000000005287b
- (id)statusItemsToImplicitlySubscribeTo;	// IMP=0x00100000000527c7
- (short)errorState;	// IMP=0x0010000000052586
- (void)_stopObservers;	// IMP=0x001000000005252a
- (void)_startObservers;	// IMP=0x001000000005242e
- (void)startWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x001000000005218b
- (id)initWithManagementSourceObjectID:(id)arg1 inContext:(id)arg2;	// IMP=0x00100000000520f2

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

