//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSPersistentContainer;

@interface RMStoreXPCProxyHandler : NSObject
{
    _Bool _hasCommandLineEntitlement;	// 8 = 0x8
    _Bool _hasObserverEntitlement;	// 9 = 0x9
    _Bool _hasProviderEntitlement;	// 10 = 0xa
    _Bool _hasSubscriberEntitlement;	// 11 = 0xb
    NSPersistentContainer *_persistentContainer;	// 16 = 0x10
}

+ (_Bool)_isConnection:(id)arg1 fromApplicationIdentifier:(id)arg2;	// IMP=0x00200000000882da
+ (id)_applicationIdentifierFromConnection:(id)arg1;	// IMP=0x00100000000882be
+ (_Bool)_doesConnection:(id)arg1 haveEntitlements:(id)arg2;	// IMP=0x0010000000088062
- (void).cxx_destruct;	// IMP=0x002000000008c176
@property(readonly, nonatomic) _Bool hasSubscriberEntitlement; // @synthesize hasSubscriberEntitlement=_hasSubscriberEntitlement;
@property(readonly, nonatomic) _Bool hasProviderEntitlement; // @synthesize hasProviderEntitlement=_hasProviderEntitlement;
@property(readonly, nonatomic) _Bool hasObserverEntitlement; // @synthesize hasObserverEntitlement=_hasObserverEntitlement;
@property(readonly, nonatomic) _Bool hasCommandLineEntitlement; // @synthesize hasCommandLineEntitlement=_hasCommandLineEntitlement;
@property(readonly, nonatomic) NSPersistentContainer *persistentContainer; // @synthesize persistentContainer=_persistentContainer;
- (void)publishStatusWithStoreIdentifier:(id)arg1 status:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x001000000008beb5
- (void)removeStatusWithStoreIdentifier:(id)arg1 declarationIdentifier:(id)arg2 declarationServerToken:(id)arg3 sourceIdentifier:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;	// IMP=0x001000000008bc13
- (void)writeStatusWithStoreIdentifier:(id)arg1 declarationType:(id)arg2 declarationIdentifier:(id)arg3 declarationServerToken:(id)arg4 sourceIdentifier:(id)arg5 validity:(_Bool)arg6 reasons:(id)arg7 completionHandler:(CDUnknownBlockType)arg8;	// IMP=0x001000000008b92b
- (void)resolveAsset:(id)arg1 storeIdentifier:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x001000000008b620
- (void)subscribedDeclarationsWithTypes:(id)arg1 storeIdentifier:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x001000000008b34a
- (void)subscribedStoreDeclarationsWithTypes:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000008b093
- (void)subscriberStoresWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x001000000008ae1b
- (void)subscriberStoreWithIdentifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000008ab5b
- (void)applyChangesForStoreIdentifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000008a8c7
- (void)deleteDeclarationWithIdentifier:(id)arg1 storeIdentifier:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x001000000008a61d
- (void)saveDeclaration:(id)arg1 storeIdentifier:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x001000000008a33e
- (void)providerStoresWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x001000000008a0c6
- (void)providerStoreWithIdentifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000089e06
- (void)removeStoreWithIdentifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000089b72
- (void)createStoreWithType:(long long)arg1 defaultToInteractive:(_Bool)arg2 dataSeparated:(_Bool)arg3 options:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;	// IMP=0x00100000000898c1
- (void)fetchDataAtURL:(id)arg1 storeIdentifier:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x00100000000895eb
- (void)setShouldInstallConfiguration:(id)arg1 shouldInstall:(_Bool)arg2 storeIdentifier:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x00100000000893fc
- (void)declarationManifestForStoreIdentifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000008913c
- (void)declarationsWithTypes:(id)arg1 storeIdentifier:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000088e66
- (void)declarationsForStoreIdentifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000088ba6
- (void)declarationWithIdentifier:(id)arg1 storeIdentifier:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x00100000000888d0
- (void)observerStoresWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000088658
- (void)observerStoreWithIdentifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000088398
- (id)initWithXPCConnection:(id)arg1 persistentContainer:(id)arg2;	// IMP=0x0010000000087dfb

@end

