//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Catalyst/CATOperation.h>

@interface DMDBlockOperation : CATOperation
{
    CDUnknownBlockType _block;	// 8 = 0x8
}

+ (id)blockOperationWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x0040000000026e14
- (void).cxx_destruct;	// IMP=0x0020000000026ed4
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
- (void)main;	// IMP=0x0010000000026e6a

@end

