//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface DMDEndTransactionOperation
{
}

+ (id)requiredEntitlements;	// IMP=0x004000000003c0f4
+ (id)whitelistedClassesForRequest;	// IMP=0x001000000003c0c2
+ (_Bool)validateRequest:(id)arg1 error:(id *)arg2;	// IMP=0x001000000003bf98
- (void)runWithRequest:(id)arg1;	// IMP=0x004000000003c101

@end

