//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface DMDRemoveManagedBookOperation
{
}

+ (_Bool)validateRequest:(id)arg1 error:(id *)arg2;	// IMP=0x0040000000066fbd
+ (id)requiredEntitlements;	// IMP=0x0010000000066fb0
+ (id)whitelistedClassesForRequest;	// IMP=0x0010000000066f7e

@end

