//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface DMDSetPasscodeLockGracePeriodOperation
{
}

+ (id)requiredEntitlements;	// IMP=0x004000000006aad6
+ (id)whitelistedClassesForRequest;	// IMP=0x001000000006aaa4

@end

