//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GKDatabaseConnection, GKDiscovery, GKEntitlements, GKEventTuple, GKGameInternal, GKInviteSession, GKMatchResponse, GKResourceManager, GKThreadsafeDictionary, NSDate, NSDictionary, NSLocale, NSMapTable, NSMutableDictionary, NSMutableSet, NSNumber, NSString, NSXPCConnection, _GKStateMachine;
@protocol GKUIViewService, OS_dispatch_queue, OS_dispatch_source;

@interface GKClientProxy : NSObject
{
    _Bool _deniedProductionEnvironment;	// 8 = 0x8
    _Bool _productionSigned;	// 9 = 0x9
    _Bool _installed;	// 10 = 0xa
    _Bool _supportsMultipleActivePlayers;	// 11 = 0xb
    _Bool _isOcelot;	// 12 = 0xc
    unsigned char _achievementsRateLimitedCurrentState;	// 13 = 0xd
    unsigned char _scoresRateLimitedCurrentState;	// 14 = 0xe
    _Bool _initialized;	// 15 = 0xf
    int _pid;	// 16 = 0x10
    unsigned int _applicationState;	// 20 = 0x14
    unsigned int _previousApplicationState;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_replyQueue;	// 32 = 0x20
    NSObject<OS_dispatch_queue> *_authQueue;	// 40 = 0x28
    NSXPCConnection *_connection;	// 48 = 0x30
    GKEntitlements *_entitlements;	// 56 = 0x38
    NSNumber *_adamID;	// 64 = 0x40
    NSNumber *_sandboxExtensionToken;	// 72 = 0x48
    NSNumber *_externalVersion;	// 80 = 0x50
    NSString *_bundleIdentifier;	// 88 = 0x58
    NSString *_originalBundleIdentifier;	// 96 = 0x60
    NSString *_bundleVersion;	// 104 = 0x68
    NSString *_bundleShortVersion;	// 112 = 0x70
    NSString *_name;	// 120 = 0x78
    long long _environment;	// 128 = 0x80
    NSDate *_achievementsRateLimitingStartDate;	// 136 = 0x88
    long long _achievementsRateLimitingCurrentNumberOfRequests;	// 144 = 0x90
    NSDate *_scoresRateLimitingStartDate;	// 152 = 0x98
    long long _scoresRateLimitingCurrentNumberOfRequests;	// 160 = 0xa0
    NSMutableDictionary *_alreadyCoalescingNetworkRequests;	// 168 = 0xa8
    NSString *_language;	// 176 = 0xb0
    GKClientProxy<GKUIViewService> *_viewService;	// 184 = 0xb8
    GKGameInternal *_currentGame;	// 192 = 0xc0
    GKDiscovery *_nearbyDiscovery;	// 200 = 0xc8
    GKEventTuple *_launchEvent;	// 208 = 0xd0
    GKInviteSession *_inviteSession;	// 216 = 0xd8
    GKMatchResponse *_currentMatchResponse;	// 224 = 0xe0
    NSMapTable *_extensionProxies;	// 232 = 0xe8
    _GKStateMachine *_appInitStateMachine;	// 240 = 0xf0
    GKThreadsafeDictionary *_appSessions;	// 248 = 0xf8
    NSObject<OS_dispatch_queue> *_delayedRequestsQueue;	// 256 = 0x100
    GKDatabaseConnection *_delayedRequestsDBConnection;	// 264 = 0x108
    NSObject<OS_dispatch_queue> *_cacheQueue;	// 272 = 0x110
    GKResourceManager *_resourceManager;	// 280 = 0x118
    NSMutableSet *_pendingDataTypesForRefresh;	// 288 = 0x120
    NSDictionary *_preferencesFromBag;	// 296 = 0x128
    NSObject<OS_dispatch_source> *_checkMatchStatusTimer;	// 304 = 0x130
    NSObject<OS_dispatch_queue> *_checkMatchStatusQueue;	// 312 = 0x138
}

+ (id)syncQueue;	// IMP=0x0020000000179024
+ (void)removeClient:(id)arg1;	// IMP=0x001000000017daae
+ (void)enumerateClientsUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000017d9e2
+ (id)clientsToBeEnumerated;	// IMP=0x001000000017d7e1
+ (id)clientForMatchmakingRID:(id)arg1;	// IMP=0x001000000017d60a
+ (id)clientForInviteSessionToken:(id)arg1;	// IMP=0x001000000017d0e5
+ (void)checkGameCenterEnabledForegroundClients;	// IMP=0x001000000017d0df
+ (id)nonGameCenterForegroundClient;	// IMP=0x001000000017cf80
+ (id)foregroundClient;	// IMP=0x001000000017ce47
+ (id)clientForBundleID:(id)arg1 pid:(int)arg2 createIfNecessary:(_Bool)arg3;	// IMP=0x001000000017ce2d
+ (id)clientForBundleID:(id)arg1 bundle:(id)arg2 pid:(int)arg3 createIfNecessary:(_Bool)arg4;	// IMP=0x001000000017befd
+ (_Bool)isExtensionBundleID:(id)arg1;	// IMP=0x001000000017bda8
+ (id)clientForProcessIdentifier:(int)arg1;	// IMP=0x001000000017bd09
+ (id)clientForBundleID:(id)arg1;	// IMP=0x001000000017bcec
+ (id)gameCenterClient;	// IMP=0x001000000017bcc5
+ (id)_clientLookup;	// IMP=0x001000000017bc5e
+ (id)factoryQueue;	// IMP=0x001000000017bc07
+ (void)saveAppInitState:(id)arg1 forBundleID:(id)arg2 pid:(int)arg3;	// IMP=0x0010000000182e44
+ (id)lastKnownAppInitStateForClientWithBundleID:(id)arg1 pid:(int)arg2;	// IMP=0x00100000001828fa
+ (void)authenticationDidChange;	// IMP=0x001000000018233f
+ (void)performDelayedRequestsForEnvironment:(long long)arg1;	// IMP=0x001000000018c477
+ (id)storeAndForwardDirectoryPathForEnvironment:(long long)arg1;	// IMP=0x001000000018b066
+ (void)closeDatabaseFromManagedObjectContextForMOC:(id)arg1;	// IMP=0x001000000019365f
+ (void)closeDatabaseFromManagedObjectContextForPlayer:(id)arg1;	// IMP=0x0010000000193613
+ (id)newManagedObjectContextForClient:(id)arg1 player:(id)arg2;	// IMP=0x001000000019346d
+ (id)_newManagedObjectContextForPlayer:(id)arg1;	// IMP=0x00100000001924b6
+ (id)cacheFileQueue;	// IMP=0x001000000019245f
+ (id)managedObjectModel;	// IMP=0x0010000000192115
+ (void)removeAllCaches;	// IMP=0x0010000000191ad0
+ (void)removeCacheForPlayer:(id)arg1;	// IMP=0x0010000000191315
+ (id)cacheFileURLForClient:(id)arg1 player:(id)arg2;	// IMP=0x00100000001912bc
+ (id)cacheDirectoryURLForClient:(id)arg1 player:(id)arg2;	// IMP=0x0010000000190c9d
+ (id)cacheDirectoryForBundleID:(id)arg1 environment:(long long)arg2;	// IMP=0x0010000000190bf2
+ (id)_existingManagedObjectContextForPlayer:(id)arg1;	// IMP=0x0010000000190892
+ (id)contextKeyForPlayer:(id)arg1;	// IMP=0x0010000000190862
- (void).cxx_destruct;	// IMP=0x001000000017ba58
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *checkMatchStatusQueue; // @synthesize checkMatchStatusQueue=_checkMatchStatusQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *checkMatchStatusTimer; // @synthesize checkMatchStatusTimer=_checkMatchStatusTimer;
@property(copy, nonatomic) NSDictionary *preferencesFromBag; // @synthesize preferencesFromBag=_preferencesFromBag;
@property(retain, nonatomic) NSMutableSet *pendingDataTypesForRefresh; // @synthesize pendingDataTypesForRefresh=_pendingDataTypesForRefresh;
@property(retain, nonatomic) GKResourceManager *resourceManager; // @synthesize resourceManager=_resourceManager;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *cacheQueue; // @synthesize cacheQueue=_cacheQueue;
@property(retain, nonatomic) GKDatabaseConnection *delayedRequestsDBConnection; // @synthesize delayedRequestsDBConnection=_delayedRequestsDBConnection;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *delayedRequestsQueue; // @synthesize delayedRequestsQueue=_delayedRequestsQueue;
@property(retain, nonatomic) GKThreadsafeDictionary *appSessions; // @synthesize appSessions=_appSessions;
@property(retain) _GKStateMachine *appInitStateMachine; // @synthesize appInitStateMachine=_appInitStateMachine;
@property _Bool initialized; // @synthesize initialized=_initialized;
@property(retain, nonatomic) NSMapTable *extensionProxies; // @synthesize extensionProxies=_extensionProxies;
@property(retain) GKMatchResponse *currentMatchResponse; // @synthesize currentMatchResponse=_currentMatchResponse;
@property(retain) GKInviteSession *inviteSession; // @synthesize inviteSession=_inviteSession;
@property(retain, nonatomic) GKEventTuple *launchEvent; // @synthesize launchEvent=_launchEvent;
@property unsigned int previousApplicationState; // @synthesize previousApplicationState=_previousApplicationState;
@property unsigned int applicationState; // @synthesize applicationState=_applicationState;
@property(retain, nonatomic) GKDiscovery *nearbyDiscovery; // @synthesize nearbyDiscovery=_nearbyDiscovery;
@property(retain, nonatomic) GKGameInternal *currentGame; // @synthesize currentGame=_currentGame;
@property(nonatomic) __weak GKClientProxy<GKUIViewService> *viewService; // @synthesize viewService=_viewService;
@property(retain, nonatomic) NSString *language; // @synthesize language=_language;
@property(retain, nonatomic) NSMutableDictionary *alreadyCoalescingNetworkRequests; // @synthesize alreadyCoalescingNetworkRequests=_alreadyCoalescingNetworkRequests;
@property(nonatomic) unsigned char scoresRateLimitedCurrentState; // @synthesize scoresRateLimitedCurrentState=_scoresRateLimitedCurrentState;
@property(nonatomic) long long scoresRateLimitingCurrentNumberOfRequests; // @synthesize scoresRateLimitingCurrentNumberOfRequests=_scoresRateLimitingCurrentNumberOfRequests;
@property(retain, nonatomic) NSDate *scoresRateLimitingStartDate; // @synthesize scoresRateLimitingStartDate=_scoresRateLimitingStartDate;
@property(nonatomic) unsigned char achievementsRateLimitedCurrentState; // @synthesize achievementsRateLimitedCurrentState=_achievementsRateLimitedCurrentState;
@property(nonatomic) long long achievementsRateLimitingCurrentNumberOfRequests; // @synthesize achievementsRateLimitingCurrentNumberOfRequests=_achievementsRateLimitingCurrentNumberOfRequests;
@property(retain, nonatomic) NSDate *achievementsRateLimitingStartDate; // @synthesize achievementsRateLimitingStartDate=_achievementsRateLimitingStartDate;
@property _Bool isOcelot; // @synthesize isOcelot=_isOcelot;
@property(nonatomic) _Bool supportsMultipleActivePlayers; // @synthesize supportsMultipleActivePlayers=_supportsMultipleActivePlayers;
@property(nonatomic) _Bool installed; // @synthesize installed=_installed;
@property(nonatomic) _Bool productionSigned; // @synthesize productionSigned=_productionSigned;
- (void)setDeniedProductionEnvironment:(_Bool)arg1;	// IMP=0x001000000017b6c5
- (_Bool)deniedProductionEnvironment;	// IMP=0x001000000017b6bc
@property(nonatomic) long long environment; // @synthesize environment=_environment;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *bundleShortVersion; // @synthesize bundleShortVersion=_bundleShortVersion;
@property(retain, nonatomic) NSString *bundleVersion; // @synthesize bundleVersion=_bundleVersion;
@property(retain, nonatomic) NSString *originalBundleIdentifier; // @synthesize originalBundleIdentifier=_originalBundleIdentifier;
@property(retain, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@property(retain, nonatomic) NSNumber *externalVersion; // @synthesize externalVersion=_externalVersion;
@property(retain, nonatomic) NSNumber *sandboxExtensionToken; // @synthesize sandboxExtensionToken=_sandboxExtensionToken;
@property(retain, nonatomic) NSNumber *adamID; // @synthesize adamID=_adamID;
@property(retain) GKEntitlements *entitlements; // @synthesize entitlements=_entitlements;
@property(nonatomic) NSXPCConnection *connection; // @synthesize connection=_connection;
@property(nonatomic) int pid; // @synthesize pid=_pid;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *authQueue; // @synthesize authQueue=_authQueue;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *replyQueue; // @synthesize replyQueue=_replyQueue;
- (void)deleteInviteSession;	// IMP=0x001000000017b310
- (id)fetchOrCreateInviteSession;	// IMP=0x001000000017add1
- (void)cancelInvitationForSession:(id)arg1 playerID:(id)arg2 pushTokens:(id)arg3 handler:(CDUnknownBlockType)arg4;	// IMP=0x001000000017a742
- (void)cancelOutstandingCheckMatchStatus;	// IMP=0x001000000017a6b9
- (_Bool)processMatchResponse:(id)arg1;	// IMP=0x00100000001797c5
- (void)checkMatchStatus;	// IMP=0x00100000001792b7
- (void)performAsync:(CDUnknownBlockType)arg1;	// IMP=0x0010000000179251
- (void)performSync:(CDUnknownBlockType)arg1;	// IMP=0x001000000017907b
- (void)setLaunchEvent:(unsigned long long)arg1 withContext:(id)arg2;	// IMP=0x0010000000178db5
- (void)updatePreferencesFromBag:(id)arg1;	// IMP=0x0010000000178d60
- (void)setExtensionProxy:(id)arg1 forBundleID:(id)arg2;	// IMP=0x0010000000178c32
- (_Bool)isExtension;	// IMP=0x0010000000178c2a
- (_Bool)isUIService;	// IMP=0x0010000000178c22
- (_Bool)isGameCenter;	// IMP=0x0010000000178bd4
@property(readonly, nonatomic) NSLocale *locale; // @dynamic locale;
@property(readonly, nonatomic) NSDictionary *gameDescriptor;
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000178713
@property(readonly) unsigned long long hash;
@property(readonly, copy) NSString *description;
- (void)resetCache:(id)arg1;	// IMP=0x0010000000178595
- (void)_setupCache;	// IMP=0x001000000017858f
- (id)credentialForPlayer:(id)arg1;	// IMP=0x0010000000178418
- (id)transportWithCredential:(id)arg1;	// IMP=0x0010000000178361
- (void)dealloc;	// IMP=0x001000000017826d
- (void)updateIfRecentlyInstalled;	// IMP=0x0010000000177e68
- (id)initWithBundleIdentifier:(id)arg1 bundleOrNil:(id)arg2 pid:(int)arg3;	// IMP=0x0010000000177763
- (void)initializeInitializationStateMachine;	// IMP=0x00100000001775fd
- (void)handleCloudKitShareMetadata:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00100000001820b2
- (oneway void)resetLoginCancelCount;	// IMP=0x0010000000181df7
- (oneway void)loadRemoteImageDataForURL:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x0010000000181d65
- (oneway void)localizedMessageFromDictionary:(id)arg1 forBundleID:(id)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000181c53
- (oneway void)getAuthenticatedPlayerIDWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000181b87
- (oneway void)getAccountNameWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000181903
- (oneway void)getAuthenticatedLocalPlayersWithStatus:(unsigned long long)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000180a9e
- (oneway void)getGamedFiredUpWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x001000000018081d
- (oneway void)getAuthenticatedPlayerCredential:(CDUnknownBlockType)arg1;	// IMP=0x00100000001803f8
- (oneway void)getAuthenticatedPlayerInfo:(CDUnknownBlockType)arg1;	// IMP=0x001000000018004a
- (oneway void)getPrivateServicesForPID:(int)arg1 localPlayer:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x001000000017fb3d
- (oneway void)getServicesForPID:(int)arg1 localPlayer:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x001000000017f4fa
- (oneway void)getPrivateServicesWithTransport:(id)arg1 forClient:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x001000000017f015
- (oneway void)getServicesWithTransport:(id)arg1 forClient:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x001000000017ea2c
- (oneway void)setTestGame:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x001000000017ea15
- (oneway void)messagesDidReceiveGameCenterURL:(id)arg1 senderHandle:(id)arg2 contactID:(id)arg3;	// IMP=0x001000000017df09
- (oneway void)setHostPID:(int)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x001000000017def2
- (id)serviceForClass:(Class)arg1 transport:(id)arg2 client:(id)arg3 credential:(id)arg4;	// IMP=0x001000000017dc65
- (void)didEnterForeground;	// IMP=0x001000000018359a
- (void)updateAppInitState;	// IMP=0x00100000001834ad
- (id)verifyAuthorized;	// IMP=0x00100000001827e7
- (id)appInitState;	// IMP=0x00100000001827ce
- (_Bool)setAppInitState:(id)arg1;	// IMP=0x00100000001827b5
- (void)stateDidChange;	// IMP=0x001000000018273a
- (id)missingTransitionFromState:(id)arg1 toState:(id)arg2;	// IMP=0x00100000001825fd
- (void)sendAuthenticationDidChangeNotificationWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x001000000018237a
- (void)bgInitializeWithCredential:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000018abda
- (void)initializeWithCredential:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000018a5d0
- (void)removeAppSessionForPlayer:(id)arg1;	// IMP=0x001000000018a5b7
- (id)appSessionForPlayer:(id)arg1;	// IMP=0x001000000018a530
- (void)addAppSession:(id)arg1 forCredential:(id)arg2;	// IMP=0x001000000018a419
- (void)backgroundWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000189c69
- (void)terminateWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000189554
- (oneway void)setLogBits:(int)arg1;	// IMP=0x00100000001892f5
- (oneway void)authenticatedPlayersDidChange:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x0010000000188b6f
- (oneway void)completedOptimisticAuthenticationWithResponse:(id)arg1 error:(id)arg2;	// IMP=0x0010000000188ac6
- (oneway void)setCurrentGame:(id)arg1 serverEnvironment:(long long)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x00100000001884bd
- (oneway void)getPreferenceForKey:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x001000000018844d
- (oneway void)setPreferencesValues:(id)arg1;	// IMP=0x00100000001882f2
- (oneway void)refreshPendingDataTypes;	// IMP=0x00100000001881cf
- (oneway void)refreshContentsForDataType:(unsigned int)arg1 userInfo:(id)arg2;	// IMP=0x0010000000187ba2
- (oneway void)setBadgeCount:(unsigned long long)arg1 forType:(unsigned long long)arg2;	// IMP=0x00100000001879ec
- (oneway void)session:(id)arg1 didReceiveMessage:(id)arg2 withData:(id)arg3 fromPlayer:(id)arg4;	// IMP=0x00100000001877ce
- (oneway void)session:(id)arg1 didReceiveData:(id)arg2 fromPlayer:(id)arg3;	// IMP=0x00100000001875d5
- (oneway void);	// IMP=0x00100000001873dc
- (oneway void)session:(id)arg1 player:(id)arg2 didChangeConnectionState:(long long)arg3;	// IMP=0x00100000001871f5
- (oneway void)session:(id)arg1 removedPlayer:(id)arg2;	// IMP=0x0010000000187016
- (oneway void)session:(id)arg1 addedPlayer:(id)arg2;	// IMP=0x0010000000186e37
- (oneway void)didReceiveData:(id)arg1 reliably:(_Bool)arg2 forRecipients:(id)arg3 fromSender:(id)arg4;	// IMP=0x0010000000186c35
- (oneway void)didDisconnectFromParticipantWithID:(id)arg1;	// IMP=0x0010000000186a6f
- (oneway void)didConnectToParticipantWithID:(id)arg1;	// IMP=0x00100000001868a9
- (oneway void)relayPushNotification:(id)arg1;	// IMP=0x0010000000186618
- (oneway void)nearbyDataReceivedForPlayerID:(id)arg1 deviceID:(id)arg2 data:(id)arg3;	// IMP=0x001000000018641f
- (oneway void)nearbyPlayerLostForPlayerID:(id)arg1 deviceID:(id)arg2;	// IMP=0x0010000000186240
- (oneway void)nearbyPlayerFoundForPlayerID:(id)arg1 deviceID:(id)arg2 discoveryInfo:(id)arg3;	// IMP=0x0010000000186047
- (oneway void)cancelGameInvite:(id)arg1;	// IMP=0x0010000000185db6
- (oneway void)cancelInviteWithNotification:(id)arg1;	// IMP=0x0010000000185b25
- (oneway void)declineInviteWithNotification:(id)arg1;	// IMP=0x0010000000185894
- (oneway void)acceptInviteWithNotification:(id)arg1;	// IMP=0x0010000000185603
- (oneway void)acceptMultiplayerGameInvite;	// IMP=0x00100000001853e1
- (oneway void)fetchTurnBasedData;	// IMP=0x0010000000185222
- (oneway void)achievementSelected:(id)arg1;	// IMP=0x001000000018505c
- (oneway void)scoreSelected:(id)arg1;	// IMP=0x0010000000184e96
- (oneway void)challengeCompleted:(id)arg1;	// IMP=0x0010000000184c67
- (oneway void)challengeReceived:(id)arg1;	// IMP=0x0010000000184aa1
- (oneway void)completedChallengeSelected:(id)arg1;	// IMP=0x00100000001848db
- (oneway void)receivedChallengeSelected:(id)arg1;	// IMP=0x0010000000184715
- (oneway void)friendRequestSelected:(id)arg1;	// IMP=0x001000000018450a
- (oneway void)respondedToNearbyInvite:(id)arg1;	// IMP=0x0010000000184344
- (oneway void)resetNetworkActivity;	// IMP=0x00100000001841a5
- (oneway void)endNetworkActivity;	// IMP=0x0010000000184006
- (oneway void)beginNetworkActivity;	// IMP=0x0010000000183e67
- (oneway void)requestSandboxExtension:(CDUnknownBlockType)arg1;	// IMP=0x0010000000183c4f
- (void)performDelayedRequestsForCredential:(id)arg1;	// IMP=0x001000000018cae1
- (void)performDelayedRequestsForEnvironment:(long long)arg1;	// IMP=0x001000000018ca12
- (id)removeGameWriterWithCredential:(id)arg1;	// IMP=0x001000000018c3e4
- (id)deletePlayerPhotoWriterWithCredential:(id)arg1;	// IMP=0x001000000018c351
- (id)setPlayerPhotoWriterWithCredential:(id)arg1;	// IMP=0x001000000018c2be
- (id)setPlayerStatusWriterWithCredential:(id)arg1;	// IMP=0x001000000018c22b
- (id)_delayedRequestWriterWithCacheWriterClass:(Class)arg1 cacheReaderClass:(Class)arg2 networkWriterClass:(Class)arg3 bagKey:(id)arg4 batchSubmissionInterval:(long long)arg5 credential:(id)arg6;	// IMP=0x001000000018bdc5
- (void)_removeDelayedRequestStore;	// IMP=0x001000000018b631
- (void)_setupDelayedRequestsWriters;	// IMP=0x001000000018b40b
- (id)requestsCacheForEnvironment:(long long)arg1;	// IMP=0x001000000018b1d8
- (id)storeAndForwardDirectoryPathForEnvironment:(long long)arg1;	// IMP=0x001000000018b16b
- (void)invalidateStoreFrontDependentObjects;	// IMP=0x00100000001921d7
- (id)transactionGroupIfCacheExistsForPlayer:(id)arg1;	// IMP=0x0010000000190b2d
- (id)transactionGroupForPlayer:(id)arg1;	// IMP=0x0010000000190a97
- (id)_managedObjectContextForPlayer:(id)arg1;	// IMP=0x0010000000190918

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

