//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GKDatabaseConnection, NSString;

@interface GKDelayedSetPhotoCacheWriter : NSObject
{
    GKDatabaseConnection *_connection;	// 8 = 0x8
}

+ (id)writerWithDatabaseConnection:(id)arg1;	// IMP=0x0020000000109594
- (void).cxx_destruct;	// IMP=0x002000000010a790
// Error: Property attributes should begin with the type ('T') attribute, property name: connection
// Property attributes: (null)

- (void)writeResources:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000109c47
- (void)writeToDatabase:(struct sqlite3 *)arg1 statementStore:(id)arg2 withInsertSQL:(id)arg3 updateSQL:(id)arg4 bindOperation:(CDUnknownBlockType)arg5;	// IMP=0x00100000001098c2
- (void)bindParametersForGetOldPhotosStatement:(struct sqlite3_stmt *)arg1 playerID:(id)arg2;	// IMP=0x00100000001098aa
- (id)getOldPhotosSQL;	// IMP=0x0010000000109881
- (void)bindParametersForDeleteOldPhotosStatement:(struct sqlite3_stmt *)arg1 requestsRowID:(long long)arg2;	// IMP=0x001000000010986a
- (id)deleteOldPhotosSQL;	// IMP=0x0010000000109841
- (void)bindParametersForPhotoStatement:(struct sqlite3_stmt *)arg1 photo:(id)arg2 avatarType:(id)arg3 requestsRowID:(long long)arg4;	// IMP=0x001000000010979b
- (id)photosInsertSQL;	// IMP=0x0010000000109760
- (void)bindParametersForRequestsStatement:(struct sqlite3_stmt *)arg1 playerID:(id)arg2;	// IMP=0x00100000001096c3
- (id)requestsInsertSQL;	// IMP=0x0010000000109693
@property(readonly, nonatomic) GKDatabaseConnection *databaseConnection;
- (id)initWithDatabaseConnection:(id)arg1;	// IMP=0x00100000001095f1

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

