//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSDate, NSNumber, NSSet, NSString;

@interface GKGameSummaryInternal
{
    _Bool _isArcade;	// 8 = 0x8
    NSString *_bundleID;	// 16 = 0x10
    NSNumber *_adamID;	// 24 = 0x18
    NSDate *_playedAt;	// 32 = 0x20
    NSSet *_compatiblePlatforms;	// 40 = 0x28
}

+ (id)secureCodedPropertyKeys;	// IMP=0x0040000000223c7b
- (void).cxx_destruct;	// IMP=0x002000000022430f
@property(nonatomic) _Bool isArcade; // @synthesize isArcade=_isArcade;
@property(retain, nonatomic) NSSet *compatiblePlatforms; // @synthesize compatiblePlatforms=_compatiblePlatforms;
@property(retain, nonatomic) NSDate *playedAt; // @synthesize playedAt=_playedAt;
@property(retain, nonatomic) NSNumber *adamID; // @synthesize adamID=_adamID;
@property(retain, nonatomic) NSString *bundleID; // @synthesize bundleID=_bundleID;
- (id)description;	// IMP=0x0010000000224130
- (id)initWithGameSummary:(id)arg1;	// IMP=0x0010000000223de5

@end

