//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface GKServiceInterface : NSObject
{
}

+ (void)configureInterface:(id)arg1;	// IMP=0x0040000000227e4e
+ (id)interfaceProtocol;	// IMP=0x0010000000227d35
+ (id)interface;	// IMP=0x0010000000227cb6
+ (id)plistClasses;	// IMP=0x0010000000227b86

@end

