//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface GKTurnBasedMultiplayerCanceledExchangeBulletin
{
}

+ (_Bool)shouldLoadCacheData;	// IMP=0x00400000001f1618
- (void)loadBulletinMessageWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x00400000001f1dfd
- (void)loadDataWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x00100000001f1634
- (id)aggregateDictionaryKey;	// IMP=0x00100000001f1620

@end

