//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface SYDUserNotifications : NSObject
{
}

+ (id)queue;	// IMP=0x004000000000a42b
+ (_Bool)shouldShowNotifications;	// IMP=0x001000000000a3ff
+ (id)userNotificationCenter;	// IMP=0x001000000000a2f2
+ (void)requestAuthorizationIfNecessary;	// IMP=0x001000000000a172
+ (void)showNotificationWithTitle:(id)arg1 body:(id)arg2 threadIdentifier:(id)arg3;	// IMP=0x0010000000009e8f
+ (void)showUserNotificationIfEnabledForStoreIdentifier:(id)arg1 format:(id)arg2;	// IMP=0x0010000000009c42

@end

