//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface CKKSSQLResult : NSObject
{
    NSString *_stringValue;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x002000000002c8a6
@property(retain) NSString *stringValue; // @synthesize stringValue=_stringValue;
- (id)asBase64DecodedData;	// IMP=0x001000000002c7f0
- (id)asISO8601Date;	// IMP=0x001000000002c743
- (id)asNSNumberInteger;	// IMP=0x001000000002c6a5
- (id)asString;	// IMP=0x001000000002c693
- (long long)asNSInteger;	// IMP=0x001000000002c64f
- (_Bool)asBOOL;	// IMP=0x001000000002c60b
- (id)init:(id)arg1;	// IMP=0x001000000002c5a0

@end

