//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface OTPersonaActualAdapter : NSObject
{
}

- (void)performBlockWithPersonaIdentifier:(id)arg1 block:(CDUnknownBlockType)arg2;	// IMP=0x0040000000150d6e
- (void)prepareThreadForKeychainAPIUseForPersonaIdentifier:(id)arg1;	// IMP=0x0010000000150c22
- (_Bool)currentThreadIsForPrimaryiCloudAccount;	// IMP=0x0010000000150abc
- (id)currentThreadPersonaUniqueString;	// IMP=0x0010000000150a3b
- (id)init;	// IMP=0x0010000000150a0c

@end

