//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, NSXPCListener;

@interface SFKeychainControlManager : NSObject
{
    NSXPCListener *_listener;	// 8 = 0x8
}

+ (id)sharedManager;	// IMP=0x0020000000070e3f
- (void).cxx_destruct;	// IMP=0x0020000000070b5a
- (void)rpcDeleteCorruptedItemsWithReply:(CDUnknownBlockType)arg1;	// IMP=0x0010000000070add
- (void)rpcFindCorruptedItemsWithReply:(CDUnknownBlockType)arg1;	// IMP=0x0010000000070a53
- (_Bool)deleteCorruptedItemsWithError:(id *)arg1;	// IMP=0x00100000000706de
- (id)findCorruptedItemsWithError:(id *)arg1;	// IMP=0x0010000000070026
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x001000000006fe1e
- (id)xpcControlEndpoint;	// IMP=0x001000000006fdca
- (id)_init;	// IMP=0x001000000006fd3d

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

