//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface IXClientProtocolInterface : NSObject
{
}

+ (void)configureInterface:(id)arg1;	// IMP=0x00400000000817d5
+ (id)interfaceProtocol;	// IMP=0x00100000000817c4
+ (id)interface;	// IMP=0x00100000000816f2
+ (id)new;	// IMP=0x00000000000816e0
- (id)init;	// IMP=0x00400000000816ce

@end

