//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface IXFileManager : NSObject
{
}

+ (id)defaultManager;	// IMP=0x00400000000355fa
- (unsigned long long)diskUsageForURL:(id)arg1;	// IMP=0x0000000000039231
- (unsigned long long)_diskUsageForDirectoryURL:(id)arg1;	// IMP=0x00100000000388bd
- (id)realPathForURL:(id)arg1 ifChildOfURL:(id)arg2;	// IMP=0x00100000000375ea
- (_Bool)_validateSymlink:(id)arg1 withStartingDepth:(unsigned int)arg2 andEndingDepth:(unsigned int *)arg3;	// IMP=0x001000000003739d
- (id)_realPathForURL:(id)arg1 allowNonExistentPathComponents:(_Bool)arg2;	// IMP=0x00100000000371c6
- (id)_realPathWhatExistsInPath:(id)arg1;	// IMP=0x0010000000036eb5
- (_Bool)setPermissionsOfItemAtURL:(id)arg1 toMode:(unsigned short)arg2 error:(id *)arg3;	// IMP=0x0010000000036dd6
- (_Bool)setDataProtectionClassOfItemAtURL:(id)arg1 toClass:(int)arg2 ifPredicate:(CDUnknownBlockType)arg3 error:(id *)arg4;	// IMP=0x0010000000036b7d
- (_Bool)dataProtectionClassOfItemAtURL:(id)arg1 class:(int *)arg2 error:(id *)arg3;	// IMP=0x00100000000369e8
- (id)debugDescriptionOfItemAtURL:(id)arg1;	// IMP=0x00100000000368ff
- (_Bool)itemDoesNotExistAtURL:(id)arg1;	// IMP=0x00100000000367b3
- (_Bool)itemExistsAtURL:(id)arg1;	// IMP=0x001000000003679f
- (_Bool)itemExistsAtURL:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000036788
- (_Bool)itemExistsAtURL:(id)arg1 isDirectory:(_Bool *)arg2 error:(id *)arg3;	// IMP=0x0010000000036775
- (id)destinationOfSymbolicLinkAtURL:(id)arg1 error:(id *)arg2;	// IMP=0x00100000000365c5
- (_Bool)createSymbolicLinkAtURL:(id)arg1 withDestinationURL:(id)arg2 error:(id *)arg3;	// IMP=0x001000000003645b
- (id)urlsForItemsInDirectoryAtURL:(id)arg1 ignoringSymlinks:(_Bool)arg2 error:(id *)arg3;	// IMP=0x0010000000036449
- (_Bool)_removeACLAtPath:(const char *)arg1 isDir:(_Bool)arg2 error:(id *)arg3;	// IMP=0x0010000000035d3d
- (_Bool)_traverseDirectory:(id)arg1 error:(id *)arg2 withBlock:(CDUnknownBlockType)arg3;	// IMP=0x0010000000035aa3
- (id)createTemporaryDirectoryInDirectoryURL:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000035a93
- (_Bool)moveItemAtURL:(id)arg1 toURL:(id)arg2 error:(id *)arg3;	// IMP=0x0010000000035a78
- (_Bool)copyItemAtURL:(id)arg1 toURL:(id)arg2 error:(id *)arg3;	// IMP=0x0010000000035a5d
- (_Bool)moveItemIfExistsAtURL:(id)arg1 toURL:(id)arg2 error:(id *)arg3;	// IMP=0x0010000000035a45
- (_Bool)copyItemIfExistsAtURL:(id)arg1 toURL:(id)arg2 error:(id *)arg3;	// IMP=0x0010000000035a2d
- (_Bool)_moveItemAtURL:(id)arg1 toURL:(id)arg2 failIfSrcMissing:(_Bool)arg3 error:(id *)arg4;	// IMP=0x0010000000035706
- (_Bool)_copyItemAtURL:(id)arg1 toURL:(id)arg2 failIfSrcMissing:(_Bool)arg3 error:(id *)arg4;	// IMP=0x00100000000356f0
- (_Bool)createDirectoryAtURL:(id)arg1 withIntermediateDirectories:(_Bool)arg2 mode:(unsigned short)arg3 error:(id *)arg4;	// IMP=0x00100000000356cb
- (_Bool)createDirectoryAtURL:(id)arg1 withIntermediateDirectories:(_Bool)arg2 mode:(unsigned short)arg3 class:(int)arg4 error:(id *)arg5;	// IMP=0x00100000000356b0
- (_Bool)removeItemAtURL:(id)arg1 keepParent:(_Bool)arg2 error:(id *)arg3;	// IMP=0x001000000003569e
- (_Bool)removeItemAtURL:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000035687

@end

