//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface IXSHealthKitDataUninstallAlert
{
}

+ (void)viewHealthKitDataForAppWithBundleID:(id)arg1;	// IMP=0x0020000000060731
+ (void)healthKitDataPresentForAppWithBundleID:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000006035a
+ (Class)hkBehaviorClass;	// IMP=0x0010000000060139
+ (Class)hkSourceStoreClass;	// IMP=0x0010000000060114
+ (Class)hkHealthStoreClass;	// IMP=0x00100000000600ef
+ (void)openHealthKitClasses;	// IMP=0x001000000005ffd5
- (id)cancelButtonLabel;	// IMP=0x004000000006033a
- (id)defaultButtonLabel;	// IMP=0x001000000006031a
- (id)message;	// IMP=0x00100000000602a0
- (id)title;	// IMP=0x00100000000601ce
- (id)initWithAppRecord:(id)arg1 bundleIdentifier:(id)arg2;	// IMP=0x001000000006015e

@end

