//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableSet, NSSet, NSURL;
@protocol OS_dispatch_queue;

@interface IXSPendingOperationsTracker : NSObject
{
    NSURL *_sentinelPath;	// 8 = 0x8
    NSMutableSet *_pendingOperationIdentities;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_internalQueue;	// 24 = 0x18
}

+ (id)sharedInstance;	// IMP=0x0040000000032557
- (void).cxx_destruct;	// IMP=0x0020000000033762
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *internalQueue; // @synthesize internalQueue=_internalQueue;
@property(retain, nonatomic) NSMutableSet *pendingOperationIdentities; // @synthesize pendingOperationIdentities=_pendingOperationIdentities;
- (void)clearAllPendingOperations;	// IMP=0x001000000003359a
@property(readonly, nonatomic) NSSet *pendingWorkIdentities;
- (void)endPendingOperationForIdentity:(id)arg1;	// IMP=0x00100000000331f3
- (void)beginPendingOperationForIdentity:(id)arg1;	// IMP=0x0010000000032fc7
- (void)_onQueue_writePendingWork;	// IMP=0x0010000000032ced
- (id)initWithSentinelPathOverride:(id)arg1;	// IMP=0x0010000000032c2c
- (id)init;	// IMP=0x0010000000032c18
- (void)_deserializePendingOperationIdentities;	// IMP=0x00100000000329a1
- (_Bool)_deserializeKeyedArchiveFromData:(id)arg1 atURL:(id)arg2;	// IMP=0x0010000000032873
- (_Bool)_deserializePlistFormatFromData:(id)arg1 atURL:(id)arg2;	// IMP=0x0010000000032682
@property(readonly, nonatomic) NSURL *sentinelPath; // @synthesize sentinelPath=_sentinelPath;

@end

