//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class SSKeyValueStore;
@protocol OS_dispatch_queue;

@interface KeyValueStore : NSObject
{
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 8 = 0x8
    SSKeyValueStore *_keyValueStore;	// 16 = 0x10
}

+ (void)setValuesWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x00400000001979cb
+ (void)removeValuesWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000197984
+ (void)removeAllValuesWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x001000000019793d
+ (void)removeAccountWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x00100000001978f6
+ (void)observeXPCServer:(id)arg1;	// IMP=0x0010000000197850
+ (void)getValuesWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x001000000019779d
+ (id)defaultKeyValueStore;	// IMP=0x00100000001975aa
- (void)_setValuesWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x002000000019823e
- (void)_removeValuesWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000198093
- (void)_removeAllValuesWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000197f29
- (void)_removeAccountWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000197e6f
- (void)_handleMessage:(id)arg1 connection:(id)arg2 withReplyBlock:(CDUnknownBlockType)arg3;	// IMP=0x0010000000197d48
- (void)_handleMessage:(id)arg1 connection:(id)arg2 withBlock:(CDUnknownBlockType)arg3;	// IMP=0x0010000000197c48
- (void)_getValuesWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000197a12
- (id)valueForDomain:(id)arg1 key:(id)arg2;	// IMP=0x001000000019763d
- (void)setValue:(id)arg1 forDomain:(id)arg2 key:(id)arg3;	// IMP=0x0010000000197627
- (void)dealloc;	// IMP=0x0010000000197561
- (id)init;	// IMP=0x0010000000197503

@end

