//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ISOperationQueue, SSMetricsEventController;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface MetricsController : NSObject
{
    long long _backoffRetryCount;	// 8 = 0x8
    NSObject<OS_dispatch_source> *_backoffRetryTimer;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 24 = 0x18
    SSMetricsEventController *_eventController;	// 32 = 0x20
    ISOperationQueue *_operationQueue;	// 40 = 0x28
}

+ (id)sharedInstance;	// IMP=0x004000000016e20d
- (void).cxx_destruct;	// IMP=0x0020000000170272
- (void)_sendUnentitledResponseToMessage:(id)arg1 connection:(id)arg2;	// IMP=0x0010000000170018
- (void)_scheduleBackoffRetry;	// IMP=0x001000000016fbd6
- (void)_reportEventsIfNeeded;	// IMP=0x001000000016f87c
- (void)_reportEvents;	// IMP=0x001000000016f575
- (id)_operationQueue;	// IMP=0x001000000016f4b9
- (_Bool)_hasEntitlements:(id)arg1;	// IMP=0x001000000016f45e
- (void)_cancelBackoffRetryTimer;	// IMP=0x001000000016f428
- (void)_cancelBackoffRetry;	// IMP=0x001000000016f403
- (void)setInternalSettingsWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x001000000016f282
- (void)reportEventsWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x001000000016ee2a
- (void)recordAnalyticsWithMetricsDialogEventWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x001000000016ea90
- (void)insertEventWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x001000000016e6eb
- (void)getInternalSettingsWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x001000000016e5d7
- (void)configureDuet;	// IMP=0x001000000016e5d1
- (void)recordAnalyticsWithMetricsDialogEvent:(id)arg1 forTopic:(id)arg2;	// IMP=0x001000000016e324
- (void)observeXPCServer:(id)arg1;	// IMP=0x001000000016e262
- (void)dealloc;	// IMP=0x001000000016e174
- (id)init;	// IMP=0x001000000016e08f

@end

