//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <StoreServices/SSSQLiteEntity.h>

@interface PreorderEntity : SSSQLiteEntity
{
}

+ (id)newValueDictionaryWithItem:(id)arg1;	// IMP=0x00400000000f9f62
+ (id)newClientPreorderWithPersistentID:(long long)arg1 allValues:(const id *)arg2;	// IMP=0x00100000000f9e13
+ (id)allProperties;	// IMP=0x00100000000f9d9e
+ (id)databaseTable;	// IMP=0x00100000000f9d91
- (void)setValuesWithItem:(id)arg1;	// IMP=0x00400000000fa141

@end

