//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class SSSQLiteDatabase;

@interface PurchaseActionsDatabase : NSObject
{
    SSSQLiteDatabase *_database;	// 8 = 0x8
}

+ (_Bool)_setupDatabase:(id)arg1;	// IMP=0x00400000000c463d
- (void).cxx_destruct;	// IMP=0x00200000000c475d
- (void)incrementPingbackRetryCountForApp:(id)arg1;	// IMP=0x00100000000c428a
- (void)removeNonPendingInstallAttributionPingbacksBeforeDate:(id)arg1;	// IMP=0x00100000000c3ecd
- (void)removeInstallAttributionPingbackForApp:(id)arg1;	// IMP=0x00100000000c3b1a
- (void)getPendingInstallAttributionPingbacksWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x00100000000c35b2
- (void)setPingbackPendingForApp:(id)arg1;	// IMP=0x00100000000c31ff
- (void)getInstallAttributionPingbackForApp:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000c2aab
- (void)insertInstallAttributionPingback:(id)arg1;	// IMP=0x00100000000c24cc
- (void)removeInstallAttributionParamsBeforeDate:(id)arg1;	// IMP=0x00100000000c210f
- (void)removeInstallAttributionParamsForApp:(id)arg1;	// IMP=0x00100000000c1d5c
- (void)getInstallAttributionParamsForApp:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000c15a2
- (void)insertInstallAttributionParams:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000c0fd7
- (void)resetTimestampsForApp:(id)arg1;	// IMP=0x00100000000c05d0
- (void)insertPurchaseIntent:(id)arg1;	// IMP=0x00100000000c012c
- (void)getPurchaseIntentsForApp:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00100000000bfb55
- (void)deletePurchaseIntentsForApp:(id)arg1;	// IMP=0x00100000000bf918
- (void)readUsingTransactionBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000000bf81e
- (void)readAsyncUsingTransactionBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000000bf76b
- (void)modifyUsingTransactionBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000000bf66d
- (id)initWithDatabaseURL:(id)arg1 readOnly:(_Bool)arg2;	// IMP=0x00100000000bf59a
- (id)init;	// IMP=0x00100000000bf508

@end

