//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ICConnectionConfiguration, ICUserIdentity, ICUserIdentityStore, ML3MusicLibrary;
@protocol ICDBackgroundTaskScheduling;

@interface BaseRequestHandler : NSObject
{
    _Bool _active;	// 8 = 0x8
    ICUserIdentity *_userIdentity;	// 16 = 0x10
    ICUserIdentityStore *_userIdentityStore;	// 24 = 0x18
    ICConnectionConfiguration *_configuration;	// 32 = 0x20
    ML3MusicLibrary *_musicLibrary;	// 40 = 0x28
    id <ICDBackgroundTaskScheduling> _taskScheduler;	// 48 = 0x30
}

+ (id)accountlessHandler;	// IMP=0x002000000002104b
+ (_Bool)supportsAccountlessHandling;	// IMP=0x0010000000021043
+ (id)managedConfigurations;	// IMP=0x0010000000020f44
+ (id)deleteHandlerForConfiguration:(id)arg1;	// IMP=0x0010000000020dfa
+ (id)handlerForConfiguration:(id)arg1;	// IMP=0x0010000000020cb8
+ (id)handlers;	// IMP=0x0010000000020c89
+ (id)globalSerialQueue;	// IMP=0x0010000000020c26
- (void).cxx_destruct;	// IMP=0x0020000000020bd1
@property(nonatomic, getter=isActive) _Bool active; // @synthesize active=_active;
@property(retain, nonatomic) id <ICDBackgroundTaskScheduling> taskScheduler; // @synthesize taskScheduler=_taskScheduler;
@property(readonly, nonatomic) ML3MusicLibrary *musicLibrary; // @synthesize musicLibrary=_musicLibrary;
@property(readonly, nonatomic) ICConnectionConfiguration *configuration; // @synthesize configuration=_configuration;
@property(readonly, nonatomic) ICUserIdentityStore *userIdentityStore; // @synthesize userIdentityStore=_userIdentityStore;
@property(readonly, nonatomic) ICUserIdentity *userIdentity; // @synthesize userIdentity=_userIdentity;
- (void)updateLibraryWithReason:(long long)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000020b76
- (id)description;	// IMP=0x0010000000020a8b
- (void)cancelOperationsWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0010000000020a85
- (void)increasePriorityForAllOperations;	// IMP=0x0010000000020a7f
- (void)decreasePriorityForAllOperations;	// IMP=0x0010000000020a79
- (void)onCalloutQueue:(CDUnknownBlockType)arg1;	// IMP=0x00100000000209d6
- (void)cancellAllOperations;	// IMP=0x00100000000209d0
- (void)performInitialLibraryUpdate;	// IMP=0x00100000000209ca
- (void)becomeInactiveWithDeauthentication:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000209c4
- (void)becomeActive;	// IMP=0x00100000000209be
- (id)initWithConfiguration:(id)arg1;	// IMP=0x00100000000208d5
- (id)init;	// IMP=0x0010000000020893

@end

