//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSOperationQueue, NSString;
@protocol ICDHandlerProviding;

@interface CloudService : NSObject
{
    NSString *_requestingBundleID;	// 8 = 0x8
    id <ICDHandlerProviding> _handlerProvider;	// 16 = 0x10
    NSOperationQueue *_operationQueue;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x002000000008cc46
@property(readonly, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
@property(readonly, nonatomic) __weak id <ICDHandlerProviding> handlerProvider; // @synthesize handlerProvider=_handlerProvider;
@property(copy, nonatomic) NSString *requestingBundleID; // @synthesize requestingBundleID=_requestingBundleID;
- (void)_updateSagaLibraryWithReason:(long long)arg1 allowNoisyAuthPrompt:(_Bool)arg2 forConfiguration:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x001000000008c9b5
- (void)listCloudServerOperations;	// IMP=0x001000000008c971
- (void)processPendingKeyInvalidations;	// IMP=0x001000000008c92d
- (void)fetchEnhancedAudioOfflineKeys;	// IMP=0x001000000008c8e9
- (void)refreshEnhancedAudioSharedKeys;	// IMP=0x001000000008c8a5
- (void)importSubscriptionContainerArtworkForPersistentID:(long long)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000008c6ad
- (void)updatePinnedSubscribedPlaylistsWithConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000008c4e1
- (void)disableCloudLibraryWithReason:(long long)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000008c368
- (void)authenticateForConfiguration:(id)arg1 startInitialImport:(_Bool)arg2 enableCloudLibraryPolicy:(long long)arg3 isExplicitUserAction:(_Bool)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x001000000008c256
- (void)loadMissingArtworkForConfiguration:(id)arg1;	// IMP=0x001000000008bf93
- (void)loadUpdateProgressForConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000008bdbf
- (void)loadIsUpdateInProgressForConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000008bbe5
- (void)loadArtworkInfoForSubscriptionContainerPersistentIDs:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000008b9b9
- (void)loadScreenshotInfoForSubscriptionPersistentIDs:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000008b78d
- (void)loadArtworkInfoForSubscriptionItemPersistentIDs:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000008b559
- (void)deprioritizeSubscriptionContainerArtworkForPersistentID:(long long)arg1 configuration:(id)arg2;	// IMP=0x001000000008b3f2
- (void)deprioritizeSubscriptionScreenshotForPersistentID:(long long)arg1 configuration:(id)arg2;	// IMP=0x001000000008b28b
- (void)deprioritizeSubscriptionItemArtworkForPersistentID:(long long)arg1 configuration:(id)arg2;	// IMP=0x001000000008b124
- (void)importSubscriptionScreenshotForPersistentID:(long long)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000008af2c
- (void)importSubscriptionItemArtworkForPersistentID:(long long)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000008ad34
- (void)importAlbumArtistHeroImageForPersistentID:(long long)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000008aa22
- (void)importArtistHeroImageForPersistentID:(long long)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000008a710
- (void)updateArtistHeroImagesForConfiguration:(id)arg1;	// IMP=0x001000000008a4e1
- (void)deprioritizeAlbumArtistHeroImageForPersistentID:(long long)arg1 configuration:(id)arg2;	// IMP=0x001000000008a37a
- (void)deprioritizeArtistHeroImageForPersistentID:(long long)arg1 configuration:(id)arg2;	// IMP=0x001000000008a213
- (void)setItemProperties:(id)arg1 forPurchaseHistoryID:(unsigned long long)arg2 configuration:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x001000000008a008
- (void)hideItemsWithPurchaseHistoryIDs:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000089e23
- (void)loadBooksForStoreIDs:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000089a2e
- (void)loadScreenshotInfoForPurchaseHistoryIDs:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000897ef
- (void)loadArtworkInfoForPurchaseHistoryIDs:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000895b0
- (void)deprioritizeScreenshotForPurchaseHistoryID:(unsigned long long)arg1 configuration:(id)arg2;	// IMP=0x0010000000089450
- (void)deprioritizeItemArtworkForPurchaseHistoryID:(unsigned long long)arg1 configuration:(id)arg2;	// IMP=0x00100000000892f0
- (void)importScreenshotForPurchaseHistoryID:(unsigned long long)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000089126
- (void)importItemArtworkForPurchaseHistoryID:(unsigned long long)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000088f5c
- (void)loadJaliscoUpdateProgressForConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000088d7a
- (void)loadIsJaliscoUpdateInProgressForConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000088ba0
- (void)isMediaKindDisabledForJaliscoLibrary:(long long)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000088986
- (void)removeJaliscoLibraryForConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000008877c
- (void)setupInitialJaliscoPoolingForConfiguration:(id)arg1;	// IMP=0x0010000000088460
- (void)unfavoritePlaylistWithGlobalID:(id)arg1 time:(id)arg2 configuration:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x0010000000088245
- (void)unfavoriteArtistWithCloudLibraryID:(id)arg1 time:(id)arg2 configuration:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x001000000008802a
- (void)unfavoriteAlbumWithCloudLibraryID:(id)arg1 time:(id)arg2 configuration:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x0010000000087e0f
- (void)unfavoriteEntityWithSagaID:(long long)arg1 entityType:(long long)arg2 time:(id)arg3 configuration:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;	// IMP=0x0010000000087c05
- (void)unfavoriteEntityWithStoreID:(long long)arg1 entityType:(long long)arg2 time:(id)arg3 configuration:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;	// IMP=0x00100000000879fb
- (void)favoriteArtistWithCloudLibraryID:(id)arg1 time:(id)arg2 configuration:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x00100000000877e0
- (void)favoriteAlbumWithCloudLibraryID:(id)arg1 time:(id)arg2 configuration:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x00100000000875c5
- (void)favoriteEntityWithSagaID:(long long)arg1 entityType:(long long)arg2 time:(id)arg3 configuration:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;	// IMP=0x00100000000873bb
- (void)favoritePlaylistWithGlobalID:(id)arg1 time:(id)arg2 configuration:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x00100000000871a0
- (void)favoriteEntityWithStoreID:(long long)arg1 entityType:(long long)arg2 time:(id)arg3 configuration:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;	// IMP=0x0010000000086f96
- (void)sdk_addStoreItemWithOpaqueID:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000086e8c
- (void)sdk_addItemWithSagaID:(long long)arg1 toPlaylistWithPersistentID:(long long)arg2 configuration:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x0010000000086c7b
- (void)sdk_addStoreItemWithOpaqueID:(id)arg1 toPlaylistWithPersistentID:(long long)arg2 configuration:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x0010000000086a00
- (void)sdk_createPlaylistWithPersistentID:(long long)arg1 properties:(id)arg2 trackList:(id)arg3 configuration:(id)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x0010000000086785
- (void)setAlbumProperties:(id)arg1 forAlbumPersistentID:(long long)arg2 configuration:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x001000000008657a
- (void)uploadCloudPlaylistPropertiesForConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000863c7
- (void)uploadCloudItemPropertiesForConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000086214
- (void)setItemProperties:(id)arg1 forSagaID:(unsigned long long)arg2 configuration:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x0010000000086009
- (void)loadLastKnownEnableICMLErrorStatusForConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000085e36
- (void)removeItemsWithSagaIDs:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000085c51
- (void)addStorePlaylistWithGlobalID:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000085a0e
- (void);	// IMP=0x00100000000857bb
- (void)updateSubscribedPlaylistsWithSagaIDs:(id)arg1 ignoreMinRefreshInterval:(_Bool)arg2 configuration:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x00100000000855a8
- (void)uploadArtworkForPlaylistWithPersistentID:(long long)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000853de
- (void)removePlaylistsWithSagaIDs:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000851f9
- (void)publishPlaylistWithSagaID:(long long)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000084fce
- (void)addItemWithSagaID:(long long)arg1 toPlaylistWithPersistentID:(long long)arg2 configuration:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x0010000000084def
- (void)addStoreItemWithAdamID:(long long)arg1 referral:(id)arg2 toPlaylistWithPersistentID:(long long)arg3 configuration:(id)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x0010000000084bb6
- (void)sdk_setPlaylistProperties:(id)arg1 trackList:(id)arg2 forPlaylistPersistentID:(long long)arg3 configuration:(id)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x001000000008493f
- (void)setPlaylistProperties:(id)arg1 trackList:(id)arg2 forPlaylistPersistentID:(long long)arg3 configuration:(id)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x00100000000846f9
- (void)createPlaylistWithPersistentID:(long long)arg1 properties:(id)arg2 trackList:(id)arg3 configuration:(id)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x001000000008445b
- (void)addGeniusPlaylistWithPersistentID:(long long)arg1 name:(id)arg2 seedItemSagaIDs:(id)arg3 itemSagaIDs:(id)arg4 configuration:(id)arg5 completion:(CDUnknownBlockType)arg6;	// IMP=0x00100000000841cd
- (void)loadGeniusItemsForSagaID:(unsigned long long)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000083fa4
- (void)loadScreenshotInfoForSagaIDs:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000083d65
- (void)loadArtworkInfoForContainerSagaIDs:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000083b26
- (void)loadArtworkInfoForSagaIDs:(id)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000838e7
- (void)deprioritizeContainerArtworkForSagaID:(unsigned long long)arg1 configuration:(id)arg2;	// IMP=0x0010000000083787
- (void)deprioritizeScreenshotForSagaID:(unsigned long long)arg1 configuration:(id)arg2;	// IMP=0x0010000000083627
- (void)deprioritizeItemArtworkForSagaID:(unsigned long long)arg1 configuration:(id)arg2;	// IMP=0x00100000000834c7
- (void)importContainerArtworkForSagaID:(unsigned long long)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000832fd
- (void)importScreenshotForSagaID:(unsigned long long)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000083133
- (void)importItemArtworkForSagaID:(unsigned long long)arg1 configuration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000082f69
- (void)loadSagaUpdateProgressForConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000082d84
- (void)loadIsSagaUpdateInProgressForConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000082baa
- (void)setCloudAddToPlaylistBehavior:(long long)arg1 forConfiguration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000829e0
- (void)deauthenticateForConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000082826
- (void)updateJaliscoLibraryWithReason:(long long)arg1 forConfiguration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000008265c
- (void)isSagaAuthenticatedForConfiguration:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000008256f
- (void)setPreferredVideoQuality:(long long)arg1 forConfiguration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000824c7
- (void)updateSagaLibraryWithReason:(long long)arg1 forConfiguration:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000822f6
- (void)setupInitialSagaPoolingForConfiguration:(id)arg1;	// IMP=0x00100000000820e7
- (id)initWithHandlerProvider:(id)arg1;	// IMP=0x0010000000082023

@end

