//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray;

@interface JaliscoHideItemOperation
{
    NSArray *_itemPurchaseHistoryIDs;	// 8 = 0x8
}

+ (_Bool)supportsSecureCoding;	// IMP=0x00400000000b96e5
- (void).cxx_destruct;	// IMP=0x00200000000b939b
- (void)main;	// IMP=0x00100000000b8e5e
- (_Bool)isPersistent;	// IMP=0x00100000000b8e56
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00100000000b8dd9
- (id)initWithCoder:(id)arg1;	// IMP=0x00100000000b8ccf
- (id)initWithConfiguration:(id)arg1 clientIdentity:(id)arg2 itemPurchaseHistoryIDs:(id)arg3;	// IMP=0x00100000000b8c41
- (id)initWithItemPurchaseHistoryIDs:(id)arg1;	// IMP=0x00100000000b8bbb

@end

